### ISSUE TITLE
SSL cert skip

### ISSUE THREAD

**Issue by arnaldojvg** [crossbario/autobahn-python#1001]
I wrote a simple wss app with (based in echo_tls server) using:
contextFactory = ssl.DefaultOpenSSLContextFactory('key.key', 'cert.crt')
..
.
webdir.contentTypes['.crt'] = 'application/x-x509-ca-cert'
reactor.listenSSL(8080, web, contextFactory)

When i try to connect with the classic websocket-client python module i HAVE to use it like this:
a = ws.create_connection("wss://localhost", sslopt={"cert_reqs": ssl.CERT_NONE})
And when i try to connect from js or nodejs i have conflicts with the cert...

Is there a way server-side to keep the wss but skip the client-side cert param??

**Comment by meejah** [comment]
Sounds like maybe you're using a self-signed certificate? Try something that's trusted by browsers, like Let's Encrypt.
