### ISSUE TITLE
Original exception class name can be useful in ApplicationError instance

### ISSUE THREAD

**Issue by blinkingmatt** [crossbario/autobahn-python#1004]
- autobahn version 18.4.1

When transmitting an ApplicationError args and kwargs of original exception are included. It can be useful on the client side to also know the type of the exception.
So I would suggest to include the class name of the exception in autobahn.wamp.protocol.BaseSession._message_from_exception:

```
def _message_from_exception(self, request_type, request, exc, tb=None, enc_algo=None):
        """
        Create a WAMP error message from an exception.

        :param request_type: The request type this WAMP error message is for.
        :type request_type: int

        :param request: The request ID this WAMP error message is for.
        :type request: int

        :param exc: The exception.
        :type exc: Instance of :class:`Exception` or subclass thereof.

        :param tb: Optional traceback. If present, it'll be included with the WAMP error message.
        :type tb: list or None
        """
        args = None
        if hasattr(exc, 'args'):
            args = list(exc.args)  # make sure tuples are made into lists

        kwargs = None
        if hasattr(exc, 'kwargs'):
            kwargs = exc.kwargs

        if kwargs and six.PY2:
            kwargs = {
                k.decode('utf8'): v
                for k, v in kwargs.iteritems()
            }
            
        # begin
        # get class name of exception for later use
        if not isinstance( exc, exception.ApplicationError ):
            exc_type = str( exc.__class__ )
            
            import re
            # first search if 'class' in description
            reExcClass = re.compile( r"(?P<pre>\<class\s*)(?P<name>.+?)(?P<suf>\s*\>)" )
            # match "<class 'Modul.Exception'>" -> extract 'Modul.Exception'
            m = reExcClass.search( exc_type )
            if not m:
                # search for 'type' in description
                reExcType = re.compile( r"(?P<pre>\<class\s*)(?P<name>.+?)(?P<suf>\s*\>)" )
                # match "<type 'exceptions.ValueError'>" -> extract 'exceptions.ValueError'
                m = reExcType.search( exc_type ) 
            if m:
                exc_type = m.group( "name" )[1:-1]
            
                if kwargs:    
                    kwargs[u'error_class'] = exc_type
                else:
                    kwargs = { u'error_class': exc_type }
        # end

        if tb:
            if kwargs:
                kwargs[u'traceback'] = tb
            else:
                kwargs = {u'traceback': tb}
```

**Comment by blinkingmatt** [comment]
Hi Meejah,

Sometimes it is desirable to raise an instance of the original error on the client side (to mask the underlying WAMP framework). Since we have args and kwargs in ApplicationError we only need the class name oft he original error to accomplish this.

Thanks,
Matt

Von: meejah <notifications@github.com>
Gesendet: Dienstag, 22. Mai 2018 17:25
An: crossbario/autobahn-python <autobahn-python@noreply.github.com>
Cc: Matthias Kirst <matthias@blink-dx.com>; Author <author@noreply.github.com>
Betreff: Re: [crossbario/autobahn-python] Original exception class name can be useful in ApplicationError instance (#1004)


Can you describe what you're trying to do? If a not-ApplicationError-exception is raised it should come through in the error_class attribute (looking at the above code).

**Comment by oberstet** [comment]
the error class is Python specific, but WAMP is language agnostic

**Comment by blinkingmatt** [comment]
But we have args and kwargs ... (which are Python specific).
Language specific information in my opinion is ok - it is only information for the client, nothing depends on it.
At least one can just monitor this info.

**Comment by oberstet** [comment]
args and kwargs are not Python specific, and sending language specific serialization types to the wire is a WAMP protocol violation (unless payload transparency is used).

**Comment by blinkingmatt** [comment]
Ok. I give up ...
But a string is not a language specific serialization type.

**Comment by oberstet** [comment]
Not the string in itself (sorry, I can see how my wording is misleading), but the semantics attached to it: a Python class name. Say I receive this in C++, what should I do with a Python class name?

You can transport whatever you like as application payload though, for example https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/wamp/rpc/errors/backend.py#L77
