### ISSUE TITLE
auth derive_key segmentation fault

### ISSUE THREAD

**Issue by francescofranze** [crossbario/autobahn-python#1009]
The implementation of wamp.auth.derive_key can raise a segfault if used with a high number of iterations (~ 100000).
The same issue is also [reported](https://github.com/mitsuhiko/python-pbkdf2/issues/2) in the original pbkdf2 library. 

A possible workaround is to flatten the nested iterators every N iterations (e.g N=1000), anyway the pure python implementation can take several seconds, sometimes this could be not very usable.

**Comment by oberstet** [comment]
you can use pypy to run autobahn with high performance
