### ISSUE TITLE
Can't get msgpack to work

### ISSUE THREAD

**Issue by dionytadema** [crossbario/autobahn-python#1015]
Hi, for a work project i'm trying to send binary data over wamp, this requires the msgpack serialization. However i can't get it to work.

i create my component with the code below:
```
connection = Component(
    transports=[{
        "url": u'ws://192.168.0.178:9000',
        "serializers": ['msgpack'],
        "max_retries": -1,
        "max_retry_delay": 20  # seconds
    }],
    realm=u'main',
)
```
when connecting to my router (https://github.com/gammazero/nexus) i get the following error:
`dropping connection to peer tcp4:192.168.0.178:9000 with abort=True: I dropped the WebSocket TCP connection: The server does not speak any of the WebSocket subprotocols  we requested.`

the router however does support msgpack, and using it with Autobahn|Js works fine with this js code:
```
var connection = new autobahn.Connection({
		realm: "main",
		transports: [{
			type: 'websocket',
			url: "ws://192.168.0.178:9000",
			protocols: ['wamp.2.msgpack']
		}],
	})
connection.open()
```

 i attached a 'not' working example (txt as .py is not supported for uploads)

[test.txt](https://github.com/crossbario/autobahn-python/files/2072496/test.txt)

**Comment by oberstet** [comment]
looks like the router does not announce wamp properly. please ask upstream .. or use crossbar.

**Comment by dionytadema** [comment]
i have checked in the sorcecode of the nexus router and it does follow the [RCF6455](https://tools.ietf.org/html/rfc6455#section-4) and does announce support for wamp.2.msgpack

I noticed that the request send from Autobahn python does not even list msgpack. so the problem is in Autobahn python, for some reason setting msgpack on the transport in the component doesn't propagate and is not added to the subprotocol list in the HTTP GET request send to upgrade to a websocket connection.

in the example code above the error should also list the sub protocols but it's list is empty

**Comment by dionytadema** [comment]
well now on a diferent system it is suddenly working :/

**Comment by jurjen96** [comment]
Had the same issue, fixed it by installing `pip install u-msgpack-python==2.5.0`.

**Comment by oberstet** [comment]
`pip install autobahn[compression]` will install the (optional) dependencies that make (all) alternative serializers work by installing the necessary requirements.

`pip install autobahn`: will only install the absolute minimum (not even Twisted, so the former will only be usable on Python 3.5+ which includes full asyncio)
