### ISSUE TITLE
asyncio/websocket.py not compatible with Python 3.7 syntax changes

### ISSUE THREAD

**Issue by Ardonius** [crossbario/autobahn-python#1022]
This change in Python 3.7:

> Backwards incompatible syntax changes:
> 
> async and await are now reserved keywords.

Broke this code block in asyncio/websocket.py:
```
if hasattr(asyncio, 'ensure_future'):
    ensure_future = asyncio.ensure_future
else:  # Deprecated since Python 3.4.4
    ensure_future = asyncio.async
```

Example failure log:

```
Traceback (most recent call last):
 File REDACTED, line 18, in <module>
   from autobahn.asyncio.websocket import WebSocketServerFactory, WebSocketServerProtocol
 File “/usr/local/lib/python3.7/site-packages/autobahn/asyncio/__init__.py”, line 36, in <module>
   from autobahn.asyncio.websocket import \
 File “/usr/local/lib/python3.7/site-packages/autobahn/asyncio/websocket.py”, line 52
   ensure_future = asyncio.async
                               ^
SyntaxError: invalid syntax
```

I fixed the issue locally by just deleting the old import, but I don't know what preferred fix in autobahn official library is.  It would probably work to use getattr(asyncio, "async") to preserve backwards compatibility while still respecting the new Python 3.7 syntax rules.

**Comment by meejah** [comment]
Thanks for the report! We will want to support Python 3.4 for now, some OSes still ship that by default.

**Comment by oberstet** [comment]
yeah, we should continue supporting 3.4+ (and 2.7)

**Comment by nicolas-leydet** [comment]
> from @meejah 
> We will want to support Python 3.4 for now

The fix proposed by @Ardonius should do exactly that:

```
if hasattr(asyncio, 'ensure_future'):
    ensure_future = asyncio.ensure_future
else:  # Deprecated since Python 3.4.4
    ensure_future = getattr(asyncio, "async")
```

**Comment by agronholm** [comment]
I stumbled onto this too but testing the fix has been problematic as pytest_asyncio runs into the same problem.

**Comment by agronholm** [comment]
Actually this is not the case with the current release of pytest_asyncio. Why does autobahn's test suite depend on pytest_asyncio < 0.6?

**Comment by agronholm** [comment]
Even if I use the latest version, the test suite still fails because it tries to import a nonexistent module (`asyncio.test_utils`).
