### ISSUE TITLE
Configuring a proxy for a WAMP Component not possible

### ISSUE THREAD

**Issue by rndwb** [crossbario/autobahn-python#1026]
Hi, I'm using a asyncio WAMP Component like described in https://autobahn.readthedocs.io/en/latest/wamp/programming.html#running-components but I can't find a way to connect via a proxy server.

It looks like the `ApplicationRunner` gets a `proxy` parameter but writing WAMP components via subclassing it is discouraged and I like the new interface better than the subclassing approach.

Is there a way to get a connection through a proxy via the "new" way?

**Comment by oddjobz** [comment]
Hi, just to fully understand the issue, could you document your 'use-case' for this? i.e. why you want or need to connect via a proxy?

**Comment by oberstet** [comment]
@meejah FWIW, Autobahn has proxy support at the WebSocket layer via `proxy` argument to `WebSocketClientFactory`: https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L3796

We should expose that feature at the WAMP layer for both "old API" and "new API" (component). Not sure what the current status is ..

**Comment by rndwb** [comment]
>  could you document your 'use-case' for this?

I'm behind a corporate firewall and the only way to connect to the internet is through a proxy. Therefore I can't connect a service running locally to a router running on AWS right now.

> We should expose that feature at the WAMP layer for both "old API" and "new API" (component). Not sure what the current status is ..

In the "old API" the ApplicationRunner takes a proxy kwarg but I couldn't find anything like that in the Component API.

**Comment by meejah** [comment]
It probably doesn't look too hard to expose some proxy configuration via Component -- but yes currently that is not done. This is an HTTP proxy right? (Not SOCKS?)

**Comment by oberstet** [comment]
Autobahn only supports HTTP proxies for WebSocket (so no SOCKS)

**Comment by meejah** [comment]
I don't see anything in the asyncio side for proxy stuff -- is this also missing currently? (i.e. is proxy support twisted-only?)

**Comment by meejah** [comment]
I added asyncio support in component too..
