### ISSUE TITLE
Asyncio component fails to initialize serializers when using raw sockets

### ISSUE THREAD

**Issue by aberres** [crossbario/autobahn-python#1029]
Given a router awaiting raw socket connections on port 8081 the following fails
```
autobahn.asyncio.component.Component(transports=[{"type": "rawsocket", "url": "rs://127.0.0.1:8081",  "endpoint": {"type": "tcp", "host": "127.0.0.1", "port": 8081}]}
```

with this backtrace

```
2018-07-30T14:59:14 Exception in callback RawSocketClientProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle RawSocketClientProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/autobahn/asyncio/rawsocket.py", line 248, in connection_made
    self._length_exp << 4 | self.serializer_id,
  File "/Users/berres/venv/mpptool/lib/python3.5/site-packages/autobahn/asyncio/rawsocket.py", line 411, in serializer_id
    self._serializer = self.factory._serializer()
TypeError: 'MsgPackSerializer' object is not callable
```

When looking at the code it seems as if `_create_transport_serializer()` in `asyncio/component.py` is instantiating the serializer while the rawsocket is expecting a class object it can initialize.
Removing the initialization in either place allows a successful connection.

I am also wondering why I need to set `endpoint` and `url` when specifying the transport. One of the should be enough I guess.

**Comment by aberres** [comment]
Just noticed I have not the most recent version installed.
It is working fine with 18.7 👍

**Comment by oberstet** [comment]
good to hear you got it .. thx for coming back and closing the issue (housekeepng)!

**Comment by meejah** [comment]
@aberres you should be able to just give a "url" when using the Component API (and it'll infer the endpoint from it). Did you try and it doesn't work?

**Comment by aberres** [comment]
@meejah See #1031
