### ISSUE TITLE
Unix transport: url parameter required though not used

### ISSUE THREAD

**Issue by haizaar** [crossbario/autobahn-python#1062]
Trying to utilize the following component configuration:

```python
component = Component(
    transports=[
        {
            "type": "rawsocket",
            "endpoint": {
                "type": "unix",
                "path": "/tmp/crossbar.sock",
            }
        }
    ],
    realm="mine",
)
```
Fails with:
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    realm="mine",
  File ".../lib/python3.7/site-packages/autobahn/wamp/component.py", line 461, in __init__
    _create_transport(idx, transport, self._check_native_endpoint)
  File ".../lib/python3.7/site-packages/autobahn/wamp/component.py", line 213, in _create_transport
    url=transport['url'],
KeyError: 'url'
```

Looking at the [code](https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/component.py#L223), transport creator indeed requires it, but nothing is actually done with this parameter down the road (in case of unix connection again).

E.g. the following works just fine:
```python
component = Component(
    transports=[
        {
            "type": "rawsocket",
            "url": "not-in-use",
            "endpoint": {
                "type": "unix",
                "path": "/tmp/crossbar.sock",
            }
        }
    ],
    realm="mine",
)
```
(note the `url`).

Documentation does not see to say anything about urls for unix sockets. Bug?

**Comment by oberstet** [comment]
yep: `url` only makes sense for websocket, but there it has some use even when running over unix sockets. for rawsocket, no url is used for the protocol.

**Comment by haizaar** [comment]
I'm a bit confused - doen't unix socket imply rawsocket? (Or do you really support websocket over unix socket??)

**Comment by oberstet** [comment]
yes, crossbar supports websocket over unix domain socket. also every other protocol that crossbar supports. in general: crossbar supports every combination of:

* serializer: json, msgpack, cbor, ubjson, none ("transparency mode")
* framing: websocket, rawsocket
* bytes transport: tcp, tls, unix domain

it also supports some combinations for "longpoll" for "framing", and we could add H2 for framing as well.

**Comment by haizaar** [comment]
Thanks for the info. Really informative.
Just to clarity - the Component API is the one that's currently recommended, right?

**Comment by oberstet** [comment]
Component API is recommended, yep!

@meejah ^

**Comment by oberstet** [comment]
yes, component API is recommended.

@meejah ^

**Comment by oberstet** [comment]
fix will land via https://github.com/crossbario/autobahn-python/pull/1083
