### ISSUE TITLE
WebSocketServerProtocol instance leak

### ISSUE THREAD

**Issue by dimitar-kunchev** [crossbario/autobahn-python#1068]
I belive there might be a leak in twisted websocket implementation - the instances of WebSocketServerProtocol subclass are never garbage collected. I have reproduced that with the echo example by repeatedly connecting and disconnecting clients and observing the used memory on the server process. Also adding __del__ implementation on the server protocol instance and printing calls indicates it is never called.
Similar test with twisted Protocol subclass and Factory works fine - the instances are deleted when connection is closed. So I suppose the problem comes with the WebSocket implementation. Unfortunately I have not been able to identify what reference keeps them alive.
Testing with autobahn 18.10.1, python 3.5

**Comment by glyph** [comment]
For what it's worth, adding `__del__` changes the nature of a class's interaction with the garbage collector, and may cause it to become uncollectable garbage where previously it would have been found.

**Comment by meejah** [comment]
Might be related to #1064

**Comment by dimitar-kunchev** [comment]
> For what it's worth, adding `__del__` changes the nature of a class's interaction with the garbage collector, and may cause it to become uncollectable garbage where previously it would have been found.

I am not a python expert but I have heard that too. However I have confirmed it by just observing memory use too without code modifications. And besides - I am not sure having a `__del__` implementation would make a difference when the object is collected.

> Might be related to #1064

I thought that but it talks about TLS only and I have verified it with unencrypted socket. But I haven't examined the proposed fix to see if it applies here too. Will do and report back.

**Comment by muhammadsyahyas** [comment]
Found similar problem

**Comment by muhammadsyahyas** [comment]
I tried using tornado websocket server and got memory leak too. This is really interesting. Here is the code:

```
import sys
import json
import logging
import tornado.escape
import tornado.ioloop
import tornado.options
import tornado.web
import tornado.websocket
import tornado.httpserver
from tornado.options import define, options

define("port", default=8000, help="run on the given port", type=int)

clients = set()

class BroadcastServerHandler(tornado.websocket.WebSocketHandler):
    def open(self):
        clients.add(self)
        print("Connected client {}".format(self.request.remote_ip))
      
    def on_message(self, message):
        msg = json.loads(message)
        try:
            if msg['command'] == 'feeder':
                print("Received feed and data from {}".format(self.request.remote_ip))
                for c in clients:
                    c.write_message(json.dumps(msg))
                    print("Message sent to {}".format(c.request.remote_ip))
        except:
            pass
 
    def on_close(self):
        clients.remove(self)
        print("Disconnected client {}".format(self.request.remote_ip))
 
    def check_origin(self, origin):
        return True
 
application = tornado.web.Application([
    (r'/', BroadcastServerHandler),
])

if __name__ == '__main__':
    http_server = tornado.httpserver.HTTPServer(application)
    http_server.listen(options.port)
    print("Websocket Server Started")
    tornado.ioloop.IOLoop.current().start()
```


![screenshot from 2018-11-01 18-11-09](https://user-images.githubusercontent.com/34974598/47849352-d2573980-de03-11e8-958c-f6cdf1acbe47.png)

Even when the "feeder" client closed the connection, the memory usage of the websocket server is still high.

![screenshot from 2018-11-01 18-11-52](https://user-images.githubusercontent.com/34974598/47849358-d71bed80-de03-11e8-9fc9-d00858ee12ab.png)

**Comment by oberstet** [comment]
cannot reproduce
