### ISSUE TITLE
Error handling with multiple concurrent connections

### ISSUE THREAD

**Issue by oddjobz** [crossbario/autobahn-python#1078]
@meejah as per our discussion on slack; if you have a WAMP client that runs multiple concurrent connections via the Component interface, and one of those connections errors, AND in the event you have retries turned off, an exception makes it's way back up the chain causing 'run' to exit. So if you are for example connecting to three different Crossbar's, and ONE of the connections to one of the Crossbar's fails, the entire app will fail. Sample code;
```python
#!/usr/bin/env python3

import sys
from autobahn.asyncio.component import Component
from autobahn.asyncio.component import run
from autobahn.wamp.types import SubscribeOptions
import txaio
txaio.use_asyncio()
#
log = txaio.make_logger()
if sys.argv[-1] == '--debug':
    sys.argv.pop()
    txaio.start_logging(level='debug')
else:
    txaio.start_logging(level='info')
#
#
routers = []
router_definitions = [
    [
        {'name': 'instance1', 'url': 'ws://localhost:8091/ws', 'realm': 'realm1'},
        {'name': 'instance2', 'url': 'ws://localhost:8092/ws', 'realm': 'realm1'},
        {'name': 'instance3', 'url': 'ws://localhost:8093/ws', 'realm': 'realm1'},
    ]
]


class RouterComponent(Component):

    def __init__(self, router):

        self._router = router
        self._session = None
        transports = {
            'url': router['url'],
            'max_retries': 0
        }
        super().__init__(
            transports=[transports],
            realm=router['realm']
        )

    def startup(self):
        self.on_join(self.on_connection_join)
        self.on_leave(self.on_connection_leave)
        return self

    @property
    def name(self):
        return self._router['name']

    async def on_connection_join(self, session, details):

        self._session = session
        options = SubscribeOptions(match='exact', details=True)
        await session.subscribe(self.subscription_on_create, 'wamp.subscription.on_create', options)
        await session.subscribe(self.subscription_on_subscribe, 'wamp.subscription.on_subscribe', options)
        await session.subscribe(self.subscription_on_unsubscribe, 'wamp.subscription.on_unsubscribe', options)
        await session.subscribe(self.subscription_on_delete, 'wamp.subscription.on_delete', options)

    async def on_connection_leave(self, session, details):
        log.info(f'on_connection_leave: [{self.name}]: {details}')

    async def subscription_on_data(self, data, details=None):
        log.info(f'subscription_on_data [{self.name}]: {data} :: {details.topic}')

    async def subscription_on_create(self, session_id, sub_details, details=None):
        log.debug(f'subscription_on_create [{self.name}]: session_id={session_id} :: id={sub_details["id"]} uri={sub_details["uri"]}')

    async def subscription_on_subscribe(self, session_id, sub_id, details):
        log.debug(f'subscription_on_subscribe [{self.name}]: session={session_id} :: sub_id={sub_id}')

    async def subscription_on_unsubscribe(self, session_id, sub_id, details):
        log.debug(f'subscription_on_unsubscribe [{self.name}]: session={session_id} :: sub_id={sub_id}')

    async def subscription_on_delete(self, session_id, sub_id, details=None):
        log.debug(f'subscription_on_delete: session={session_id} :: sub_id={sub_id}')


if __name__ == "__main__":

    for router in router_definitions[0]:
        component = RouterComponent(router).startup()
        routers.append(component)

    run(routers)
```
Sample output, run application, then Ctrl+C in one of the crossbar consoles;
```python
$ ./substest.py
2018-11-07T11:04:15 connecting once using transport type "websocket" over endpoint "tcp"
2018-11-07T11:04:15 connecting once using transport type "websocket" over endpoint "tcp"
2018-11-07T11:04:15 connecting once using transport type "websocket" over endpoint "tcp"
2018-11-07T11:04:18 session leaving 'wamp.close.transport_lost'
2018-11-07T11:04:18 on_connection_leave: [instance2]: CloseDetails(reason=<wamp.close.transport_lost>, message='WAMP transport was lost without closing the session before')
2018-11-07T11:04:18 Connection failed: TransportLost: failed to complete connection
2018-11-07T11:04:18 Component failed: Exhausted all transport connect attempts
2018-11-07T11:04:18 Component '<__main__.RouterComponent object at 0x7f51278eab00>' error: RuntimeError: Component failed: Exhausted all transport connect attempts
```
**Specific use-case**

I want to be able to connect to a dynamic list of Crossbar servers, in the instance one should fail, I want to remove it from the list and potentially add a new one. Currently I don't get the chance because the entire app exits on an exception.

... I think the exception stems from wamp/component.py here;
```python
    dl = []
    for comp in components:
        d = component_start(comp)
        dl.append(d)
    done_d = txaio.gather(dl, consume_exceptions=False)

    def all_done(arg):
        log.debug("All components ended; stopping reactor")
        done_callback(reactor, arg)
```
i.e. the consume_exceptions = False

**Comment by meejah** [comment]
Interesting, never anticipated that `Component` would be sub-classed ;)

This might be a case where you'd need your own "run"-type method; the semantics for "run" are basically: keep all these `Component`s running, and if any of them fail outright, then fail. So in the above, one of your components is failing ("`wamp.close.transport_lost`").

Have you already tried the `is_fatal` suggestion? (e.g. add an `is_fatal` handler that says nothing is fatal)

**Comment by meejah** [comment]
Also, why are you starting logging yourself but also using `run`..?

**Comment by oberstet** [comment]
yeah, agreed. I mean, not subclassing .. was a major reason for Component in the first place.

**Comment by meejah** [comment]
@oberstet I think this might be for monitoring multiple routers? (But also, yeah: why not just re-connect to them .. or let the component keep trying to re-connect, anyway)

**Comment by meejah** [comment]
So, I wasn't even thinking "HA stuff" here, just wondering why you'd want to have a component "just stop running" while other ones do -- but I guess there's going to be use-cases for that, so ..

**Comment by oddjobz** [comment]
For Crossbar OS users for example, if you want to monitor your systems, and you've split your environment using a number of Crossbars, you may well want to connect to all of your crossbars for stats and uptime .. in this context, crossbars will reboot (or crash, or be upgraded) and you may want to add or remove environments .. in these instances, you probably don't want your monitor to terminate ... :) .. or you may want to notify a process running in one environment of an event in another environment, so you may want your own simple notification bridge that may need to connect to one or more crossbars .. same applies ... generically, whereas the 'terminate when all components have finished' makes complete sense to me, 'terminate when one component suffers a disconnect' .. less so ..

**Comment by meejah** [comment]
Well, okay that's a fine use-case -- but why not just handle `join` and `leave` events? That is, your component keeps "running" (i.e.trying to re-connect) to the now-down crossbar instance. If you just drop a component out of the `run` list, how would it ever get back into that list?

I guess what I'm getting at here is: the right way to learn if your `Component` is connected or not is via the leave/join events. The only use-case I see for `max_retries=0` is if you're writing a quick one-off client that you want to connect ONCE only, but see an immediate failure if the connection fails (so, e.g. maybe some kind of "status" CLI command or similar).

**Comment by oddjobz** [comment]
Ok, so for the monitor example, if I have a new Crossbar to monitor, would I not want to add a component to the array of active components, rather than restarting the app? (and the reverse if a crossbar instance becomes obsolete or fails permanently?)

**Comment by oberstet** [comment]
Managing multiple connections is outside the scope of the component API - the component API is about this use: run multiple app components on over one WAMP connection.

**Comment by meejah** [comment]
@oberstet well, no it can run mulitple WAMP connections too .. but yes the API never really anticipated trying to add and remove components themselves.

@oddjobz maybe, but that's not what your code is doing; it's just failing a component right away as soon as the connection dies (once). Anyway, my answer would be: yes, you should probably just re-start because you're re-configuring your monitoring application. (In general, it's pretty hard to get "dynamically re-load the configuration on-the-fly" correct .. I'm not suggesting that would be a bad thing to have, but definitely it's outside the scope of `run`).

If you're not really using the re-connect logic `Component` provides, **and** not using the promises of `run` this is really where you should just use `.start()` on `Component` directly and have your own main-loop (i.e. "don't use `run`"). At a bare minimum, `run` would need more features to support "add and remove components whenever". But it would likely make more sense to have a completely separate API for this (e.g. a `Service` in Twisted) and keep `run` simple and focused.

This would be like a kind of "dynamically manage `Component`s" API. That said, though, any "monitoring" application like this would have to be able to re-start. Once you have that feature, what's wrong with just using it to re-configure the list of expected "things to monitor"..?

**Comment by meejah** [comment]
In this vein, an API addition I think might make sense to `Component`: adding an `async def session()` which will: insist that `max_retries=0` (i.e. no reconnects) and fires with a `autobahn.wamp.Session` instance once connected (or an error). The use-case for this would be one-off clients that want a single WAMP session or an error, nothing else. So then you'd do something like:

```
my_component = Component(...)

async def main(reactor):
    session = await my_component.session()
    await session.call(...)
    # etc...
    await session.leave()
react(lambda r: ensureDeferred(main(r)))
```

For example, you want to connect to a WAMP router, make a few `call()`s and then leave. Probably for CLI tools, or similar.

**Comment by oddjobz** [comment]
@meejah 
> maybe, but that's not what your code is doing;

No, it's just a snippet for testing, bit it's what the code would like to do .. :)

Ok, this change to component.py modifies the exit behaviour, i.e. so it doesn't;
```python3
    done_d = txaio.gather(dl, consume_exceptions=True)
```
I'll have a think about a run() when I come back to what I was testing. In the meantime I hear what you're saying about restarting being the easy path, and it may well be a preferred option for many use-cases. That said for applications in general, having to restart the entire application just to reconfigure it, is not always what users want. If for example we had to restart the UI when someone added a new node, it wouldn't really qualify as a modern reactive SPA .. there might even be a few comments on google groups indicating that people might like to be able to reconfigure Crossbar without having to restart it ... ;)

I tweaked my example a little, just as a coding exercise .. is this what you meant by composition rather then inheritance .. or am I still missing something?

```python3
#!/usr/bin/env python3

from autobahn.asyncio.component import Component
from autobahn.asyncio.component import run
from autobahn.wamp.types import SubscribeOptions
import txaio
txaio.use_asyncio()
log = txaio.make_logger()


class Crossbars:

    class Crossbar:

        def __init__(self, name, port):
            self._name = name
            self._port = port

        @property
        def name(self):
            return self._name

        @property
        def port(self):
            return self._port

        @property
        def url(self):
            return f'ws://localhost:{self._port}/ws'

        @property
        def realm(self):
            return 'realm1'

    def __init__(self):
        self._instances = []

    def add(self, name, port):
        self._instances.append(self.Crossbar(name, port))

    def __iter__(self):
        return iter(self._instances)


class RouterComponent:

    def __init__(self, crossbar):
        self._crossbar = crossbar
        self._session = None
        transport = {'url': crossbar.url, 'max_retries': 0}
        self._component = Component(transports=[transport], realm=crossbar.realm)
        self._component.on_join(self.on_connection_join)
        self._component.on_leave(self.on_connection_leave)

    @property
    def component(self):
        return self._component

    @property
    def name(self):
        return self._crossbar.name

    async def on_connection_join(self, session, details):
        self._session = session
        options = SubscribeOptions(match='exact', details=True)
        await session.subscribe(self.subscription_on_create, 'wamp.subscription.on_create', options)
        await session.subscribe(self.subscription_on_subscribe, 'wamp.subscription.on_subscribe', options)
        await session.subscribe(self.subscription_on_unsubscribe, 'wamp.subscription.on_unsubscribe', options)
        await session.subscribe(self.subscription_on_delete, 'wamp.subscription.on_delete', options)

    async def on_connection_leave(self, session, details):
        log.info(f'on_connection_leave: [{self.name}]: {details}')

    async def subscription_on_data(self, data, details=None):
        log.info(f'subscription_on_data [{self.name}]: {data} :: {details.topic}')

    async def subscription_on_create(self, session_id, sub_details, details=None):
        log.debug(f'subscription_on_create [{self.name}]: session_id={session_id} :: id={sub_details["id"]} uri={sub_details["uri"]}')

    async def subscription_on_subscribe(self, session_id, sub_id, details):
        log.debug(f'subscription_on_subscribe [{self.name}]: session={session_id} :: sub_id={sub_id}')

    async def subscription_on_unsubscribe(self, session_id, sub_id, details):
        log.debug(f'subscription_on_unsubscribe [{self.name}]: session={session_id} :: sub_id={sub_id}')

    async def subscription_on_delete(self, session_id, sub_id, details=None):
        log.debug(f'subscription_on_delete: session={session_id} :: sub_id={sub_id}')


if __name__ == "__main__":

    crossbars = Crossbars()
    crossbars.add('instance1', 8091)
    crossbars.add('instance2', 8092)
    crossbars.add('instance3', 8093)

    routers = []
    for crossbar in crossbars:
        routers.append(RouterComponent(crossbar).component)

    run(routers)
```

**Comment by meejah** [comment]
Sorry for the delay. Something more like this, @oddjobz:

```
#!/usr/bin/env python3

import sys
from autobahn.asyncio.component import Component
from autobahn.asyncio.component import run
from autobahn.wamp.types import SubscribeOptions



urls = [
    'ws://localhost:8091/ws',
    'ws://localhost:8092/ws',
    'ws://localhost:8093/ws',
]


async def subscription_on_data(name, data, details=None):
    log.info(f'subscription_on_data [{name}]: {data} :: {details.topic}')


async def subscription_on_create(name, session_id, sub_details, details=None):
    log.debug(f'subscription_on_create [{name}]: session_id={session_id} :: id={sub_details["id"]} uri={sub_details["uri"]}')


async def subscription_on_subscribe(name, session_id, sub_id, details):
    log.debug(f'subscription_on_subscribe [{name}]: session={session_id} :: sub_id={sub_id}')


async def subscription_on_unsubscribe(name, session_id, sub_id, details):
    log.debug(f'subscription_on_unsubscribe [{name}]: session={session_id} :: sub_id={sub_id}')


async def subscription_on_delete(name, session_id, sub_id, details=None):
    log.debug(f'subscription_on_delete: session={session_id} :: sub_id={sub_id}')


components = []
for idx, url in enumerate(urls):
    comp = Component(
        transports=[
            "url": url,
            "max_retries": 0,
        ],
        realm="realm1",  # obviously, could come from 'urls' list or so instead
    )
    name = "router_{}".format(idx)

    # instead of "name" we could make a data-class style
    # MonitoredRouter or similar and bind the functions below to use
    # that instead (if, e.g., more than just "the name" is important)

    @comp.on_join
    def setup(session, details)
        options = SubscribeOptions(match='exact', details=True)
        await session.subscribe(
            partial(subscription_on_create, name)
            'wamp.subscription.on_create',
            options,
        )
        await session.subscribe(
            partial(subscription_on_subscribe, name),
            'wamp.subscription.on_subscribe',
            options,
        )
        await session.subscribe(
            partial(subscription_on_unsubscribe, name),
            'wamp.subscription.on_unsubscribe',
            options,
        )
        await session.subscribe(
            partial(subscription_on_delete, name),
            'wamp.subscription.on_delete',
            options,
        )

    @comp.on_leave
    def left(session, reason):
        log.info(f'on_connection_leave: {reason}')

    components.append(comp)


if __name__ == "__main__":
    run(components)
```

This is: simple, easy-to-test functions that are tied together by calling other functions, no complex classes and no subclassing of anything in Autobahn.
