### ISSUE TITLE
unregisterProducer raises "Exception: not implemented" after update to autobahn==18.11.1

### ISSUE THREAD

**Issue by mchfrnc** [crossbario/autobahn-python#1079]
After installation of the newest version of autobahn my script started throwing an exception, which was not present when previous version of library was used (autobahn==18.10.1). I don't know if it matters, but I'm running it in a Docker container.

Here is a simplified version the code:

**client.py**
```
import asyncio
import json

from autobahn.asyncio.websocket import WebSocketClientProtocol, WebSocketClientFactory


class MyServerProtocol(WebSocketClientProtocol):
    async def onConnect(self, request):
        print(f'Server connected: {request.peer}')

    async def onOpen(self):
        self.sendMessage(
            json.dumps({"action": "getversion", "data": {}}).encode()
        )

    async def onMessage(self, payload, isBinary):
        res = json.loads(payload.decode())
        print(res['response'])

    async def onClose(self, wasClean, code, reason):
        loop = asyncio.get_event_loop()
        loop.stop()


if __name__ == '__main__':
    factory = WebSocketClientFactory("ws://127.0.0.1:9000")
    factory.protocol = MyServerProtocol

    loop = asyncio.get_event_loop()
    loop.set_debug(1)
    try:
        coro = loop.create_connection(factory, '127.0.0.1', '9000')
        transport, client_protocol = loop.run_until_complete(coro)
        loop.run_forever()
    finally:
        loop.close()
```

**server.py**
```
import asyncio
import json

from autobahn.asyncio.websocket import WebSocketServerFactory, WebSocketServerProtocol


class MyServerProtocol(WebSocketServerProtocol):

    async def onConnect(self, request):
        print(f'[{request.peer} -> server] Connecting...')

    async def onOpen(self):
        print(f'Connection open {self.peer}')

    async def onClose(self, wasClean, code, reason):
        print(f'Connection {self.peer} closed: {reason} (code: {code})')

    async def onMessage(self, payload, isBinary):
        self._send_response({'response_for': 'getversion', 'response': '1.0'})
        self.sendClose()

    def _send_response(self, response):
        encoded_response = json.dumps(response).encode('utf8')
        self.sendMessage(encoded_response, fragmentSize=len(encoded_response))


def main():
    factory = WebSocketServerFactory(u"ws://127.0.0.1:9000")
    factory.protocol = MyServerProtocol

    loop = asyncio.get_event_loop()
    loop.set_debug(1)
    coro = loop.create_server(factory, '0.0.0.0', 9000)
    server = loop.run_until_complete(coro)

    try:
        loop.run_forever()
    finally:
        server.close()
        loop.close()


if __name__ == '__main__':
    main()
```

And below you can find a comaprision what happens, when I run it:

1) with autobahn==18.10.1

> user@f65a32fad83a:~$ pip freeze
> aioprocessing==1.0.1
> APScheduler==3.5.3
> atomicwrites==1.2.1
> attrs==18.2.0
> autobahn==18.10.1
> certifi==2018.10.15
> chardet==3.0.4
> coverage==4.5.1
> docker==3.5.1
> docker-pycreds==0.3.0
> docopt==0.6.2
> idna==2.7
> more-itertools==4.3.0
> pluggy==0.8.0
> py==1.7.0
> pytest==3.10.0
> pytest-asyncio==0.9.0
> pytest-cov==2.6.0
> pytest-mock==1.10.0
> pytz==2018.7
> PyYAML==3.13
> raven==6.9.0
> requests==2.20.0
> six==1.11.0
> SQLAlchemy==1.2.13
> txaio==18.8.1
> tzlocal==1.5.1
> urllib3==1.24.1
> websocket-client==0.54.0
> 
> Client side:
> user@f65a32fad83a:\~$ python path/to/client.py
> Server connected: tcp:127.0.0.1:9000
> 1.0
> user@f65a32fad83a:~$
> 
> Server side:
> user@f65a32fad83a:~$ python path/to/server.py
> [tcp:127.0.0.1:59440 -> server] Connecting...
> Connection open tcp:127.0.0.1:59440
> Connection tcp:127.0.0.1:59440 closed: None (code: 1000)

2) with autobahn==18.11.1

> user@761cfe8b6b2e:~$ pip freeze
> aioprocessing==1.0.1
> APScheduler==3.5.3
> atomicwrites==1.2.1
> attrs==18.2.0
> autobahn==18.11.1
> certifi==2018.10.15
> chardet==3.0.4
> coverage==4.5.1
> docker==3.5.1
> docker-pycreds==0.3.0
> docopt==0.6.2
> idna==2.7
> more-itertools==4.3.0
> pluggy==0.8.0
> py==1.7.0
> pytest==3.10.0
> pytest-asyncio==0.9.0
> pytest-cov==2.6.0
> pytest-mock==1.10.0
> pytz==2018.7
> PyYAML==3.13
> raven==6.9.0
> requests==2.20.0
> six==1.11.0
> SQLAlchemy==1.2.13
> txaio==18.8.1
> tzlocal==1.5.1
> urllib3==1.24.1
> websocket-client==0.54.0
> 
> Client side:
> user@761cfe8b6b2e:~$ python path/to/client.py
> Server connected: tcp:127.0.0.1:9000
> 1.0
> <Python is not finishing execution until server process is not terminated>
> 
> 
> Server side:
> user@761cfe8b6b2e:~$ python path/to/server.py
> [tcp:127.0.0.1:59472 -> server] Connecting...
> Connection open tcp:127.0.0.1:59472
> Exception in callback WebSocketAdapterProtocol._consume.<locals>.process(<Future finis...socket.py:108>) at /usr/local/lib/python3.6/site-packages/autobahn/asyncio/websocket.py:110
> handle: <Handle WebSocketAdapterProtocol._consume.<locals>.process(<Future finis...socket.py:108>) at /usr/local/lib/python3.6/site-packages/autobahn/asyncio/websocket.py:110 created at /usr/local/lib/python3.6/site-packages/autobahn/asyncio/websocket.py:122>
> source_traceback: Object created at (most recent call last):
>   File "path/to/server.py", line 45, in <module>
>     main()
>   File "path/to/server.py", line 38, in main
>     loop.run_forever()
>   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
>     self._run_once()
>   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1426, in _run_once
>     handle._run()
>   File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 734, in _read_ready
>     self._protocol.data_received(data)
>   File "/usr/local/lib/python3.6/site-packages/autobahn/asyncio/websocket.py", line 122, in data_received
>     self.waiter.set_result(None)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/usr/local/lib/python3.6/site-packages/autobahn/asyncio/websocket.py", line 114, in process
>     self._dataReceived(data)
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1182, in _dataReceived
>     self.consumeData()
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1194, in consumeData
>     while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1560, in processData
>     fr = self.onFrameEnd()
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1656, in onFrameEnd
>     self.processControlFrame()
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1706, in processControlFrame
>     if self.onCloseFrame(code, reasonRaw):
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 730, in onCloseFrame
>     self.dropConnection(abort=True)
>   File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 841, in dropConnection
>     self.unregisterProducer()
>   File "/usr/local/lib/python3.6/site-packages/autobahn/asyncio/websocket.py", line 196, in unregisterProducer
>     raise Exception("not implemented")
> Exception: not implemented

My Python version is 3.6.6.

I've found this issue: https://github.com/crossbario/autobahn-python/issues/875 and I think it might be related to my problem.

**Comment by jc53593** [comment]
Same issue here with Python 3.7.0 and the following:

# /opt/bin/pip3 freeze
aiomysql==0.0.19
asn1crypto==0.24.0
autobahn==18.11.1
cffi==1.11.5
cryptography==2.4.1
defusedxml==0.5.0
dnspython==1.15.0
easysnmp==0.2.5
idna==2.7
isodate==0.6.0
ldap3==2.5.1
lxml==4.2.5
pkgconfig==1.4.0
pyasn1==0.4.4
pycparser==2.19
PyMySQL==0.9.2
python3-saml==1.4.1
rrdtool==0.1.14
scapy==2.4.0
simplejson==3.16.0
six==1.11.0
srvlookup==2.0.0
txaio==18.8.1
xmlsec==1.3.3
