### ISSUE TITLE
Pausing after session establishment - Feature request for Component.create_session()

### ISSUE THREAD

**Issue by haizaar** [crossbario/autobahn-python#1088]
Good day,

I have a project where I would like to to bridge REST to WAMP. I'm using Python 3.7 with [aiohttp](https://aiohttp.readthedocs.io/en/stable/web.html#aiohttp-web).

Ideally, I would like to start an authbahn component, wait till the session is established, then stop the loop, pass the session object to aiohttp App, and start the loop again (with HTTP server already hooked in). Something like this:
```python
import asyncio
from autobahn.asyncio.component import Component
from aiohttp import web

async def main():
    loop = asyncio.get_event_loop()
    app = web.Application(loop=loop)
    
    wamp_session = await Coponent(...).create_session(loop=loop)  # <-- This is the missing method
    app["wamp_session"] = wamp_session
        
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, 'localhost', 8080)
    await site.start()
    loop.run_forever()

if __name__ == "__main__":
    asyncio.run(main())
```

Then I can use `wamp_session` from my HTTP request handlers, for example, to pass RPC results in web responses.

I can think of how it can be done with the current autobahn API, but it seems unclean/unnatural.

For example I can stop the loop from component's main function:
```python
    loop = asyncio.get_event_loop()
    wamp_session = await Coponent(main=lambda: loop.stop()).start(loop=loop)
    ...
```
Or I can start the HTTP server from the main function.

Again, it will work, but I think there should be a cleaner way. What do you think? Am I missing something?

**Comment by meejah** [comment]
Questions are better asked on the mailing-lists or in IRC (channel `#autobahn` on Freenode).

What will you do upon a re-connection? Why do you want to stop and re-start the loop?
