### ISSUE TITLE
Decorator returning None

### ISSUE THREAD

**Issue by Paradoxeuh** [crossbario/autobahn-python#1092]
Hi,

I am not sure it is a bug but I would like to understand why as soon as I register a function, it becomes impossible to access it. Here is a simple example

```
@comp.register("com.toto")
def toto():
    print("toto")

print(toto) # returns None
```

Why does toto disappear to become None? Is it intended and if yes why ? I'm asking that as I write some pytest and I would like to test functions without the crossbar.io stack in a first approach.
How broken would it be to use wraps from functools to be able to unwrap original functions ?

Thank you for this amazing lib !

**Comment by meejah** [comment]
Hmm, looking at the code, it does return the (wrapped) function. So I guess the answer is "I don't know why you see that behavior"...

**Comment by meejah** [comment]
Hi @Paradoxeuh does the attached branch fix your problems? I believe this is now more-correct behavior anyway (the decorator *should* return the wrapped function)..

**Comment by meejah** [comment]
...and just to clarify, the functions in this case *aren't actually wrapped* so there's e.g. no extra call overhead

**Comment by Paradoxeuh** [comment]
I cannot try it before next Monday, but by the look of it I would say it should totally fix my problem. I hope it will get merged soon, thanks !
