### ISSUE TITLE
Segmentation fault using large iteration count in autobahn.wamp.auth.derive_key() 

### ISSUE THREAD

**Issue by spr0cketeer** [crossbario/autobahn-python#1097]
>>> from autobahn.wamp import auth
>>> auth.derive_key('x', 'x', 150000, 32)
[1]    27137 segmentation fault (core dumped)  python

This happens on an autobahn client when using dynamic authentication in crossbar with Django as the backend - Django now using 150000 iterations in its pbkdf2 hasher https://github.com/django/django/blob/master/django/contrib/auth/hashers.py#L239

**Comment by oberstet** [comment]
yeah, I can repro the issue:

```
(cpy371_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ python
Python 3.7.1 (default, Dec  6 2018, 11:02:00) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autobahn.wamp import auth
>>> auth.derive_key('x', 'x', 150000, 32)
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by oberstet** [comment]
still there with the latest cpy 3.7.3. 100k iterations works fine though:

``` 
(cpy373_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx$ python
Python 3.7.3 (default, Apr 20 2019, 14:09:01) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autobahn.wamp import auth
>>> auth.derive_key('x', 'x', 15000, 32)
b'sm4ODgt0zxj/ycd36HTpCv/ev7TilE1iyAKzdllZ0vk='
>>> auth.derive_key('x', 'x', 20000, 32)
b'u66hPM8BSa9mBO7wiWaSLR0AmFgHaAASTfsimR4QTiU='
>>> auth.derive_key('x', 'x', 50000, 32)
b'9NMYF8WkdyY2Gc+GH5HFqjY0Na4E4/XFnNmpzoVjE8Q='
>>> auth.derive_key('x', 'x', 100000, 32)
b'7Y0kKpWAJloO5JARvAxqc2E0QVVJSyC/kG7yaJTg16o='
>>> auth.derive_key('x', 'x', 120000, 32)
Speicherzugriffsfehler (Speicherabzug geschrieben)
(cpy373_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx$ 
```

we should probably just `assert challenge.extra['iterations'] <= 100000`  ..

**Comment by meejah** [comment]
We're already (transitively) depending on cryptography.io, which has a PBKDF2 implementation. It doesn't segfault as above (at 150k iterations).

(Although, the above is maybe-even a python bug? in like `starmap` maybe?)
