### ISSUE TITLE
Tests fail with "import file mismatch"

### ISSUE THREAD

**Issue by lfam** [crossbario/autobahn-python#1117]
While working on a distro package for GNU Guix I found that Autobahn's tests fail to run.

For example:

```
______ ERROR collecting build/lib/autobahn/nvx/test/test_utf8validator.py ______
import file mismatch:
imported module 'test_utf8validator' has this __file__ attribute:
  /tmp/guix-build-python-autobahn-19.2.1.drv-0/autobahn-19.2.1/autobahn/nvx/test/test_utf8validator.py
which is not the same as the test file we want to collect:
  /tmp/guix-build-python-autobahn-19.2.1.drv-0/autobahn-19.2.1/build/lib/autobahn/nvx/test/test_utf8validator.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

This is with `Python 3.7.0`, `mock 2.0.0`, and `pytest 3.8.0`.

As a reminder, your `setup.py` specifies an older pytest in order to keep support for `Python 3.3`, but I "relaxed" that version requirement since we don't aim to support that older Python. 

So, my apologies if that is the cause of these test failures...

The packaging discussion is here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34515#95

**Comment by oberstet** [comment]
> I found that Autobahn's tests fail to run.

our tests run fine: https://travis-ci.org/crossbario/autobahn-python/builds/493230514

**Comment by PureTryOut** [comment]
The tests fail for me too with the same problems, this is on Alpine Linux with `pytest 6.1.2` and `Python 3.8.6`.

Did you have any luck with this @lfam?

**Comment by lfam** [comment]
Hi @PureTryOut ,

No, we didn't ever resolve the problem, so the Guix package still skips the test suite. In the Guix bug report (linked above), we suspected it was related to this issue in pytest itself:

https://github.com/pytest-dev/pytest/issues/529

**Comment by travankor** [comment]
Also running into this issue.

**Comment by PureTryOut** [comment]
Just a reminder that this is still broken with Python 3.10 and pytest 7.1.3.
