### ISSUE TITLE
Two corner cases

### ISSUE THREAD

**Issue by asodeur** [crossbario/autobahn-python#1118]
During clean-up I found a list of typos I bumped into while digging into `twisted`'s 
[IOCP reactor issue](https://github.com/crossbario/crossbar/issues/1347). Never encountered them outside load testing to date and forgot to report.

1. `wamp.protocol.ApplicationSession` throws exception if caller closes the transport before callee returns.
2. A `range()` argument in `websocket.protocol.WebSocketProtocol` might be a `float` in `py3` due to integer division

I'll open PRs shortly.

**Comment by oberstet** [comment]
thx for filing! two nasty hidden bugs hard to find ..

**Comment by oberstet** [comment]
and thanks for PRs! merged
