### ISSUE TITLE
Consider making CBOR default dependency

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1125]
Currently, cbor is an optional dependency that only gets installed when doing eg:

```
pip install autobahn[serialization]
```

The performance (when talking to crossbar) when using JSON is however less good than CBOR, and to avoid letting users fall into that trap without knowing, we might consider just making it a requirement in AB.

**Comment by om26er** [comment]
My experience with CBOR has been great and it has worked really nicely for my use cases. I guess the question mostly revolves around performance on low powered hardware (RPi for example). If its "good enough" then adding CBOR as a dep makes sense (IINM, Crossbar's serializer preference order is CBOR, MsgPack and then JSON).

One other question of course, falls on the stability of cbor lib we use in ABPy but then if its already chosen for Crossbar as default, we consider it stable enough.

So +1 on making that a dep.

**Comment by oddjobz** [comment]
Note: ABJS and CBOR, seems to want to use the 'node' version of CBOR .. which (?) doesn't seem to want to work atm (out of date?).  I hacked autobahn around a little to make it work with "cbor-js", which seems to work fine, although speedups are minimal (5%?). I guess the Python speeds are mainly down to the implementation / C extension .. bit of a shame Chrome doesn't support a native CBOR codec yet .. :(

**Comment by oberstet** [comment]
* for browser ABJS, that is also my experience: json will be faster due to the native VM integration etc
* for ABPy on PyPy, my experience is: cbor is fastest (very slightly to msgpack) and using a python-only cbor is good for security _and_ performance (JITted code is faster than calling into any native cbor extension .. via cffi and definitely any cpyext)

**Comment by oberstet** [comment]
by default, autobahn can make use of `cbor`, and it also allows to alternatively use `cbor2` by setting the env var AUTOBAHN_USE_CBOR2

rgd _requiring_ cbor: won't fix .. AB is now used in quite some places, and coming up with new mandatory deps (for no hard reason) isn't a good idea
