### ISSUE TITLE
PublishOptions / eligible over-reaching ...

### ISSUE THREAD

**Issue by oddjobz** [crossbario/autobahn-python#1133]
If I publish an event with publish options set to (eligible=[array]) where array is an array[n] (n>=1) of session id's, then the event only gets published to those session id's, and then only if those session id's are subscribed to the topic. If however the array is empty, the publish goes to all subscribed session id's, whereas I would expect it to go to none.

Sample code;
```python
    @inlineCallbacks
    def publish_node(self, key, doc, acl=None):
        if acl and not len(acl):
            log.info('|pub| nothing to publish')
            return
        include = [session['oid'] for session in self._model._sessions.values() if key == session['cur_node']]
        print('Include>', include)
        include.append(1)
        doc['oid'] = key
        yield self._gsession.publish('cfc.api.event', {'type': 'NodeStats', 'payload': doc}, options=PublishOptions(eligible=include))
        log.info(f'<stats> key="{key}"')
```
Without the "include.append", I will always see the event .. on adding the "include.append" to ensure the array is never zero length, then I will only get the event when my session has "cur_node" set to the key I'm interested in. (as intended)

**Comment by oberstet** [comment]
Just quickly: the issue should probably move to CB repo, and the issue, thinking about it: an empty list is falsey .. so this is a candidate reason for the observed behavior. And I would agree: it is definitely surprising that an empty list would behaves the same as "no list / None" and we should rectify that ..

**Comment by oberstet** [comment]
migrated to https://github.com/crossbario/crossbar/issues/1577
