### ISSUE TITLE
Easiest way to listen RabbitMQ events, and then publish to subscribers with with autobahn pubsub?

### ISSUE THREAD

**Issue by dreamjole** [crossbario/autobahn-python#1145]

**Comment by oberstet** [comment]
you need a MQTT client which subscribes to RabbitMQ and republishes to WAMP using Autobahn.

crossbar.io has buit-in MQTT support as in it can serve as a MQTT broker_and_ WAMP router at the same time and transparently bridge betwen those - but it (crossbar) cannot act as a MQTT client
