### ISSUE TITLE
WebSocketProtocol can leak handshake timeout DelayedCalls

### ISSUE THREAD

**Issue by exarkun** [crossbario/autobahn-python#1151]
`WebSocketProtocol._connectionMade` can create a delayed call for handshake timeout:

https://github.com/crossbario/autobahn-python/blob/0b0f3262903eb879a9ab6b313ab1a77e4d525726/autobahn/websocket/protocol.py#L1053-L1057

This is cleaned up:
* in `succeedHandshake`: https://github.com/crossbario/autobahn-python/blob/0b0f3262903eb879a9ab6b313ab1a77e4d525726/autobahn/websocket/protocol.py#L2984-L2987
* in `processHandshake`: https://github.com/crossbario/autobahn-python/blob/0b0f3262903eb879a9ab6b313ab1a77e4d525726/autobahn/websocket/protocol.py#L3710-L3715
* and on its own if it fires (with some help from `onOpenHandshakeTimeout`: https://github.com/crossbario/autobahn-python/blob/0b0f3262903eb879a9ab6b313ab1a77e4d525726/autobahn/websocket/protocol.py#L794)

But if none of these things happen, it is left in the event loop (until it fires).  A notable codepath that avoids all of the cleanups above is simple connection loss.  If a connection is opened to the protocol and then closed, the timeout is left dangling.

This is inconvenient for unit tests which then fail (if using Twisted) because of a "dirty" reactor error.  It may have other problematic consequences too (perhaps relating to availability of the server).

**Comment by oberstet** [comment]
> A notable codepath that avoids all of the cleanups above is simple connection loss.

oh, right! we are cleaning up other timers - but not `openHandshakeTimeoutCall` - here: https://github.com/crossbario/autobahn-python/blob/0b0f3262903eb879a9ab6b313ab1a77e4d525726/autobahn/websocket/protocol.py#L1060

**Comment by oberstet** [comment]
I have added the `asyncio` label as well .. this affects AB on both tx and aio (`autobahn/websocket/protocol.py` is the core websocket implementation, and that code is factored and used in both tx and aio)
