### ISSUE TITLE
self.authid not settable

### ISSUE THREAD

**Issue by Emantor** [crossbario/autobahn-python#1162]
```
crossbar URL: ws://127.0.0.1:20408/ws
crossbar realm: realm1
exporter name: dibooki
exporter hostname: dibooki
resource config file: export.yaml
2019-04-01T10:48:22 Future exception was never retrieved
future: <Future finished exception=AttributeError("can't set attribute")>
Traceback (most recent call last):
  File "/home/phoenix/.virtualenvs/labgrid-crossbar-bump/lib/python3.7/site-packages/txaio/aio.py", line 426, in as_future
    res = fun(*args, **kwargs)
  File "/home/phoenix/work/ptx/labgrid/labgrid/remote/exporter.py", line 321, in onConnect
    self.authid = "exporter/{}".format(self.name)
AttributeError: can't set attribute
```
Most likely due to the introduction of setters in #1137. Tested with latest labgrid master and a bump to crossbar and autobahn.

Am I supposed to set the authid differently? Code is [here](https://github.com/labgrid-project/labgrid/blob/897b3a55d89510602229ce45e0212a75e411e994/labgrid/remote/exporter.py#L321).

**Comment by oberstet** [comment]
you should not set this attribute: it is set internally during WAMP opening handshake

**Comment by Emantor** [comment]
Thanks.

**Comment by oberstet** [comment]
looking at your code, the fix is easy:

```python
def onConnect(self):
    ...
    "exporter/{}".format(self.name)
    self.join(self.config.realm,
                 authmethods=["ticket"],
                 authid="exporter/{}".format(self.name))
```

> sidenote: `authid` and `authmethods` are keyword arguments - technically, you can use positional args, but this might break should we ever reorder those (and since the function is kwarg based, that would "not break the interface")
