### ISSUE TITLE
wamp notification tool is broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1163]
apparently, the tool doesn't exit:

``` 
wamp --authid wheel_pusher --url ws://office2dmz.crossbario.com:8008/ --realm webhook call builder.wheel_pushed --keyword name autobahn-python --keyword publish true
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by meejah** [comment]
The key that you added to the repos, does it start with `d07...` ...?

**Comment by oberstet** [comment]
Dunno:( Travis will not allow me to look at the value of a secure var

**Comment by oberstet** [comment]
I can set a _new_ value if that makes tracking down easier of course - but I cannot find any button or what to look at the existing value ..

**Comment by meejah** [comment]
Okay, I've added some more diagnostics and a `--max-failures` to the tool, and will point you to the correct private-key for Travis. Perhaps what I'll do "until it's working" is put `--publish false` and put the notification somewhere that'll run "even on a PR branch" so I don't have to mess around on master...

**Comment by meejah** [comment]
Okay, it appears to be fixed with the existing keys. There were some requirements problems, basically.
