### ISSUE TITLE
remove dead _SessionShim code

### ISSUE THREAD

**Issue by sgoudelis** [crossbario/autobahn-python#1187]
Hello everyone,

I think there is an issue with the function _merged_authextra() in protocol.py (using autobahn 19.3.3 from pypi). When I want to authenticate against a single authenticator (as a client) and I use the authexra dict to feed in extra information into my dynamic authenticator, something weird happens. Occasionally, not consistently but quite frequently, the dict keys and values are scrambled. 

Example: I construct my Component like so:

```
    comp = Component(
        transports=[
            {
                'type': 'websocket',
                'url': os.environ.get('MYENTRYPOINT', config['ENTRYPOINTURL'])+'/'+transport,
            }
        ],
        realm=os.environ.get('ROUTERRLM', config['ENTRYPOINTRLM']),
        authentication={
            'wampcra': {
                'secret': password,
                'authid': username,
                'authrole': "frontend",
                'authextra': {
                    'pubkey': wamp_static_cryptosign_key.public_key(),
                    'totptoken': totptoken,
                }
            }
        },
        is_fatal=_handle_fatal)
```
It is CRA but I also provide the system with a public key for later use, not required in the auth process. I also verify a TOTP token given. 

On the dynamic authenticator side, instead of getting the authextras as:

```
{'pubkey': "somepubkey",'totptoken': "sometoken"}
```
I get them as 
```
{'pubkey': "sometoken",'totptoken': "somepubkey"}
```
They are now scrambled. If there was a third item there, that would be scrambled as well. Very odd behavior. I tracked down the issue to the function _merged_authextra() in protocol.py. I am not fully aware of your requirements and as a result I dont think I can provide a solution to this reliably, however it seems to me using the reduce() does not respect the order of the values given and also using set() has its own issues in case where an identical value exists in the dictionary. It will be overwritten essentially. 

I kind of hacked my way through the issue and it seems to me that this should work:
```
            return {
            k: v
            for k, v in zip(
                reduce(lambda x, y: x or list(y.keys()), authextras, list()),
                reduce(lambda x, y: x or list(y.values()), authextras, list())
            )
        }
```

Although I am highly uncertain if this full complies with the requirements of your method, so take it with great precaution. 

Please let me know what your thoughts are

**Comment by oberstet** [comment]
> I tracked down the issue to the function _merged_authextra() in protocol.py

this is dead (unused) code, and experimental "new API" which now actually became the "component API": https://autobahn.readthedocs.io/en/latest/wamp/programming.html#application-components

I guess this doesn't answer whatever problem you perceive to have, but I am renaming _this_ issue to reflect - we should remove the dead code:

* `autobahn.wamp.protocol._SessionShim`
* `autobahn.twisted.wamp.Session`
* `autobahn.ayncio.wamp.Session`

all this code is dead:

```
oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ find autobahn -name "*.py" -exec grep -Hi -A5 "_SessionShim" {} \;
autobahn/twisted/wamp.py:class Session(protocol._SessionShim):
autobahn/twisted/wamp.py-    # XXX these methods are redundant, but put here for possibly
autobahn/twisted/wamp.py-    # better clarity; maybe a bad idea.
autobahn/twisted/wamp.py-
autobahn/twisted/wamp.py-    def on_welcome(self, welcome_msg):
autobahn/twisted/wamp.py-        pass
autobahn/asyncio/wamp.py:class Session(protocol._SessionShim):
autobahn/asyncio/wamp.py-    # XXX these methods are redundant, but put here for possibly
autobahn/asyncio/wamp.py-    # better clarity; maybe a bad idea.
autobahn/asyncio/wamp.py-
autobahn/asyncio/wamp.py-    def on_welcome(self, welcome_msg):
autobahn/asyncio/wamp.py-        pass
autobahn/wamp/protocol.py:class _SessionShim(ApplicationSession):
autobahn/wamp/protocol.py-    """
autobahn/wamp/protocol.py-    shim that lets us present pep8 API for user-classes to override,
autobahn/wamp/protocol.py-    but also backwards-compatible for existing code using
autobahn/wamp/protocol.py-    ApplicationSession "directly".
autobahn/wamp/protocol.py-
```

**Comment by sgoudelis** [comment]
Thank you for your comments @oberstet. Am I not using the new Component API in the example I give above ?

**Comment by meejah** [comment]
`_SessionShim` (via `autobahn.twisted.component` or `autobahn.asyncio.component`) is used by `Component` at least for the authentication functionality (`_SessionShim` is what calls `.join()` for example). The `on_welcome` pep8-renaming stuff isn't critical to this, but `_SessionShim` (well, the framework-specific `Session` subclasses anyway) make the newer way of doing authentication work with `Component`.

**Comment by meejah** [comment]
Thanks for the report @sgoudelis -- yes, one of those uses of `set()` was incorrect .. I've tried to make the code more-readable this time too.

**Comment by oberstet** [comment]
@meejah ahh, ok! no "dead code" apparantly;) so `Component` is using eg `autobahn.twisted.wamp.Session` which in turn inherits `_SessionShim`? anyways, seems like you hint at an actual fix related to the set processing ..

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-python/pull/1191
