### ISSUE TITLE
Consider making WAMP command line tool python 2.7+ compatible

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1196]
The WAMP command line tool

https://github.com/crossbario/autobahn-python/blob/c3365f31e5e22aad19b9d054090be93d237a6091/setup.py#L267

is implemented in

https://github.com/crossbario/autobahn-python/blob/master/autobahn/__main__.py

and uses python 3.5+ syntax ("async def" etc).

as far as I can see, using txaio instead (and plain deferred approach instead of co-routines) would be possible, and would make the command line tool work on python 2.7+

**Comment by mojca** [comment]
I get the following just by installing autobahn:
```
byte-compiling /path/to/py27-autobahn/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autobahn/__main__.py to __main__.pyc
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/autobahn/__main__.py", line 239
    async def do_call(reactor, session, options):
            ^
SyntaxError: invalid syntax
```

**Comment by meejah** [comment]
Yes, supporting 2.7+ is entirely possible. We would still have to decide which framework to use (i.e. Twisted vs asyncio) ... but maaaaybe this could even be done via `try/except ImportError` (i.e. if you don't have Twisted try asyncio, then fail).
