### ISSUE TITLE
How to assign subscriber's topics from backend (check subscriber's authorization)

### ISSUE THREAD

**Issue by dsun-ge** [crossbario/autobahn-python#1210]
Say the front end is a web application that runs in browsers. Front end  (javascript) can send a token to the websocket server (python) so that the server can id the front end. Now from here, how can I make the front end subscribe the topics it is supposed to subscribe but nothing more?

**Comment by oddjobz** [comment]
If I understand the question ... then "yes". For more details, please redirect your questions to the forums at https://forum.crossbar.io/ .. :)
