### ISSUE TITLE
RuntimeError: could not create serializer for "cbor" (available: ['json'])

### ISSUE THREAD

**Issue by jcgertig** [crossbario/autobahn-python#1212]
```
self.__wamp = Component(
  transports=u"ws://router",
  realm=u"realm1"
)
run(self.__wamp)
```

With the above code I get the following error

connecting once using transport type "websocket" over endpoint "tcp"
Connection failed: RuntimeError: could not create serializer for "cbor" (available: ['json'])

What can I do to alleviate this?

**Comment by meejah** [comment]
Please ask questions in our forum: https://forum.crossbar.io/

**Comment by jcgertig** [comment]
@meejah I created as a post a few hours ago on the forum but says a staff member has to review.

**Comment by jcgertig** [comment]
@meejah  yeah that forum is terrible keeps suspending me making it so I cant reply

Requirement already satisfied: autobahn[cbor] in c:\users\jgertig\appdata\local\conda\conda\envs\python36\lib\site-packages (19.3.3)
  autobahn 19.3.3 does not provide the extra 'cbor'

**Comment by oberstet** [comment]
the command would be: `pip install autobahn[serialization]` 

see https://github.com/crossbario/autobahn-python/blob/51ab48c999777c566cd4c6e5a33ada34c80de3bb/setup.py#L238

**Comment by jcgertig** [comment]
Ahh I see thought that was a replace with the type thanks

**Comment by oberstet** [comment]
np;) btw, your post to the forum seems to be public https://forum.crossbar.io/t/runtimeerror-could-not-create-serializer-for-cbor-available-json/1548 .. pls let us know if you have issues when posting or with the forum in general! the new forum is .. quite new (we used google groups before) ..

**Comment by jcgertig** [comment]
The post is there but I cant reply to the answer

**Comment by meejah** [comment]
It said you were "silenced" because "new user typed too fast" ... not entirely sure what that means, but you should be able to use it now.

(@oberstet / @om26er are there some settings related to new users posting too much / too quickly? This was several hours between post and my reply and then @jcgertig 's attempt to reply ...)

**Comment by om26er** [comment]
@meejah there was a default setting, which I just disabled in the forum. New posts should be good now.
