### ISSUE TITLE
Message pack breaks RPC's without return

### ISSUE THREAD

**Issue by dionytadema** [crossbario/autobahn-python#1244]
using the messagepack serialization there is no way to have an rpc not return anything, see the example, this will throw an error `Potentially unhandled rejection [1] Error: undefined is not encodable in msgpack!`

Expected behavior would be to produce a RESULT without args and kwargs

```
var connection = new autobahn.Connection({
   url: 'ws://127.0.0.1:8080/ws',
   realm: 'crossbardemo',
   protocols: ['wamp.2.msgpack']
});
connection.onopen = function (session) {

   function ping() {}

   session.register('ping', ping).then(
      function (registration) {
         session.call('ping',[],{})
      }
   );
};
connection.open();
```

**Comment by discoli** [comment]
Hey, this is completely unrelated but @dionytadema are you the current owner of the account https://namemc.com/profile/Dionysus

(sorry for the unrelated post once again, but this is the only way that I was able to find to contact you with the other username on the account)

If it is would you be interested in selling the account at all, if so my details are as follows:
email - me@disco.ly
discord - discoli#4344
telegram - @discoli

Let me know, thanks!
