### ISSUE TITLE
Replace pep8 with pycodestyle

### ISSUE THREAD

**Issue by opoplawski** [crossbario/autobahn-python#1256]
pep8 has been deprecated and has been dropped from Fedora.  Please replace with pycodestyle.

**Comment by waterbug** [comment]
"Deprecated"?  No sign of its deprecation in the PEP index ... what evidence do you have?

**Comment by waterbug** [comment]
Apologies, I see you are talking about the "pep8" package, not PEP 8 -- sorry for the noise!

**Comment by oberstet** [comment]
sorry, won't fix - that is fedora distro follies ..
