### ISSUE TITLE
Check if packet arrived at subscriber

### ISSUE THREAD

**Issue by SanjayThomas** [crossbario/autobahn-python#1272]
Hello,

I seem to have encountered a rare case where a message I sent over a publish subscribe channel was not detected at a subscriber. Is this even possible? If yes, is there any way I can have the publisher detect this so that I can publish the message again?

Thank you

**Comment by meejah** [comment]
Yes for sure that's possible: a connection can end at any moment, and it's not possible for the sender to know which bytes have been received at the other end. So, it's not possible for the router (e.g. crossbar) to know if any given subscriber has actually received a publish, unless that message is acknowledged (in turn, that client can't know that the ack was received .. etc).
