### ISSUE TITLE
Code and docs cleanups for dropping python <3.5 support

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1282]
Moving forward, we would like to support python 3.5 as the minimal version and drop python 2. The issue here is for removing CI steps, cleaning up code (remove things that can be systematically cleaned up) and adjust the docs.

**Comment by om26er** [comment]
One step towards that is https://github.com/crossbario/autobahn-python/pull/1277 -- It removes Py2.7 CI, also removes most of the Py2.7 compat code and updates examples as well.

**Comment by oberstet** [comment]
@om26er yeah, saw that .. and cool: that is a nice start! @meejah opinions? I'd say, let's move (with dropping py 2 now);)

**Comment by meejah** [comment]
Maybe "one more" release where we can say in the release notes "this is the last release that will support python2"..? This gives anyone depending on python2 a thing to pin to, and also some warning (do we happen to know if there are any such users?)

I haven't actually looked at the diff yet..

**Comment by oberstet** [comment]
> Maybe "one more" release where ..

make sense, agreed: so I created an additional release milestone v20.1.1 which would be the last python 2 supporting release

**Comment by om26er** [comment]
> cleaning up code (remove things that can be systematically cleaned up)

I wonder if we also want to use async/await internally as compared to returnValue/yield. Or make that a candidate for future merge requests ?

**Comment by oberstet** [comment]
> I wonder if we also want to use async/await internally as compared to returnValue/yield. 

Yes, in general yes.

> Or make that a candidate for future merge requests?

Yeah, I would do that in follow ups over time ..

There is 1 thing that pops to my mind: using async/await syntax also in autobahn/twisted will use the _additional_ twisted machinery under the hood to make that work. in my experience, this works quite well and I haven't run into any issues. Then I didn't do systematic investigation .. and also not performance investigation.

**Comment by om26er** [comment]
@oberstet once you tag a new release with currently landed changes, we could do the release announcement and even update the pypi page (?) to mention about Python2 deprecation notice or something. The I will be doing further pull requests. One being the removal of all `from __future__ import ...` lines.

**Comment by meejah** [comment]
> There is 1 thing that pops to my mind: using async/await syntax also in autobahn/twisted will use the additional twisted machinery under the hood to make that work. in my experience, this works quite well and I haven't run into any issues. Then I didn't do systematic investigation .. and also not performance investigation.

I haven't done a deep investigation or performance-testing but the `ensureDeferred` stuff (which is what, ultimately, `async def` and `await` fall back on in Twisted) uses the very same internal machinery/functions as `@inlineCallbacks` -- so I wouldn't expect different performance than that.

I have been lead to believe `@inlineCallbacks` can be slightly slower than "straight deferreds". Still, I think the readability of async/await (or inlineCallbacks/yield) is preferable even with a slight performance hit? (And, bear in mind, I don't even know if there IS a perf hit)

**Comment by oberstet** [comment]
@meejah ok, I see: sounds good enough for me / fits my limited experience with that stuff too. so lets move to await/async syntax (later) ..

ok, I reviewed the big https://github.com/crossbario/autobahn-python/pull/1277 .. couldn't find anything wrong, so merged!

> one thing I recognized, which we might want to clean up also in a followup: `u'blabla' ` => `'blabla'`, and `u"blabla"` => `'blabla'`

**Comment by om26er** [comment]
> one thing I recognized, which we might want to clean up also in a followup: `u'blabla' ` => `'blabla'`, and `u"blabla"` => `'blabla'`

This PR https://github.com/crossbario/autobahn-python/pull/1286 addresses that. It also removes trollius fallback and some more...

**Comment by oberstet** [comment]
All PRs merged, CI here and in CB is green. Guess the code cleanup is already complete? awesome!!

So remaining is only examples? docs? Should we move those to a follow up issue and close this one or keep it open?

**Comment by om26er** [comment]
Lets close this and we can monitor further updates in different issues.
* Move to async/await
* Update docs (where do they live ?)
* Update examples (crossbar-examples ?)

**Comment by oberstet** [comment]
follow up issue is here https://github.com/crossbario/autobahn-python/issues/1289
