### ISSUE TITLE
Wrongly worded closing handshake timout warning

### ISSUE THREAD

**Issue by thomgree** [crossbario/autobahn-python#1310]
Here:
https://github.com/crossbario/autobahn-python/blob/0c38a7ea759f353e6d096fa553dab96910cb3d3b/autobahn/websocket/protocol.py#L832
We have
'WebSocket closing handshake timeout (peer did not finish the opening handshake in time)'

Surely this should read:
'WebSocket closing handshake timeout (peer did not finish the closing handshake in time)'

**Comment by oberstet** [comment]
uups, yes of course;) that's a typo.

**Comment by om26er** [comment]
https://github.com/crossbario/autobahn-python/pull/1311
