### ISSUE TITLE
Asyncio echo example not working properly

### ISSUE THREAD

**Issue by jersobh** [crossbario/autobahn-python#1341]
I'm getting this error :
```
WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
```
while running the asyncio example. Twisted example works, tough.

**Comment by meejah** [comment]
With python 3.6.9, it seems to work for me. That is, running both `client.py` and `server.py` from `examples/asyncio/websocket/echo` connects and shows responses. Can you provide more details?

**Comment by jersobh** [comment]
Sorry, I was using uvloop. Without it works fine. Actually, it works with it, but it's needed to set a policy.
