### ISSUE TITLE
Add support for adding callback to add_event_handler in asyncio

### ISSUE THREAD

**Issue by uttaravadina** [crossbario/autobahn-python#1386]
I am currently using asyncio for event loop as it supports *add_event_handler* for handling **UNIX Signals**

I have a use-case where I want to call 2 or more software and hardware APIs, when the running process receives SIGINT and SIGTERM before the process can finally exit. 
I noticed that part is already implemented and that is how the app closes cleanly every time.
[asyncio - add_signal_handler](https://github.com/crossbario/autobahn-python/blob/011453fc7aa7e22f7ed558391ba6a0597b864578/autobahn/asyncio/component.py#L383)

I think we can provide support to pass extra callbacks via the [run](https://github.com/crossbario/autobahn-python/blob/011453fc7aa7e22f7ed558391ba6a0597b864578/autobahn/asyncio/component.py#L315) and then pass it at [nicely_exit](https://github.com/crossbario/autobahn-python/blob/011453fc7aa7e22f7ed558391ba6a0597b864578/autobahn/asyncio/component.py#L360)

@meejah @om26er @oberstet If there is feasibility of adding this into the library then is there any other way the process can listen for UNIX Signals and run a callback?

**Comment by u774r4v4d1n** [comment]
FYI, I did try adding **signal.signal(event, callback)** before calling **run([comp])** but it doesn't act on it. I realised it's possible probably if called within the **nicely_exit**

**Comment by meejah** [comment]
Did calling `add_signal_hander` before calling `run()` not work? `signal.signal` is probably too "low level", by-passing asyncio's own stuff.

In Twisted, there is an API to call your own hooks/functions when the reactor is shutting down .. see https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IReactorCore.html#addSystemEventTrigger

**Comment by u774r4v4d1n** [comment]
This is news to me. So, let me try addSystemEventTrigger and get back.

So, initially I used Component from autobahn.twisted.component first, before moving onto asyncio, and directly used `signal.signal` a couple of statements before calling `run([component])` and it didn't work. My best estimate was that the event loop is picking up and executing the callback tied up to that event and doesn't give a chance for the signal.signal callback to be executed.

**Comment by oberstet** [comment]
> If there is feasibility of adding this into the library then is there any other way the process can listen for UNIX Signals and run a callback?

just some quick notes:

* Integration with posix signals is sth for the networking framework to provide, not Autobahn
* for Twisted, this integration is available as meejah noted
* I don't know whether there is similar stuff for asyncio and wether that is working robustly in practice (I am mostly using Twisted, and signals work there .. eg Crossbar.io is using it)

**Comment by oberstet** [comment]
one more note rgd background: the root of these annoyances is - at least historically - lack of integration of signals and file descriptors in posix. eg in epoll in linux.

in the BSDs, eg FreeBSD kqueue has a cleaner design (again, historically at least). so signals can be waited upon just as everything else via a FD added to kqueue ..

anyways: signals are tricky to integrate within the networking framework. as is real async disk IO. blame Posix;)

**Comment by u774r4v4d1n** [comment]
There is something similar for asyncio actually just like meejah pointed out for twisted and autobahn-python is already using that for asyncio [here](https://github.com/crossbario/autobahn-python/blob/011453fc7aa7e22f7ed558391ba6a0597b864578/autobahn/asyncio/component.py#L383)

Thanks for pointing that out @oberstet.
How would you recommend handling the signals when using autobahn-python using Twisted on Client-side (in Linux at least)?
The idea is to perform some minor operations just before the process is about to terminate.

**Comment by u774r4v4d1n** [comment]
For example: When running Client-side apps using Autobahn-python on hardware like RPi, a change in the colour of LED or turning it on/off just before the process is about to terminate.

**Comment by oberstet** [comment]
@uttaravadina I would go with the machinery built into Twisted, that is what meejah noted [here](https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IReactorCore.html#addSystemEventTrigger)

you can find example usage within crossbar eg here

https://github.com/crossbario/crossbar/blob/7a24af99fce6d057c63a9c7b144b0418ca627f4e/crossbar/node/main.py#L873

that will cover cases such as SIGINT

you cannot (to my knowledge) process SIGKILL within the killed program itself.

if you need to cover that as well, I'd start a monitoring main process and spawn your actual program using https://twistedmatrix.com/documents/current/core/howto/process.html, communicate (eg for logging) with your main monitor from the forked app via std pipes. you will then be able to process SIGKILL to the forked app within the monitor (as it receives the exit code from the forked app)

https://github.com/crossbario/crossbar/blob/master/crossbar/node/main.py#L616

if you need to process a power interrupt where all processes die simult., you need some persistency .. eg crossbar writes a "PID file" and will note when it restarts that it had been hard killed.

**Comment by uttaravadina** [comment]
I will try this and get back to you.

**Comment by meejah** [comment]
If you want to do stuff when the process is shutting down, absolutely use Twisted's APIs -- these will run no matter how the process is shutting down (except probably via SIGKILL which applications can't handle, no matter the language/framework).

"In general", these frameworks (Twisted, etc) are built to deal with weird low-level stuff -- which signals *definitely* qualify as -- so using their APIs are usually the best approach. As a bonus, they also will typically work on all supported platforms (so you don't have to figure out how OS X handles signals versus Linux versus windows etc etc).
