### ISSUE TITLE
Bytes and string both get encoded as strings

### ISSUE THREAD

**Issue by Lois31** [crossbario/autobahn-python#1388]
Hello community,

I have a problem when sending a byte array with the use of the msgpack serializer.
When receiving the data, it is unpack as a string.

When using the json serializer, the data is correctly encoded, as referenced in this [document](https://wamp-proto.org/_static/gen/wamp_latest.html#binary-conversion-of-json-strings), and decoded as bytes.

I also made Wireshark captures which show that the following byte array `b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x10'`, is encoded as follows `["\u0000b'AQIDBAUGBwgJEA==' "]`, when using the json serializer. This encoding corresponds well to that described in the standard cited in the previous document.
With the msgpack serializer, the byte array is not encoded correctly and send derecly as follow `0a 01 02 03 04 05 06 07 08 09 10`

here is my current configuration:

- Python3.8
- autobahn 20.4.3
- msgpack 1.0.0

Below an example allowing to highlight the problem:

**Backend.py**
```
import asyncio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component, run

class Backend(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)


    async def onJoin(self, details):
        print('Register test_echo_payload')
        await self.register(self.test_echo_payload, 'test.echo.payload')

    async def onDisconnect(self):
        loop  = asyncio.get_event_loop()
        loop.stop()


    async def test_echo_payload(self, value: bytes) -> bytes:
        if not isinstance(value, bytes):
            print('Value is not an instance of bytes but is a %s' % (type(value)))
        return value


if __name__ == '__main__':
    backend = Component(
            session_factory = Backend,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8902/ws',
                    'max_retries': 3
                }
            ]
        )

    run([backend])
```

**Client.py**
```
import asyncio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component, run


class Client(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)


    async def onJoin(self, details):
        print('Call test_echo_payload')
        loop = asyncio.get_running_loop()
        loop.create_task(self.test_echo_payload())

    async def onDisconnect(self):
        loop  = asyncio.get_event_loop()
        loop.stop()

    async def test_echo_payload(self):
        message_bytes = b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x10'
        ret = await self.call('test.echo.payload', message_bytes)


if __name__ == '__main__':
    client = Component(
            session_factory = Client,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8902/ws',
                    'max_retries': 3
                }
            ]
        )

    run([client])
```

**Comment by Lois31** [comment]
In addition, I did the same test via the autobahn C ++ library. 
I get two different wiresharc traces:

**Python3**:
```
95 30 02 80 b1 74 65 73		74 2e 65 63 68 6f 2e 70		.0...tes	t.echo.p
61 79 6c 6f 61 64 91 c4		0a 01 02 03 04 05 06 07		ayload..	........
08 09 10
```
**C++**:
```
95 30 01 80 b1 74 65 73 	74 2e 65 63 68 6f 2e 70		.0...tes	t.echo.p
61 79 6c 6f 61 64 91 c4 	0b 00 01 02 03 04 05 06		ayload..	........
07 08 09 10												....
```

Byte array encoding, the first character is different between Python and C ++:
Python: `0a 01 xx` => `0b 00 01 xx` C++

**Comment by oberstet** [comment]
seems like you are doing a full client->router->client test? if so, what router exactly? since the router deserializes and then re-serializes, so it's important to know what's going on there.

that being said:

we already have had extensive serializer tests in AutobahnPython, which I further expanded: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/test/test_serializer.py

these tests include "cross-trip testing" for _every combination_ of supported serializers: serialize using SER-A, and deserialize using SER-B, and compare values.

and the values include binaries and unicode

using these tests, I cannot reproduce this and everything works as expected on py 3.8:

```
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python -V
Python 3.8.2
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ make test_tx_serializer 
USE_TWISTED=1 trial autobahn.wamp.test.test_serializer
autobahn.wamp.test.test_serializer
  TestFlatBuffersSerializer
    test_basic ...                                                         [OK]
  TestSerializer
    test_auto_stats ...                                                    [OK]
    test_cache_msg ...                                                     [OK]
    test_crosstrip_msg ...                                                 [OK]
    test_deep_equal_msg ...                                                [OK]
    test_initial_stats ...                                                 [OK]
    test_reset_stats ...                                                   [OK]
    test_roundtrip_msg ...                                                 [OK]
    test_serialize_stats ...                                               [OK]
    test_serialize_stats_with_details ...                                  [OK]

-------------------------------------------------------------------------------
Ran 10 tests in 0.563s

PASSED (successes=10)
``` 

here is CI:

* https://travis-ci.com/github/crossbario/autobahn-python/jobs/340600063#L904
* https://travis-ci.com/github/crossbario/autobahn-python/builds/168433839

**Comment by oberstet** [comment]
rgd router, eg when using crossbar, checkout this:

```
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ which python
/home/oberstet/cpy382_1/bin/python
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ python -V
Python 3.8.2
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ crossbar version


    :::::::::::::::::
          :::::          _____                      __
    :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
    :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
    :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
          :::::
    :::::::::::::::::   Crossbar v20.5.1.dev1

    Copyright (c) 2013-2020 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.

 Crossbar.io        : 20.5.1.dev1
   txaio            : 20.4.1
   Autobahn         : 20.5.1.dev1
     UTF8 Validator : wsaccel-0.6.2
     XOR Masker     : wsaccel-0.6.2
     JSON Codec     : stdlib
     MsgPack Codec  : msgpack-1.0.0
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.16.1
     FlatBuffers    : flatbuffers-1.12
   Twisted          : 20.3.0-EPollReactor
   LMDB             : 0.98/lmdb-0.9.22
   Python           : 3.8.2/CPython
 Frozen executable  : no
 Operating system   : Linux-4.15.0-101-generic-x86_64-with-glibc2.2.5
 Host machine       : x86_64
 Release key        : RWRCwbVSHPPyh5AMf5965n+tP1EJ18aOuO4yIAK4EiZkQsAGdWYh3Paw

``` 

and

``` 
(pypy36_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ which python
/home/oberstet/pypy36_1/bin/python
(pypy36_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ python -V
Python 3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:04)
[PyPy 7.3.0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
(pypy36_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar$ crossbar version


    :::::::::::::::::
          :::::          _____                      __
    :::::   :   :::::   / ___/____ ___   ___  ___  / /  ___ _ ____
    :::::::   :::::::  / /__ / __// _ \ (_-< (_-< / _ \/ _ `// __/
    :::::   :   :::::  \___//_/   \___//___//___//_.__/\_,_//_/
          :::::
    :::::::::::::::::   Crossbar v20.5.1.dev1

    Copyright (c) 2013-2020 Crossbar.io Technologies GmbH, licensed under AGPL 3.0.

 Crossbar.io        : 20.5.1.dev1
   txaio            : 20.4.1
   Autobahn         : 20.5.1.dev1
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : stdlib
     MsgPack Codec  : umsgpack-2.5.2
     CBOR Codec     : cbor-1.0.0
     UBJSON Codec   : ubjson-0.14.0
     FlatBuffers    : flatbuffers-1.11
   Twisted          : 20.3.0-EPollReactor
   LMDB             : 0.98/lmdb-0.9.22
   Python           : 3.6.9/PyPy-7.3.0
 Frozen executable  : no
 Operating system   : Linux-4.15.0-101-generic-x86_64-with-debian-buster-sid
 Host machine       : x86_64
 Release key        : RWRCwbVSHPPyh5AMf5965n+tP1EJ18aOuO4yIAK4EiZkQsAGdWYh3Paw

```

---

so on CPython, crossbar is using `msgpack-1.0.0` which is native code (CPyExt based), whereas on PyPy we are using `umsgpack-2.5.2`, a pure Python code implementation (which is faster than the C-based native extension on PyPy).

those details all matter ..

**Comment by oberstet** [comment]
so I've been thinking a bit about what kind of tests would be required at the integration level, which I think would be require to address this:

first, we cannot get away with tests comparing to known-good serialized octets.

the reason is that none of the serializers we support have this property:

> For each possible (complex) value, there is only a single valid bencoding; i.e. there is a bijection between values and their encodings. This has the advantage that applications may compare bencoded values by comparing their encoded forms, eliminating the need to decode the values.

Bencode is the only serialization format I know of that has this property

so we need to do full integration testing, including 2 clients plus router:

* Client 1 based on AutobahnX1 using serializer Y1 connected to Crossbar.io
* Client 2 based on AutobahnX2 using serializer Y2 connected to Crossbar.io

and then test every combination of X1, Y1, X2 and Y2

my expectation would be to find real bugs in serializer libraries doing that

this is quite challenging as we have Autobahn-Python, -JS, -C++ and -Java and support JSON, MessagePack, CBOR, UBJSON and Flatbuffers (upcoming).

that means: 4x5 = 20 combinations. not even counting "batched" serialization (`wamp.2.json` vs `wamp.2.json.batched`). and funnel all kind of values and WAMP message types through all those combinations.

but would totally make sense (be useful). we don't have that currently :(

**Comment by oberstet** [comment]
> Byte array encoding, the first character is different between Python and C ++:
Python: 0a 01 xx => 0b 00 01 xx C++

it might be a real issue in this case - or not. because MessagePack doesn't have the bijection property above.

so only from looking at octets and detecting a difference, that doesn't necessarily mean the actual values are different ..

in your example, both instances seem to be a msgpack "fixstr" (a fixed length byte array of up to 31 bytes) https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family

---

anyways, maybe we find out what's going on in a simpler way:

```python
import binascii
import txaio
txaio.use_twisted()

from autobahn.wamp import message
from autobahn.wamp import serializer

ser = serializer.MsgPackSerializer()
msg = message.Call(123456, 'test.echo.payload', args=[b'\x01\x02\x03\x04\x05\x06\x07\x08\x09\x10'])
payload, _ = ser.serialize(msg)

print('0x{}'.format(binascii.b2a_hex(payload).decode()))
```

CPython 3.8 (`msgpack-1.0.0`):

```console
(cpy382_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python test.py 
0x9530ce0001e24080b1746573742e6563686f2e7061796c6f616491c40a01020304050607080910
```

PyPy 7.3.0 (`umsgpack-2.5.2`) 

```console
(pypy36_1) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python test.py 
0x9530ce0001e24080b1746573742e6563686f2e7061796c6f616491c40a01020304050607080910
```

that is: both result in identical octets `0a01020304050607080910` - and this is correct.

so the messagepack serializer in AutobahnC++ seems to be wrong.

**Comment by Lois31** [comment]
Thank you Tobias for your analysis and your reactivity!

In order to complete the COTS used, I tested with the V20.4.2 Crossbar WAMP router.
Below, its configuration:
```
{
  "$schema": "https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json",
  "version": 2,
  "controller": {
  },
  "workers": [
    {
      "type": "router",
      "realms": [
        {
          "name": "TESTS",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": false,
                    "publisher": false
                  },
                  "cache": true
                }
              ]
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8902,
            "backlog": 1024
          },
          "paths": {
            "/": {
              "type": "static",
              "directory": "../web",
              "options": {
                "enable_directory_listing": true
              }
            },
            "ws": {
              "type": "websocket",
              "serializers": [
                "msgpack"
              ],
              "options": {
                "allowed_origins": ["*"],
                "allow_null_origin": true,
                "enable_webstatus": false,
                "max_frame_size": 1048576,
                "max_message_size": 1048576,
                "auto_fragment_size": 65536,
                "fail_by_drop": true,
                "open_handshake_timeout": 2500,
                "close_handshake_timeout": 1000,
                "auto_ping_interval": 10000,
                "auto_ping_timeout": 5000,
                "auto_ping_size": 4,
                "compression": {
                  "deflate": {
                    "request_no_context_takeover": false,
                    "request_max_window_bits": 13,
                    "no_context_takeover": false,
                    "max_window_bits": 13,
                    "memory_level": 5
                  }
                }
              }
            },
            "info": {
              "type": "nodeinfo"
            }
          }
        }
      ]
    }
  ]
}
```

Let's get rid of C++ and go back to my original problem.
The problem being that when we send a message of type "bytes" while serializing with **msgpack**, we receive a message of type "str" ...

I just did some additional tests which make me think that the problem comes from the router, I explain.
Here are the steps of my test:

1. Start the Crossbar router on Linux1 machine
2. Star the Backend component on Linux2 machine
3. Start the Client component on Linux1 machine

The _Client_ component correctly sends the byte table type message encoded in msgpack as follows:
`0x9530ce0001e24080b1746573742e6563686f2e7061796c6f616491c40a01020304050607080910`
But on the _Backend_ component, we receive the message of the following form:
```
0000   18 60 24 80 ee d2 48 0f cf 35 d8 ac 08 00 45 00   .`$...H..5....E.
0010   00 76 8a 82 40 00 40 06 8c 66 2c 21 66 b9 2c 21   .v..@.@..f,!f.,!
0020   64 9e 22 c6 c0 e8 76 98 54 58 13 f5 16 52 80 18   d."...v.TX...R..
0030   00 85 b0 f0 00 00 01 01 08 0a 10 8f 32 63 7a ec   ............2cz.
0040   34 1c 82 40 95 44 19 12 81 a9 70 72 6f 63 65 64   4..@.D....proced
0050   75 72 65 b1 74 65 73 74 2e 65 63 68 6f 2e 70 61   ure.test.echo.pa
0060   79 6c 6f 61 64 91 bd 5b 22 5c 75 30 30 30 30 62   yload..["\u0000b
0070   27 41 51 49 44 42 41 55 47 42 77 67 4a 45 41 3d   'AQIDBAUGBwgJEA=
0080   3d 27 22 5d                                       ='"]
```

It seems that the Crossbar router returns the message in Json format and not Msgpack...

**Comment by Lois31** [comment]
Hello Tobias,

In the end everything works very well ... I had to mix in my many tests ... (Python, C++, Json, MsgPack, ...)

Thank you again for your help.
You can close this ticket.
