### ISSUE TITLE
How to manually manage session lifetime in asyncio?

### ISSUE THREAD

**Issue by neara** [crossbario/autobahn-python#1399]
I am writing an asyncio application that needs to talk to another component via rpc. I already have crossbar router in place and component exposing methods that can be called.
However, I can't seem to figure out or find an example of how can I create a session to crossbar router and at some point call those methods (not as part of a blocking `loop.run_forever` in `component.run`). 
How to manually manage the session? Connect, call, leave, etc.

Thanks 🙏

**Comment by rdebroiz** [comment]
If your question is how to start a component using an already running loop, you can do something event based like: 
```python
# I supposed your component is already created.
comp = Component(...)

ready = asyncio.Event()
disconnected = asyncio.Event()
# not "disconnected" yet.
disconnected.set()

async def on_joined(*args, **kwargs):
    disconnected.clear()

async def on_ready(*args, **kwargs):
    ready.set()

async def on_disconnected(self, *args, **kwargs):
    disconnected.set()

# or use decorator on on_joined, on_ready and on_disconnected
comp.on("joined", on_joined)
comp.on("ready", on_ready)
comp.on("disconnect", on_disconnected)

# start the component using an already running loop
txaio.config.loop = loop
comp.start(loop=loop)

# wait for readyness
await ready.wait()

# do what you need

# stop the component
try:
   comp.stop()
except AttributeError:  # "bug" in txaio.aio.is_called  (not sure if it's still there, also it might be only for python 3.8)
   pass
# wait for it to be fully disconnected from the router.
await disconnected.wait()
```

Maybe there is a simpler way of doing it, this one works well.

**Comment by neara** [comment]
@rdebroiz that was exactly what i was looking for. Thank you 🙏 

I also asked the question on crossbar forum and got an answer: https://forum.crossbar.io/t/how-can-i-open-a-connection-to-crossbar-and-publish-without-using-run-loop/1782/6

For me, the missing part was to understand the use of `future` (`Event` in your example) to await the end of `join` event.
