### ISSUE TITLE
add PyPI Stats badge

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1401]
https://pypistats.org/packages/autobahn

```
[![Downloads](https://img.shields.io/badge/dynamic/json.svg?label=downloads&url=https%3A%2F%2Fpypistats.org%2Fapi%2Fpackages%2Fpython-hcl2%2Frecent&query=data.last_month&colorB=brightgreen&suffix=%2FMonth)](https://pypistats.org/packages/python-hcl2)
``` 

https://github.com/amplify-education/python-hcl2/blob/master/README.md

**Comment by thomasgoirand** [comment]
Hi,

Please don't add "badges". They are annoying for downstream distributions, and we got to remove them one by one (because it otherwise is very annoying to browse a local disk HTML and have internet queries for badges).

**Comment by oberstet** [comment]
Him our project motivation is to "make it useful" for users, that is app developers. As an app developer, I want to see if the projects' CI succeeds and such. I might also be interested in how broad the library is generally used in the community. We already have a badge for the former, and the issue here is only to expand on that in adding another badge for download stats. If that collides with some distros' policies, that is unfortunate, but we cannot support the common denominator over all distros. I would guess this denominator doesn't exist, and as said, also not a focus for us. People should `pip install autobahn` into an app specific Python venv is what we recommend.

**Comment by oberstet** [comment]
Having said that, I would definitely prefer to link the badges to PyPI, if that would provide such. The current external links in the `README.rst` (which also is rendered as the docs main page) are

```

.. |Version| image:: https://img.shields.io/pypi/v/autobahn.svg
   :target: https://pypi.python.org/pypi/autobahn

.. |Master Branch| image:: https://img.shields.io/badge/branch-master-orange.svg
   :target: https://travis-ci.com/crossbario/autobahn-python.svg?branch=master

.. |Build Status| image:: https://travis-ci.com/crossbario/autobahn-python.svg?branch=master
   :target: https://travis-ci.com/crossbario/autobahn-python

.. |Coverage| image:: https://img.shields.io/codecov/c/github/crossbario/autobahn-python/master.svg
   :target: https://codecov.io/github/crossbario/autobahn-python

.. |Docs| image:: https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat
   :target: https://autobahn.readthedocs.io/en/latest/

.. |Docker| image:: https://img.shields.io/badge/docker-ready-blue.svg?style=flat
   :target: https://hub.docker.com/r/crossbario/autobahn-python/
```

**Comment by oberstet** [comment]
what we could certainly do is get rid of `https://img.shields.io` .. not `https://travis-ci.com`

**Comment by oberstet** [comment]
so the only feedback was "negative" (see above), and no one cares/works on this. closing
