### ISSUE TITLE
Publish a library+tool snap

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#1415]
* We should publish it as a snap. I have reserved the name `wamp`
* We should aim to have it available on pypi, independent of `autobahn-python` (needs discussion)
* Long stretch: we should also have builds for Mac/Windows as well.

Reasons: Our CLI tool should be the entry point for anyone coming to WAMP/Crossbar/Autobahn, think of it as `curl` or `httpie` but for WAMP proto. Ideas welcome.

**Comment by oberstet** [comment]
IMO, if we publish another snap, that snap should be `autobahn`, and this bundles the CLI. is there an autobahn snap?

**Comment by oberstet** [comment]
so there is no autobahn snap package: https://snapcraft.io/search?q=autobahn

> We should publish it as a snap. I have reserved the name wamp

my view: no, we should not publish a separate snap, but an autobahn snap (including the library and any tools the library bundles)

> We should aim to have it available on pypi, independent of autobahn-python (

my view: no, why separate?

> Long stretch: we should also have builds for Mac/Windows as well.

my view: what do you mean with "builds"? a binary package for windows or mac?

**Comment by om26er** [comment]
We reverted the change, more details in the PR.
