### ISSUE TITLE
Running multiple websocket clients in multiple threads

### ISSUE THREAD

**Issue by schmidtfx** [crossbario/autobahn-python#1416]
Hi, 

is there a way to run multiple websocket clients on a thread pool?
Is there an example?

Thanks

**Comment by oberstet** [comment]
It is possible to run client connections app code in background threads, but all client network connections must be opened from the main thread. The ultimate reason is that the Twisted reactor or asyncio event loop always run (only) on the main thread.

So it will depend on your goals:

* blocking network and IO (syscalls): built into the async paradigm (threads not needed)
* scaling network and IO (syscalls) with threads: not possible (you must use multi-process architecture)
* scaling userland / app with threads: easy to do .. eg in WAMP https://github.com/crossbario/crossbar-examples/blob/1045aeda312c2a820859206a149392eb6c7f6e3f/scaling-microservices/queued/compute.py#L65

pure websocket will work similar
