### ISSUE TITLE
Client sends reserved bit without negotiating it

### ISSUE THREAD

**Issue by Haegi** [crossbario/autobahn-python#1417]
When I try to use the autobahn-python client. I occasionally face the issue that my WebSocket server receives a frame with at least one reserved bit set and a not RFC defined opcode (e.g. 4, 12 etc.). This happens only occasionally when I execute the same code over and over again. Shouldn't it be idempotent or at least negotiate an extension?

According to [this section](https://tools.ietf.org/html/rfc6455#section-5.2) in RFC6455, there needs the be a negotiation for the extension and if there is no negotiation the connection MUST fail. Unfortunately, there is no extension negotiation (no `Sec-WebSocket-Extensions` header field) as described in the [Negotiating Extensions](https://tools.ietf.org/html/rfc6455#section-9.1) section in RFC6455, the only header fields received are the "normal" once.

Received header fields (even with RSV set and other opcodes):
```
'GET / HTTP/1.1',
'User-Agent: AutobahnPython/20.7.1',
'Host: localhost:80',
'Upgrade: WebSocket',
'Connection: Upgrade',
'Pragma: no-cache',
'Cache-Control: no-cache',
'Sec-WebSocket-Key: [...]',
'Sec-WebSocket-Version: 13',
'',
''
```

Client code:
```python
class MyClientProtocol(WebSocketClientProtocol):

   def onOpen(self):
      payload = b"*" * 65535
      self.sendFrame(opcode = 1, payload = payload)
```

**Comment by oberstet** [comment]
cannot reproduce- autobahn.python websocket is tested exhaustively using https://github.com/crossbario/autobahn-testsuite/
