### ISSUE TITLE
Example of setting up mutual TLS?

### ISSUE THREAD

**Issue by danielwangksu** [crossbario/autobahn-python#1428]
Is there example of how to use autobahn setup mutual TLS? Thank you!

**Comment by oberstet** [comment]
here is an example of a WAMP client being authenticated via TLS client certificates using AutobahnPython and Crossbar.io

**Comment by danielwangksu** [comment]
> here is an example of a WAMP client being authenticated via TLS client certificates using AutobahnPython and Crossbar.io
> 
> https://github.com/crossbario/crossbar-examples/tree/master/authentication/tls/static

Thank you @oberstet but it is not clear to me if mutual authentication is enabled. e.g., the client verify the server's certificate but the the server also verify client's certificate.

**Comment by oberstet** [comment]
https://crossbar.io/docs/TLS-Client-Certificate-Authentication/
