### ISSUE TITLE
One little question

### ISSUE THREAD

**Issue by jorgebg2016** [crossbario/autobahn-python#1442]
How can I create a websocket protocol matrix where I can send datas from server to all clients alloweds? Is there some example?

**Comment by oberstet** [comment]
websocket does not have a "websocket protocol matrix". it is a raw point-to-point (link) protocol. WAMP, whjich builds on WebSocket, provides what you might call a "matrix" - this feature is called Publish & Subscribe: pls see here https://wamp-proto.org/routing.html
