### ISSUE TITLE
Failing WebSocket opening handshake ('WebSocket connection upgrade failed (400 - BadRequest)')

### ISSUE THREAD

**Issue by nmmapper** [crossbario/autobahn-python#1452]
I have used autobahn-python to write real enterprise websocket servers. But I have never tried to use it to write websocket clients until now. But when I try to connect to a remote server I get the following error on logs.

```
DEBUG 2021-02-05 05:58:44,497 client 5736 Transport details: {"peer": "tcp4:172.67.209.146:443", "is_secure": false, "secure_channel_id": {}}
INFO 2021-02-05 05:58:44,710 aio 5736 failing WebSocket opening handshake ('WebSocket connection upgrade failed (400 - BadRequest)')
WARNING 2021-02-05 05:58:44,711 aio 5736 dropping connection to peer tcp4:172.67.209.146:443 with abort=True: WebSocket connection upgrade failed (400 - BadRequest)
WARNING 2021-02-05 05:58:44,711 client 5736 Server closed connection wasClean=False code=1006 reason=connection was closed uncleanly (WebSocket connection upgrade failed (400 - BadRequest))
```
Here is the entire configurations. The server am connecting to runs behind cloudflare. When I monitor the server logs the connection is not even hitting the nginx proxy and yet if I use another python websocket library it works like a charm, but autobahn-python client fails.

```
self.factory = WebSocketClientFactory("wss://www.nmmapper.com/ws/service/02125740424e0560fe676c11eb92830050563f9853/197.157.0.35/")
        self.factory.protocol = self.PROTOCOL
if __name__=="__main__":
    factory = BlueAgentClientFactory("www.nmmapper.com", 443)
    factory.run_loop()
```

What truely Am i doing wrong?

**Comment by oberstet** [comment]
no idea what you are doing wrong. autobahn works as both a websocket server and client
https://github.com/crossbario/autobahn-python/tree/master/examples
https://github.com/crossbario/autobahn-testsuite
