### ISSUE TITLE
Issue with Python 3.9

### ISSUE THREAD

**Issue by misterflop** [crossbario/autobahn-python#1483]
Python version: 3.9.4 (default, Apr  9 2021, 01:03:21)
Autobahn package: 21.3.1

When I'm trying to connect to websocket:

2021-04-26 07:46:06+0000 [-] onConnecting failed: [Failure instance: Traceback: <class 'TypeError'>: Object of type bytes is not JSON serializable
	/usr/local/lib/python3.9/dist-packages/autobahn/twisted/websocket.py:250:connectionMade
	/usr/local/lib/python3.9/dist-packages/autobahn/websocket/protocol.py:3405:_connectionMade
	/usr/local/lib/python3.9/dist-packages/autobahn/websocket/protocol.py:3527:startHandshake
	/usr/local/lib/python3.9/dist-packages/txaio/tx.py:366:as_future
	--- <exception caught here> ---
	/usr/local/lib/python3.9/dist-packages/twisted/internet/defer.py:167:maybeDeferred
	/home/docker/binance_client/BinanceWSClient.py:26:onConnecting
	/usr/local/lib/python3.9/dist-packages/autobahn/websocket/types.py:230:__str__
	/usr/lib/python3.9/json/__init__.py:231:dumps
	/usr/lib/python3.9/json/encoder.py:199:encode
	/usr/lib/python3.9/json/encoder.py:257:iterencode
	/usr/lib/python3.9/json/encoder.py:179:default
	]

TransportDetails object content:

{'peer': 'tcp4:<valid ip address hidden for this issue>:9443', 'is_secure': True, 'secure_channel_id': {'tls-unique': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}}

My fix (no idea if it's the right thing todo):

In dist-packages/autobahn/websocket/types.py in TransportDetails(object):
I changed the self.secure_channel_id encoding:

    def __json__(self):
        secure_channel_id = dict(self.secure_channel_id)
        if isinstance(secure_channel_id.get("tls-unique"), bytes):
            secure_channel_id["tls-unique"] = secure_channel_id["tls-unique"].decode('utf-8')
        return {
            'peer': self.peer,
            'is_secure': self.is_secure,
            'secure_channel_id': secure_channel_id,
        }

**Comment by oberstet** [comment]
fixed in https://github.com/crossbario/autobahn-python/pull/1543
