### ISSUE TITLE
print TransportDetails throws json error (autobahn/websocket/types.py)

### ISSUE THREAD

**Issue by JarbasAl** [crossbario/autobahn-python#1486]
i am migrating a repo from twisted to asyncio, i am having some trouble with ssl connections on the client side, while debugging i tried to print the `transport_details` in ` def onConnecting(self, transport_details):`, this throws a json decoding error

```
  File "(....)/.venv/lib/python3.8/site-packages/autobahn/websocket/types.py", line 230, in __str__
    return json.dumps(self.__json__())
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

this is because of the secure_channel_id key which is a bytes object causing `json.dumps` to fail in `def __str__(self)` 

EDIT: this happens in more places, eg, i am using some authentication headers that caused the same issue when printing `ConnectingRequest` object

(as for my actual issue i am still bug hunting and thats unrelated to this bug report)

**Comment by oberstet** [comment]
fixed in https://github.com/crossbario/autobahn-python/pull/1543
