### ISSUE TITLE
How to create a proxy websocket server using autobahn?

### ISSUE THREAD

**Issue by vaibhav-falconx** [crossbario/autobahn-python#1487]
I am trying to setup a websocket proxy using the autobahn library. Essentially, everytime a client connects to my websocket server I would like to spin off a new connection to a destination websocket and then forward traffic between the two end points. A couple of things I am struggling with are:

1. How do I start a sub-task and attach it to the loop that will receive messages from the destination and return it to the client?
2. If not using asyncio, and instead using twisted how do I ensure that I can send a message from the server object to it's corresponding client object.

The documentation is not very clear on how I can handle these two scenarios.

**Comment by oberstet** [comment]
cleaning up issues, but fwiw, there are forwarding/proxy like examples (using twisted) here https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/websocket
