### ISSUE TITLE
autobahn/twisted.util.py won't compile

### ISSUE THREAD

**Issue by Believe20** [crossbario/autobahn-python#1491]
Hello, I am new to this, so please be patient with me.

I am having troubles installing the package correctly so I just downloaded the zip and then copy the autobahn folder to the directory I'm working in.

When I run my code, it uses another library that imports `sleep` from `autobahn.twisted.util` and I end up with this error:

`def transport_channel_id(transport: object, is_server: bool, channel_id_type: Optional[str] = None) -> bytes:`
`_____________________________________________________________________________________________________________________^`
`SyntaxError: invalid syntax`

Not sure if the error is on my side or not. Any help is appreciated!

**Comment by oberstet** [comment]
Hi! this could be related to your Python version: could you pls post the output of `python -V`?

**Comment by Believe20** [comment]
This error occurred using Python 2.7.16

In the meantime, I have tried compiling with 3.7.3, 3.7.9, and 3.9.5.

3.7 gives me the error:
`No module named 'txaio'`

3.9 gives me the error:
`No module named 'twisted'`

**Comment by meejah** [comment]
Just copying the `.zip` file won't install all the dependencies. It's best to install it like other python libraries (e.g. via `pip install` or similar). Can you describe what problems you had installing Autobahn?

**Comment by Believe20** [comment]
I just tried it again and was able to install it using pip. I don't remember the error code I got before. I think updating python could have helped.

**Comment by Believe20** [comment]
Also, I installed txaio and I got my program to run correctly. I still am confused why 2.7 and 3.9 don't work though.

**Comment by oberstet** [comment]
glad to hear you got it working! yes, meejah is right: you should just use pip to install (even from source, eg `pip install .`). the library works on python 3.7 or higher (https://github.com/crossbario/autobahn-python/blob/a370f9e7154e59b313cb675bfcaf8cad6011bd52/setup.py#L306). it is not (anymore) supported on python 2 (there is an old version of the library that works on py2)

**Comment by Believe20** [comment]
@oberstet @meejah Thank you so much for your help!
