### ISSUE TITLE
Please help to improve cpython performance in xormask

### ISSUE THREAD

**Issue by rwayan** [crossbario/autobahn-python#1494]
Sorry for my poor english

![image](https://user-images.githubusercontent.com/11252482/125579757-af580ff9-2b6a-44c0-b5f9-7fdd8a65b84c.png)
https://github.com/aaugustin/websockets/issues/466#issuecomment-423814482

would you please patch this for cpython users ?
```
    from websockets.speedups import apply_mask
    class XorMaskerShifted1(object):

        __slots__ = ('_ptr', '_mskarray','_mask')

        def __init__(self, mask):
            assert len(mask) == 4
            self._mask = mask

        def process(self, data):
            return apply_mask(data,self._mask)
```

**Comment by oberstet** [comment]
no, won't merge;
* I guess it's native code and only in "websockets"
* I care more about PyPy
* we use wsaccel on cpy, but the actual solution would be to finish work on https://github.com/crossbario/autobahn-python/tree/master/autobahn/nvx
