### ISSUE TITLE
twisted __version__ error

### ISSUE THREAD

**Issue by howard-statestitle** [crossbario/autobahn-python#1522]
I'm on autobahn version 22.1.1, and I'm running into a dunder version error with twisted:

```
  File ...
    import daphne.server
  File ...
    from .ws_protocol import WebSocketFactory
  File ...
    from autobahn.twisted.websocket import (
  File ...
    __ident__ = 'Autobahn/{}-Twisted/{}-{}/{}'.format(autobahn.__version__, twisted.__version__, platform.python_implementation(), platform.python_version())
AttributeError: module 'twisted' has no attribute '__version__'
```

Has anyone seen this?
Apologies if this is a duplicate issue.

**Comment by howard-statestitle** [comment]
I've found the fix for this: adding `enable_implicit_namespace_pkgs = True` to pip install
https://github.com/dillon-giacoppo/rules_python_external/issues/38#issuecomment-674506841

**Comment by oberstet** [comment]
interesting! glad you got it working. and thanks for leaving a note here. if there is anything we can/should do here, let me know. is it worth documenting? asking as I haven't ever seen it live ...
