### ISSUE TITLE
Auto ping/pong logs should be debug instead of info

### ISSUE THREAD

**Issue by klinquist** [crossbario/autobahn-python#1524]
https://github.com/crossbario/autobahn-python/blob/2466c2b4a666c49bb3ccd50502a3c49e07b378ec/autobahn/websocket/protocol.py#L852-L855

With the latest version of autobahn, my logs are being filled by auto ping/pong messages :)

**Comment by oberstet** [comment]
uups. this should be a debug, not info level log message. well, we don't have CI tests for _not_ logging;) anyways, I fix it.

**Comment by oberstet** [comment]
ok, here:

https://pypi.org/project/autobahn/22.2.2/
https://github.com/crossbario/autobahn-python/tree/v22.2.2

**Comment by klinquist** [comment]
Thanks!
