### ISSUE TITLE
Unpleasant amount of extra logging at info level arrives in 22.4.1

### ISSUE THREAD

**Issue by cjw296** [crossbario/autobahn-python#1561]
Using autobahn with Twisted, as of 22.4.1 and above, this extra logging has appeared:
```
((<LogLevel=info>,
  '<unknown.> connection established for peer="tcp4:127.0.0.1:56444"'),
 (<LogLevel=info>,
  '<autobahn.twisted.websocket.WebSocketAdapterProtocol.connectionMade> '
  'connection established for peer="tcp4:127.0.0.1:33983"'),
 (<LogLevel=info>,
  '<autobahn.websocket.protocol.WebSocketServerProtocol.onConnect>: '
  "request={'extensions': [],\n"
  " 'headers': {'cache-control': 'no-cache',\n"
  "             'connection': 'Upgrade',\n"
  "             'host': '127.0.0.1:33983',\n"
  "             'pragma': 'no-cache',\n"
  "             'sec-websocket-key': 'ygJydDrmloOd4+dw1FuR0Q==',\n"
  "             'sec-websocket-version': '13',\n"
  "             'upgrade': 'WebSocket',\n"
  "             'user-agent': 'AutobahnPython/22.4.1'},\n"
  " 'host': '127.0.0.1',\n"
  " 'origin': '',\n"
  " 'params': {},\n"
  " 'path': '/v5',\n"
  " 'peer': 'tcp4:127.0.0.1:56444',\n"
  " 'protocols': [],\n"
  " 'version': 13}"),
...
 (<LogLevel=info>,
  'onConnect callback completed successfully with result=None'),
```

This feels excessive. How can we turn off or disable this new logging?
At the very least, it should be logged at debug, but even so, it's extremely verbose and it would be great if there was a way to disable it completely...

**Comment by oberstet** [comment]
quick test, here is how that looks like with log level "info" and a reconnecting client on Twisted:
![Bildschirmfoto von 2022-05-06 18-34-45](https://user-images.githubusercontent.com/233340/167175573-68be3fdf-35cf-48e2-bbcc-21d5a73c21a4.png)

**Comment by cjw296** [comment]
[ccf4503](https://github.com/oberstet/autobahn-python/commit/ccf450332bb43cab02e0f2c5699cd686130e5f41) certainly appears to make this much better, when will it land in a release?

(Ideally we'd like these not to be sent at all, since the debug logging is still pretty heavy...)

**Comment by oberstet** [comment]
> when will it land in a release?

once this PR is merged, any next release will contain it. there likely will be a 22.6.1 ..

> we'd like these not to be sent at all

that's how it works already, as the txaio logger will make the log functions for non-active log levels a NoOp:

https://github.com/crossbario/txaio/blob/e00e3f079139dc32805fc595044138e1c0114f40/txaio/tx.py#L76
