### ISSUE TITLE
Need 24.4.2 published to PyPI to resolve issue with new setuptools

### ISSUE THREAD

**Issue by millsks** [crossbario/autobahn-python#1644]
The latest setuptools that was released a few hours ago finally removed the test module from `setuptools.command`. The 23.6.2 version has the import of test in the setup.py, whereas version 24.4.2 does not.

https://github.com/pypa/setuptools/tree/v71.1.0/setuptools/command
https://github.com/pypa/setuptools/tree/v72.0.0/setuptools/command

**Comment by millsks** [comment]
If you are not able to push 24.4.2 would you at least be able to pin setuptools to <72.0.0 for the time being?

**Comment by Plonq** [comment]
Related: https://github.com/pypa/setuptools/issues/451

**Comment by dimbleby** [comment]
Link should have been https://github.com/pypa/setuptools/issues/4519

**Comment by iamrraj** [comment]
How can i fix this `setuptools` on this lib ?

**Comment by iamrraj** [comment]
To temporarily fix the issue with the `autobahn` package, I installed it directly from the specific tag `v24.4.2` on the GitHub repository. This was done by adding the following line to the `requirements.txt` file:

```
git+https://github.com/crossbario/autobahn-python@v24.4.2#egg=autobahn
```

This ensures that the `autobahn` package is installed from the specified tag, which addresses the issue for now.

**Comment by cortadocodes** [comment]
This worked for me (with poetry) - thanks @iamrraj!

**Comment by sergei-lobanov** [comment]
Is it possible to do the same fix for 23.x? we are using Python 3.8, can't upgrade to 3.9 right now to use 24.x versions

**Comment by gayath-su** [comment]
setuptools has yanked v72.0.0, so we are okay for now

[https://github.com/pypa/setuptools/issues/4518](https://github.com/pypa/setuptools/issues/4518)

**Comment by sergei-lobanov** [comment]
change is still required, as it was deprecated 5 years ago, so better to update it soon than later. but yeah now we have more time

**Comment by oberstet** [comment]
pls see: https://pypi.org/project/autobahn/24.4.2/

> sorry, had some hassles with 2FA and tokens and what, sorted that out, so publications are working automated again=)
