### ISSUE TITLE
Indentation of Python Code in Examples

### ISSUE THREAD

**Issue by guettli** [crossbario/autobahn-python#165]
I think it would be better to use four spaces for the indentation of Python code. It makes copy+paste (from the examples) much easier.

Of course the project owner can make this decision. I raised this, since I could not find an explicit statement like "we use three spaces for indentation".

If you really prefer three spaces, ok, tell us, and close this issue.

**Comment by RobbieClarken** [comment]
@oberstet It looks like the project switched to 4 space indentation [in 2015](https://github.com/crossbario/autobahn-python/commit/a07a9513cdc0a8cbf19fef5389907c577da583ed) and this is now specified in the [coding style guide](https://github.com/crossbario/autobahn-python/blob/master/DEVELOPERS.md#coding-style). Would you be open to a MR that updates the docs to be consistent with the new style? I think it would make copying and pasting code from the docs easier.
