### ISSUE TITLE
Exceptions are swallowed in wamp example2

### ISSUE THREAD

**Issue by guettli** [crossbario/autobahn-python#169]
I run the server and client from wamp example2 unmodified, and everything looks good.

Then I modified the server: https://github.com/tavendo/AutobahnPython/blob/master/examples/wamp/rpc/simple/example2/server.py

```
   def onSessionOpen(self):
      print '#######'
      assert 0
```

I see '#######' but not the exception produced by "assert 0".

I guess that this exception swallowing is not done by AutobahnPython, I guess it comes from twisted.

The Zen of Python: ... Errors should never pass silently.

Please update the example, to make it a better playground. Thank you.

**Comment by mtourne** [comment]
It does seem that all exceptions are silently swallowed in all my autobahn user code, it makes it a lot harder to program in.
