### ISSUE TITLE
Implement WAMP long-poll transport

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#175]
Finish implementation in:
- https://github.com/tavendo/AutobahnPython/blob/master/autobahn/autobahn/wamp/http.py

**Comment by haizaar** [comment]
Sorry for reanimating the dead... Does autobahn-python support long-polling transport? I saw the twisted version was there, but you moved it crossbar eventually, right?

**Comment by oberstet** [comment]
yeah, the WAMP long-poll listening endpoint, as needed for a router, has moved to crossbar (OSS). I think we once even had a long-poll _client_ in autobahn/python - which is pervert, and sth no one needs;) not sure if that is still there somewhere, and about status. anyways: LP clients: that is supported in autobahn-js - where it does make sense ..

**Comment by haizaar** [comment]
@oberstet Did you have clients that required using longpoll between device(not browser)<->corssbar due to corporate policies? One of my team members says he encountered this once, so I'm trying to figure out how common it is.

**Comment by oberstet** [comment]
In the early days of websocket (anno 2013) getting older and/or IE browsers to work with WAMP could make use of long-poll.

Corporate policies: yeah, that might be a thing ("we do not allow websocket at all!"), but I haven't seen that myself as a plicy enforced. Usually, corporate proxies/middlewares - not browsers - are the prime source of issues these days. Our advice defaults to: use TLS (the latest) and secure WebSocket, and have the TLS terminated directly between the browser and crossbar. You might need to whitelist the target crossbar with the corporate MITM middleware to be allowed to bypass it.

> for the record, it moved here: https://github.com/crossbario/crossbar/blob/master/crossbar/webservice/longpoll.py

**Comment by haizaar** [comment]
Thank you for the input!
