### ISSUE TITLE
Refactor Logging

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#243]
This depends on issue #242 
1. Add a new method `LoopMixin.log(msg)` to loop mixin.
2. Cleanup:
   - All code in `autobahn/twisted/*` uses Twisted logging
   - All code in `autobahn/asyncio/*` uses Python standard logging
   - All code in `test` and `autobahn/wamp1` folders remains untouched
   - All other code uses `LoopMixin.log`

**Comment by wolfhechel** [comment]
When is this marked to be released?

**Comment by kampka** [comment]
@wolfhechel Sorry, but AutobahnPython has changed so much since my patch that it can no longer be applied. I don't now if or when I will get back to this, so if want to see it merged, feel free to rebase the patch against a current version of AutobahnPython, minding @oberstet's comments on #303.

**Comment by oberstet** [comment]
this depends on https://github.com/tavendo/txaio/issues/8

**Comment by oberstet** [comment]
we have that now: via txaio. shiny, full featured, structured logging. used in Autobahn and Crossbar.io
