### ISSUE TITLE
AutobahnPython does not work with Nginx load balancing

### ISSUE THREAD

**Issue by zhongjin616** [crossbario/autobahn-python#246]
Thanks for your great work! but i found that when i use Nginx as the websocket proxy for AutobahnPython and set up load balancing , the Autobahn will just reject the connection. when Nginx doing load balancing , it will discard the PORT, thus the autobahn will return a Bad GateWay reason.

**Comment by bcb** [comment]
Closed without responding?

**Comment by meejah** [comment]
Questions like the original are best asked on the mailing-list or IRC.

**Comment by Kostanos** [comment]
Any solution for this one? recommendation?

**Comment by meejah** [comment]
I've seen nginx work as a reverse-proxy in front of Crossbar. If there seems to be an autobahn bug here for some reason, can you please file more details etc (probably in a separate ticket?)
