### ISSUE TITLE
limit parallel connection attempts

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#26]
The spec says:

"There MUST be no more than one connection in a CONNECTING state. If multiple connections to the same IP address are attempted simultaneously, the client MUST serialize them"

**Comment by oberstet** [comment]
The spec (RFC6455) is clear in this regard, and Autobahn doesn't implement this. However, this is aimed at browsers that need to cope with rogue, random JS. This is largely irrelevant for AutobahnPython, as we cannot contain Python app code _above_ AutobahnPython, or prohibit it from doing whatever it likes. Won't fix. Not worth the hassles.

**Comment by meejah** [comment]
FWIW, I agree. Browsers have to cope with possibly-malicious browser JS, but if you're running "maybe malicious" Python you've already lost. (And similarly, if you have 19 Firefox instances running, you can still make 19 connections).
