### ISSUE TITLE
Benchmark performance impacts of timers

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#265]
Autobahn uses `callLater` at various places to issue calling of functions at a later time.

Massive numbers of timers might have sever performance impacts. We don't know today. Hence we should a performance tests to measure the impact.

See also: https://github.com/tavendo/AutobahnPython/issues/248

**Comment by oberstet** [comment]
we have a sophisticated batched/chunked timer machinery now via txaio and used in Autobahn for massive scalable WebSocket ping/pong/heartbeating

**Comment by meejah** [comment]
For posterity, there are some graphs etc on https://github.com/crossbario/autobahn-python/issues/642#issuecomment-215643003
