### ISSUE TITLE
CORS support to WAMP-over-Longpoll transport

### ISSUE THREAD

**Issue by techzhou** [crossbario/autobahn-python#284]
chrome developr console output: 

> ```
> AutobahnJS debug enabled 
> trying to create WAMP transport of type: longpoll 
> longpoll.Factory.create 
> new http_post request http://127.0.0.1:8786/lp/open 
> {"protocols":["wamp.2.json"]} 2000 
> using WAMP transport type: longpoll 
> OPTIONS http://127.0.0.1:8786/lp/open 
> XMLHttpRequest cannot load http://127.0.0.1:8786/lp/open. No 
> 'Access-Control-Allow-Origin' header is present on the requested 
> resource. Origin 'http://127.0.0.1:6543' is therefore not allowed 
> access. The response had HTTP status code 501. 
> longpoll.Transport: could not open transport 0 
> retrying in 1.4713375856010915 s 
> ```

It seems like cross origin, chrome send OPTIONS request. AutobahnPython longpoll dosent support OPTIONS request.

PS. from https://groups.google.com/forum/#!topic/autobahnws/C6Zkfj2Xi28

**Comment by klanjabrik** [comment]
Sorry, is there any progress?

**Comment by dis2ro** [comment]
Got the same issue. How to fix?

**Comment by oberstet** [comment]
The whole WAMP router thing (and hence transports too) have moved to Crossbar.io - there is no WAMP router / listening transport in Autobahn anymore.
