### ISSUE TITLE
Auto-reconnect for asyncio

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#295]
AutobahnJS has a quite sophisticated, configurable automatic reconnection mechanism. We should have that too in AutobahnPython

**Comment by mkohler** [comment]
Regarding ReconnectingClientFactory, see also #389.

**Comment by jennolsen84** [comment]
Is it possible to implement reconnecting to crossbar with asyncio with 0.11.0+?  I understand if the reconnecting client factory might not there yet, but I am afraid if I implement simple tcp reconnection, I might miss higher level WAMP reconnect logic, etc.

For simple reconnection logic, I was going to use this as a guide:  http://stackoverflow.com/questions/25998394/how-to-reconnect-a-socket-on-asyncio

**Comment by tmlmt** [comment]
Hi all. What the update on this issue?
I've seen this [stackoverflow post](http://stackoverflow.com/questions/31900592/autobahnpython-w-twisted-ssl-optionsforclienttls-on-websocket-wampwebsocketclie) for a "deprecated approach" workaround with twisted classes, or [this github code](https://github.com/isra17/autobahn-autoreconnect/blob/master/autobahn_autoreconnect/__init__.py) which proposes a rewrite of ApplicationRunner for asyncio. I am using twisted, I like the simplicity of the ApplicationRunner/ApplicationSession system, and would love to be able to have an auto-reconnect application...

**Comment by remyroy** [comment]
If you are on asyncio, the solution from [isra17/autobahn-autoreconnect](https://github.com/isra17/autobahn-autoreconnect/blob/master/autobahn_autoreconnect/__init__.py) is working fine.

**Comment by scrawl** [comment]
> If you are on asyncio, the solution from isra17/autobahn-autoreconnect is working fine.

It does indeed - perhaps it could be added to the official examples until a more sophisticated solution is implemented?

**Comment by oberstet** [comment]
We have it for Twisted now, but not for asyncio. I'll have a look.

**Comment by oberstet** [comment]
FWIW, above fork has serious licensing issues:

* LICENSE file in the repo says GPL v2
* PyPI distribution says LGPL v2
* License header in the only relevant source file says MIT
* they fail to distribute our original LICENSE file (which they are required to do)

Anyway, this is broken code (it won't run with recent Autobahn versions)

**Comment by tiaod** [comment]
When will this get fixed?

**Comment by meejah** [comment]
There is a solution if you use the newer `component` API; both asyncio and twisted versions of this do auto-reconnect (with backoff and jitter etc). See `examples/{asyncio,twisted}/wamp/component/*` for some examples.

**Comment by tiaod** [comment]
@meejah Cool, but seems not documented yet. 😅

**Comment by morissette** [comment]
I handle reconnecting w/ asyncio here:
`class Service(Eventify):
    """
    Create crossbar service
    """
    def setup_runner(self):
        """
        Setup instance of runner var
        """
        runner = ApplicationRunner(
            url=self.config['transport_host'],
            realm=u'realm1',
            extra={
                'config': self.config,
                'handlers': self.handlers,
            }
        )
        return runner


    @staticmethod
    def check_event_loop():
        """
        Check if event loop is closed and
        create a new event loop
        """
        loop = asyncio.get_event_loop()
        if loop.is_closed():
            asyncio.set_event_loop(asyncio.new_event_loop())


    def check_transport_host(self):
        """
        Check if crossbar port is open
        on transport host
        """
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex(('events-server',8080)) # TODO: Read from config vs using hard coded hostname
        if result == 0:
            logging.info('port 8080 on crossbar is open!')
            return True
        return False


    def reconnect(self):
        """
        Handle reconnect logic if connection
        to crossbar is lost
        """
        connect_attempt = 0
        max_retries = self.config['max_reconnect_retries']
        logging.info('attempting to reconnect to crossbar')
        runner = self.setup_runner()
        while True:

            if connect_attempt == max_retries:
                logging.info('max retries reached; stopping service')
                sys.exit(1)
            self.check_event_loop()

            try:
                logging.info('waiting 5 seconds')
                time.sleep(5)
                if self.check_transport_host():
                    logging.info('waiting 10 seconds to ensure that crossbar has initialized before reconnecting')
                    time.sleep(10)
                    runner.run(Component)
                else:
                    logging.error('crossbar host port 8080 not available...')
            except RuntimeError as error:
                logging.error(error)
            except ConnectionRefusedError as error:
                logging.error(error)
            except ConnectionError as error:
                logging.error(error)
            except KeyboardInterrupt:
                logging.info('User initiated shutdown')
                loop = asyncio.get_event_loop()
                loop.stop()
                sys.exit(1)
            connect_attempt += 1


    def start(self, start_loop=True):
        """
        Start a producer/consumer service
        """
        txaio.start_logging(level='info')
        runner = self.setup_runner()
        if start_loop:
            try:
                runner.run(Component)
            except ConnectionRefusedError:
                logging.error('Unable to connect to crossbar instance. Is it running?')
                sys.exit(1)
            except KeyboardInterrupt:
                logging.info('User initiated shutdown')
                loop = asyncio.get_event_loop()
                loop.stop()
                sys.exit(1)
            self.check_event_loop()
            self.reconnect()
        else:
            return runner.run(
                Component,
                start_loop=start_loop
            )`

**Comment by bodik** [comment]
i guess this one has better KeyboardInterrupt handling, might be handy for small projects
```
       shutdown = False
        while not shutdown:
                try:
                        ## code mainly taken from ApplicationRunner but can handle repeating router failures/disconnects
                        loop = asyncio.get_event_loop()
                        if loop.is_closed():
                                asyncio.set_event_loop(asyncio.new_event_loop())
                                loop = asyncio.get_event_loop()

                        runner = autobahn.asyncio.wamp.ApplicationRunner(url, realm)
                        coro = runner.run(Slave, start_loop=False, log_level="debug")
                        (transport, protocol) = loop.run_until_complete(coro)
                        loop.add_signal_handler(signal.SIGTERM, loop.stop)
                        try:
                                loop.run_forever()
                        except KeyboardInterrupt:
                                logging.info("aborted by user")
                                shutdown = True
                        if protocol._session:
                                loop.run_until_complete(protocol._session.leave())
                        loop.close()

                except Exception as e:
                        logging.error(e)
                        try:
                                time.sleep(1)
                        except KeyboardInterrupt:
                                shutdown = True
```

**Comment by oberstet** [comment]
fixed (see https://github.com/crossbario/autobahn-python/issues/295#issuecomment-329566423)
