### ISSUE TITLE
Support for MicroPython/asyncio

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#298]
see also: https://github.com/crossbario/crossbar/issues/166

**Comment by raveslave** [comment]
I'd be interested knowing if anyone spent time trying to minimize the footprint of running autobahn on an embedded (arm) device? We've tried stripping down cpython manually but it's still over 5MB.
I could offer say 10MB of RAM though but really want to find a way to distribute the python code + runtime in a minimal (preferably binary form). 

Anyone knowing more on the status & challenges of using micropython?

**Comment by hoh** [comment]
I am looking at connecting MicroPython to Crossbar using WAMP on an [ESP8266](https://fr.wikipedia.org/wiki/ESP8266).

The first part missing for WAMP appears to be the support for websocket subprotocols in the MicroPython [websocket library](https://github.com/micropython/micropython/blob/cbef0dba2eef29757237dfe4bca3d21e6a81a0ba/extmod/modwebsocket.c). There is also a [Python version](https://github.com/micropython/webrepl/blob/master/webrepl_cli.py#L33) that would be easier to hack on.

**Comment by oberstet** [comment]
Autobahn includes a WebSocket library, but requires either Twisted or asyncio. We won't port Autobahn to anything else.

**Comment by hoh** [comment]
MicroPython supports most of asyncio, that part could work.

I looked at making micropython import `autobahn.asyncio.wamp.ApplicationSession`, it would require adding/faking many dependencies in MicroPython (mainly from standard CPython library).

I am not sure whether it makes sense to add support for MicroPython in Autobahn core, or if creating an optimised autobahn-micropython would make more sense :
* there are a lot of dependencies that make sense in the CPython implementation but little in MicroPython (eg: zlib, six, ...).
* size can be an issue: the autobahn-python library is 1.3 MB (v0.16.0) and MicroPython itself is in the 524 kB range. Some boards only have 1 MB of flash.
* many class abstractions make readable code, but are very slow on embedded devices

**Comment by oberstet** [comment]
won't fix
