### ISSUE TITLE
Missing standalone argument Application.run 

### ISSUE THREAD

**Issue by saurav2k4u** [crossbario/autobahn-python#306]
Hello - I am absolutely new to Autobahn. Please help me understand how do i pass the standalone argument to instance method "run" of autobahn.twisted.wamp.Application.
Source:
http://autobahn.ws/python/_modules/autobahn/twisted/wamp.html#Application.run

Not sure why it is not working for me.
https://github.com/tavendo/AutobahnPython/blob/master/examples/twisted/wamp/app/klein/example2/server.py
On running this example:
Got TypeError: run() got an unexpected keyword argument 'standalone'

**Comment by funnydoggie** [comment]
Hi,
TypeError: __init__() got an unexpected keyword argument 'standalone'
when trying wamp example "python calculator.py --web 80"
Autobahn examples work fine, and I checked install of crossbar test OK /opt/crossbar/bin/crossbar version tests OK at 0.10.2
