### ISSUE TITLE
Crossbar Router Refactor now creates Twisted dependency

### ISSUE THREAD

**Issue by jzelinskie** [crossbario/autobahn-python#310]
Whereas before when the router code was in the Autobahn package, one could depend only on asyncio, now that the code is in Crossbar.io, it depends on twisted. Are there any plans to alleviate this dependency? We prefer to use asyncio (trollius) and not bring in any twisted dependencies.

**Comment by helambuapps** [comment]
`if __name__ == '__main__':` part is not optional when connecting an asyncio based guest app component to the router, is it?

**Comment by oberstet** [comment]
@helambuapps An asyncio based WAMP component cannot be run by Crossbar.io in a container worker (which would start and connect the component to a router itself). But must be run in a guest worker - and here you have to connect the component yourself. And hence you would need code in `__main__` which does that, e.g. using `ApplicationRunner`.
