### ISSUE TITLE
Application with asyncio

### ISSUE THREAD

**Issue by Vayel** [crossbario/autobahn-python#312]
Is the [Application](https://github.com/tavendo/AutobahnPython/tree/master/examples/twisted/wamp/app/hello) class projected to be implemented with asyncio?

**Comment by oberstet** [comment]
Yes. We want to give users a choice of

* writing components by deriving from `ApplicationSession` or
* writing apps by using `Application`

The difference is stylistic. The latter being more "Flask like" with a global app object. The latter builds on the former.

We want to have that for both Twisted and asyncio.

**Comment by Vayel** [comment]
Ok. Thanks!

**Comment by Vayel** [comment]
Perhaps it would be a better idea to wait for Twisted being compatible with Python 3?

**Comment by oberstet** [comment]
1. Twisted is Py 3 now as far as the features used in Autobahn a concerned.
2. The Flask style Application thing isn't sth we will support
