### ISSUE TITLE
Make @subscribe and @register accept options

### ISSUE THREAD

**Issue by deceze** [crossbario/autobahn-python#336]
The `@subscribe` and `@register` decorators should accept the same options as the corresponding methods in `ApplicationSession`, e.g.:

``` python
@register('foo', RegisterOptions(details_arg='bar', discloseCaller=True))
def baz(bar):
  ..
```

Perhaps even:

``` python
@register('foo', details_arg='bar', discloseCaller=True)
```

This would make code which relies on `RegisterOptions`/`SubscribeOptions` much more readable, since it keeps the annotations inline instead of requiring a fallback to `onJoin` callbacks.

**Comment by meejah** [comment]
Although not nearly as general as the above,  it's possible to set the options for *all* @register methods in your class by passing an `options=` arg like `self.register(self, options=...)` when you do the registration.

Something like the above would be good, though.

**Comment by oberstet** [comment]
This will land via https://github.com/crossbario/autobahn-python/pull/824

**Comment by oberstet** [comment]
ok, landed
