### ISSUE TITLE
Serializing binary data using msgpack seralizer.

### ISSUE THREAD

**Issue by mtourne** [crossbario/autobahn-python#350]
In reference to this topic : 
https://github.com/tavendo/WAMP/issues/4

It seems that it should be possible to serialize binary data using the msgpack serializer.
The data will actually pack just fine from the data producer side, but on the consumer side the binary data is assumed to be a utf8 string, and I'll get this error :

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by estan** [comment]
If this is really the case, it's a blocker for us. We're working on software for machine control, and quite soon I'll be building a component for controlling an image detector in the machine. I will need to be able to deliver binary data. Hopefully without encoding it as base64 or something else crazy :)

**Comment by meejah** [comment]
@mtourne can you post more details of the case that's failing? I wrote a small unit-test encoding a ``Yield`` message with one arg that is a ``bytes`` with everything from 0->255 and it seems to work and de-serialize fine (Python 2.7 or 3.4.2, msgpack 0.4.6, autobahn master)

**Comment by tangyouze** [comment]
I also come across the same issue.
Here's the failure code.
```
import asyncio
from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner
import msgpack

print(autobahn.__version__)

class Component(ApplicationSession):
    @asyncio.coroutine
    def onJoin(self, details):
        def compute():
            t = {'a': 'b'}
            msg = msgpack.packb(t)
            print('msg', msg)
            return msg

        self.register(compute, 'com.test')
        yield from asyncio.sleep(1)
        result = yield from self.call('com.test')
        print('result', result)

    def onDisconnect(self):
        asyncio.get_event_loop().stop()


runner = ApplicationRunner(
    "ws://xxx.xxx.xxx.xxx:8080/ws",
    "crossbardemo"
    # debug_wamp=True,  # optional; log many WAMP details
    # debug=True,  # optional; log even more details
)
runner.run(Component)
```

And I get the following error

```
C:\Anaconda3\python.exe D:/Dropbox/code/quantlib/learn/wowautobahn.py
0.10.9
msg b'\x81\xa1a\xa1b'
While firing onJoin
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\txaio\aio.py", line 338, in done
    res = f.result()
  File "C:\Anaconda3\lib\asyncio\futures.py", line 275, in result
    raise self._exception
  File "C:\Anaconda3\lib\asyncio\tasks.py", line 234, in _step
    result = coro.throw(exc)
  File "D:/Dropbox/code/quantlib/learn/wowautobahn.py", line 18, in onJoin
    result = yield from self.call('com.test')
  File "C:\Anaconda3\lib\asyncio\futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Anaconda3\lib\asyncio\tasks.py", line 287, in _wakeup
    value = future.result()
  File "C:\Anaconda3\lib\asyncio\futures.py", line 275, in result
    raise self._exception
autobahn.wamp.exception.SerializationError: success return value from invoked procedure "com.test" could not be serialized: WAMP serialization error ('utf-8' codec can't decode byte 0x81 in position 16: invalid start byte)

Process finished with exit code -1

```

**Comment by meejah** [comment]
So far I've tried the following, with twisted and asyncio components.

crossbar master + autobahn master + python2 or 3: works
crossbar master + autobahn 0.10.9 + python2 or 3: works
crossbar 0.11.1 + autobahn 0.10.9 + python2 or 3: works

Here, "works" means I get something like this in the logs (using @tangyouze's code):

```
2015-11-18T16:39:18-0700 [Controller  21114] Guest 'worker3': started
2015-11-18T16:39:18-0700 [Container   21122] join!
2015-11-18T16:39:18-0700 [Container   21122] msg b'\x81\xa1a\xa1b'
2015-11-18T16:39:18-0700 [Container   21122] result b'\x81\xa1a\xa1b'
```

I also tried having only JSON serializer, in which case it does fail but with an error-message:

```
2015-11-18T16:43:23-0700 [Container   24725] Fatal error in component: While firing onJoin - success return value from invoked procedure "com.test" could not be serialized: WAMP serialization error (b'\x81\xa1a\xa1b' is not JSON serializable)
```

Is it possible this is a windows-only problem? @mtourne were you running on windows as well?

**Comment by oberstet** [comment]
no response from OP
