### ISSUE TITLE
Contemplate about type hints

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#482]
The lack of static type hints/annotations. Addressed in https://www.python.org/dev/peps/pep-0484/. Scheduled for 3.5.

We should think about using that .. it can add to stability. I miss that.

**Comment by oberstet** [comment]
won't fix, as we must/want to support 2.7 (for now), which cannot digest or even only ignore type hints in sources

**Comment by choppsv1** [comment]
Can this issue be revisted now, in 2021 with python 2 truly dead?

**Comment by om26er** [comment]
I am curious, is this issue about adding type hints to the code base or is there more than that ?

**Comment by choppsv1** [comment]
> I am curious, is this issue about adding type hints to the code base or is there more than that ?

Right, it's to add type hinting to the public APIs. Otherwise the usefulness of using them in an autobahn/crossbar using project is much reduced.
