### ISSUE TITLE
Replace listenWS/connectWS

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#505]
Replace all occurences of
- `autobahn.twisted.websocket.listenWS`
- `autobahn.twisted.websocket.connectWS`

in all Twisted WebSocket examples with standard Twisted endpoint based code.

**Comment by oberstet** [comment]
both of the functions are deprecated

**Comment by emesterhazy** [comment]
For anyone else running into this, take a look at the echo example - it appears to be up-to-date.

https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/websocket/echo/server.py
