### ISSUE TITLE
Enabling wamp advance features

### ISSUE THREAD

**Issue by cchilukoori** [crossbario/autobahn-python#531]
Hi,

I am trying to implement call_timeout in my autobahn python code. How can I enable that feature?

Thanks,
Chaitanya.

**Comment by cchilukoori** [comment]
Sorry. Is something wrong with the ticket?

**Comment by goeddea** [comment]
This is an issue tracker. For general help requests, there is the mailing list (https://groups.google.com/forum/#!forum/crossbario) or StackOverflow (tag with `crossbar`).

Regarding your question itself: There is no need to enable advanced features. Call timeouts are a feature which is currently being defined. It's not implemented yet.

**Comment by cchilukoori** [comment]
Thank you. Please close it.
