### ISSUE TITLE
processHandshake is unnecessarilly strict in UTF-8 decoding

### ISSUE THREAD

**Issue by bbangert** [crossbario/autobahn-python#533]
We see cases where some browsers, in foreign locale's trigger the default strict decoding of utf-8 during processHandshake. It seems like lenient utf-8 decoding should be done.

The error:
```
encodings.utf_8 in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 647: invalid continuation byte



Stacktrace (most recent call last):

  File "autopush/websocket.py", line 85, in wrapper
    return func(self, *args, **kwargs)
  File "autopush/websocket.py", line 313, in processHandshake
    return self.parent_class.processHandshake(self)
  File "autobahn/websocket/protocol.py", line 2761, in processHandshake
    (self.http_status_line, self.http_headers, http_headers_cnt) = parseHttpHeader(self.http_request_data)
  File "autobahn/websocket/protocol.py", line 388, in parseHttpHeader
    raw = data.decode('utf8').splitlines()
  File "encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
```

Couldn't this use 'ignore' on the decode line to ignore anything it can't coerce?

**Comment by oberstet** [comment]
I have dug into the spec for HTTP header processing and in particular [this](http://tools.ietf.org/html/rfc5987), [this](http://trac.tools.ietf.org/wg/httpbis/trac/ticket/111) and [this](https://code.djangoproject.com/ticket/18916).

I think the immediate bug here is that we decode using UTF8, while we should decode using ISO-8859-1. Only via the mechanism described in RFC5987, it would be possible to support full UTF8 in HTTP header values.

**Comment by bbangert** [comment]
Unfortunately I don't know offhand what characters caused this bug for a reproduction, since Sentry used utf-8 decode with ignore to submit the bug, which stripped the characters out.

**Comment by bbangert** [comment]
Is the goal to use ISO-8859-1 decoding? Any idea when this will be fixed, as we're increasing our scale this error is happening increasingly regularly. Right now I'm probably going to use a separate fork that relaxes the strictness.

**Comment by oberstet** [comment]
waiting for travis, but this should be good.

**Comment by bbangert** [comment]
Great, thanks!
