### ISSUE TITLE
provide subscription topic in event details for non-pattern-based subscriptions

### ISSUE THREAD

**Issue by goeddea** [crossbario/autobahn-python#534]
Currently the subscription handler receives the event details as they come over the wire. For non-pattern-based subscriptions, the subscription topic is not sent over the wire since the client has the knowledge. Consequently the subscription details do not provide the topic.

This is unexpected behavior, since it exposes a wire-level optimization to the user.

In Autobahn|JS, the subscription topic is provided for all events. 

Change Autobahn|Python to have the same behavior.

**Comment by azazel75** [comment]
Why this is already implemented in JS  but in Python we are discussing it? It would be much better if the two implementations go in tandem in terms of features and behavior.

**Comment by goeddea** [comment]
I just changed the behavior of Autobahn|JS an hour ago. 

The above issue was not supposed to be opening a discussion. I've edited it to reflect that. There should obviously not be any difference between the libraries regarding this.

**Comment by meejah** [comment]
From examining the code, I believe this is already passed along, but only if you have ``details_arg`` set (that is, you get the topic in an ``EventDetails`` instance).

**Comment by azazel75** [comment]
Yes it is, i had a pretty old checkout!

**Comment by oberstet** [comment]
Here is test code:

```python
from twisted.internet.defer import inlineCallbacks

from autobahn.twisted.util import sleep
from autobahn.twisted.wamp import ApplicationSession
from autobahn.wamp.types import SubscribeOptions, PublishOptions


class AppSession(ApplicationSession):

    @inlineCallbacks
    def onJoin(self, details):

        def oncounter(counter, details=None):
            print("event for 'oncounter' received: {} {}".format(counter, details))

        sub = yield self.subscribe(oncounter, 'com.example.oncounter', options=SubscribeOptions(match=u'exact', details_arg='details'))
        print("subscribed to topic 'oncounter'")

        counter = 0
        while True:

            ## PUBLISH an event
            ##
            yield self.publish('com.example.oncounter', counter, options=PublishOptions(exclude_me=False, acknowledge=True))
            print("published to 'oncounter' with counter {}".format(counter))
            counter += 1

            yield sleep(1)
```
