### ISSUE TITLE
Allow to pass parameters to the called class with the ApplicationRunner.run() method

### ISSUE THREAD

**Issue by icefo** [crossbario/autobahn-python#536]
I had to pass parameters to a class that is launched by the ApplicationRunner.run() method.

```python
    def run(self, make, args=(), kwargs={}):
        """
        Run the application component.

        :param make: A factory that produces instances of :class:`autobahn.asyncio.wamp.ApplicationSession`
           when called with an instance of :class:`autobahn.wamp.types.ComponentConfig`.
        :type make: callable
        """
        # 1) factory for use ApplicationSession
        def create():
            cfg = ComponentConfig(self.realm, self.extra)
            try:
                session = make(cfg, *args, **kwargs)
            except Exception:
                # the app component could not be created .. fatal
                print_exc()
                asyncio.get_event_loop().stop()
            else:
                session.debug_app = self.debug_app
                return session

        isSecure, host, port, resource, path, params = parseWsUrl(self.url)

        # 2) create a WAMP-over-WebSocket transport client factory
        transport_factory = WampWebSocketClientFactory(create, url=self.url, serializers=self.serializers,
                                                       debug=self.debug, debug_wamp=self.debug_wamp)

        # 3) start the client
        loop = asyncio.get_event_loop()
        coro = loop.create_connection(transport_factory, host, port, ssl=isSecure)
        loop.run_until_complete(coro)

        # 4) now enter the asyncio event loop
        loop.run_forever()
        loop.close()
```
It's simple but useful in some cases.

Totally unrelated but I think you should add this in the examples:
```python
class MyComponent(ApplicationSession):
    def __init__(self, config=None):
        ApplicationSession.__init__(self, config)
```
because I took me some time to figure out when I tried to extend the examples.

Related this time, I changed the
```python
try:
    session = make(cfg, *args, **kwargs)
except Exception as e:
    # the app component could not be created .. fatal
    print(e)
    asyncio.get_event_loop().stop()
```
in
```python
from traceback import print_exc
try:
    session = make(cfg, *args, **kwargs)
except Exception:
    # the app component could not be created .. fatal
    print_exc()
    asyncio.get_event_loop().stop()
```
because it changes error like this:
```python
__init__() takes 1 positional argument but 2 were given
```
in
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/autobahn/asyncio/wamp.py", line 185, in create
    session = make(cfg, *args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
```
It doesn't change much for an experienced developer but for a novice/medium like me it means less time trying to figure out why it doesn't work.

have a good day :-)

**Comment by meejah** [comment]
The way you're "supposed" to give your instantiated ``ApplicationSession`` subclass more information is via the "extra" kwarg; this is then available in your subclass as ``self.config.extra``. This can be anything, but often is a ``dict`` for example, allowing you to pass along any number of extra configuration parameters etc.

I would be curious if you have a suggestion where this should be in the docs/examples to make it more likely you would have discovered this :)

**Comment by icefo** [comment]
I would put it here http://autobahn.ws/python/wamp/programming.html because it would fit really well and anyone interested in autobahn python will read this page.
Maybe you should still add the args=() and kwargs={} because threading.Thread and multiprocessing.Process use it and people are used to it. (that was my case)

I also think that you should also add this in the examples on the pages http://autobahn.ws/python/wamp/programming.html and  http://autobahn.ws/python/wamp/examples.html. Or at least say somewhere: if you want to extend these examples you have to add this. Both cases should explain what the config parameter is.
```python
class MyComponent(ApplicationSession):
    def __init__(self, config=None):
        # Or call the superclass using super()
        ApplicationSession.__init__(self, config)
```
I think you should also say in http://autobahn.ws/python/wamp/programming.html how to handle SIGINT / SIGTERM signals because this would have saved me a lot of time. The documentation from asyncio is not really clear and I ended up writing something that suffered from a "race condition". It would only work half the time and I had to use global variables. The solution was simple:

```python
class MyComponent(ApplicationSession):
    def __init__(self, config=None):
        # Or call using super()
        ApplicationSession.__init__(self, config)
        loop = asyncio.get_event_loop()
        loop.add_signal_handler(signal.SIGINT, self.exit_cleanup)
        loop.add_signal_handler(signal.SIGTERM, self.exit_cleanup)
```

I saw somewhere that you are interested in what the people make with wamp and I wrote something quite nice using [quamash](https://github.com/harvimt/quamash) and wamp: A PyQT5 GUI with a autobahn/python backend. This is an example but I used it to build a bigger app and it worked.

[PyQT5 app](https://gist.github.com/icefo/a1f52aa2a317b8a60f2d)
[autobahn python backend](https://gist.github.com/icefo/aba42c84334fb02e13cd)
