### ISSUE TITLE
RPC Timeservice Python code does not work with Bonefish but Javascript does

### ISSUE THREAD

**Issue by codelectron** [crossbario/autobahn-python#545]
When trying the example /master/examples/twisted/wamp/rpc/timeservice .
Everything works well with Crossbar but only backend.html and frontend.html works with Bonefish and not Python implementations. Since AutobahnJS works with Bonefish, it could be a bug in AutobahnPython. 

A snippet from  bonefish debug message

[wamp_message_processor.cpp:46][process_message] processing message: yield
[wamp_dealer.cpp:405][process_yield_message] session [6404284456041962,crossbardemo,open], yield [2, {}, ["2015-11-04T09:37:00Z"], nil]
[wamp_dealer.cpp:442][process_yield_message] session [6404284456041962,crossbardemo,open], result [6948753422417920, {}, ["2015-11-04T09:37:00Z"], nil]
[websocket_transport.cpp:39][send_message] sending message: result
[websocket_server_impl.cpp:221][on_message] unhandled exception: failed or incomplete serialization

**Comment by meejah** [comment]
Does #542 fix your issue here?

**Comment by codelectron** [comment]
Yes I used the fix from #542 and after that It works like this.

1. Router:crossbar
Backend:backend.py
frontend.py and frontend.html works

2. Router:crossbar
Backend:backend.html
frontend.py and frontend.html works

3. Router:bonefish
Backend:backend.py
frontend.py works
frontend.html does not works
(NOTE:I also tried a wampjs based implementation and it does not work either)

4. Router:bonefish
Backend:backend.html
frontend.py and frontend.html  works

**Comment by meejah** [comment]
@codelectron thanks! Is it correct then to say that with #542 all the python implementations you tried work with bonefish, but one JS one does not...?

**Comment by Afra-Felix** [comment]
@meejah this is codelectron replying from my official id

I see this way, Using Backend Python Implementation With AutobahnJS frontend does not work with bonefish but works with crossbar. WampyJS failed too.

I enabled debug message in AutobahnJS , see below.
1. 
Router:Bonefish
Backend:backend.py
Frontend:frontend.html (with AUTOBAHN_DEBUG = true)
--------------------------------------------------------8x-----------------------------------------------------
autobahn.js:123 AutobahnJS debug enabled
frontend.js:2 Checking
autobahn.js:732 trying to create WAMP transport of type: websocket
autobahn.js:732 using WAMP transport type: websocket
autobahn.js:732 WebSocket transport send [1,"crossbardemo",{"roles":{"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"caller_identification":true,"pattern_based_registration":true,"shared_registration":true,"progressive_call_results":true,"registration_revocation":true}},"publisher":{"features":{"publisher_identification":true,"subscriber_blackwhite_listing":true,"publisher_exclusion":true}},"subscriber":{"features":{"publisher_identification":true,"pattern_based_subscription":true,"subscription_revocation":true}}}}]
autobahn.js:732 WebSocket transport receive [2,4503766347637969,{"roles":{"dealer":{"features":{"call_timeout":true}},"broker":{}}}]
autobahn.js:732 WebSocket transport send [48,6823940815060992,{},"com.timeservice.now"]
--------------------------------------------------------8x-----------------------------------------------------
2. 
Router:Bonefish
Backend:backend.html
Frontend:frontend.html (with AUTOBAHN_DEBUG = true)
--------------------------------------------------------8x-----------------------------------------------------
AutobahnJS debug enabled
frontend.js:2 Checking
autobahn.js:732 trying to create WAMP transport of type: websocket
autobahn.js:732 using WAMP transport type: websocket
autobahn.js:732 WebSocket transport send [1,"crossbardemo",{"roles":{"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"caller_identification":true,"pattern_based_registration":true,"shared_registration":true,"progressive_call_results":true,"registration_revocation":true}},"publisher":{"features":{"publisher_identification":true,"subscriber_blackwhite_listing":true,"publisher_exclusion":true}},"subscriber":{"features":{"publisher_identification":true,"pattern_based_subscription":true,"subscription_revocation":true}}}}]
autobahn.js:732 WebSocket transport receive [2,4703295325716798,{"roles":{"dealer":{"features":{"call_timeout":true}},"broker":{}}}]
autobahn.js:732 WebSocket transport send [48,4923058269716480,{},"com.timeservice.now"]
autobahn.js:732 WebSocket transport receive [50,4923058269716480,{},["2015-11-06T08:13:14.476Z"]]
frontend.js:19 Current time: 2015-11-06T08:13:14.476Z
autobahn.js:732 WebSocket transport send [6,{},"wamp.close.normal"]
autobahn.js:732 WebSocket transport receive [6,{},"wamp.error.goodbye_and_out"]
--------------------------------------------------------8x-----------------------------------------------------

**Comment by meejah** [comment]
@Afra-Felix I tried with ``bonefish --realm crossbardemo -w 8080`` and the frontend timerservice works for me (*with* the #542 fixes of course) with either a Python2 or Python3 environment running ``backend.py``

**Comment by Afra-Felix** [comment]
@meejah Thanks, I will make a fresh build of all and try again and come back.
