### ISSUE TITLE
Wrong txaio backend is used

### ISSUE THREAD

**Issue by hlamer** [crossbario/autobahn-python#547]
I got a very interesting bug.

The project works on Python3 and asyncio. But Twisted is also installed. txaio chose twisted as default backend.
I use `autobahn.asyncio.websocket`. It works at most fine. Only autoping functionality got broken because autoping is scheduled with twisted version of call_later. The bug was discovered a few month after it has appeared.

I fixed this situation with manual `txaio.use_asyncio()` call, however would be better if `autobahn.asyncio.websocket` checks if txaio `using_asyncio()` and either configures txaio or fails loudly.

**Comment by meejah** [comment]
Are you using ``ApplicationRunner`` to start things?

**Comment by meejah** [comment]
(Either way, though, there should probably be some kind of check in ``autobahn.asyncio.*`` somewhere)

**Comment by hlamer** [comment]
No, I don't use ApplicationRunner

**Comment by meejah** [comment]
Are you running your sessions as either a router or container worker in crossbar.io?

**Comment by hlamer** [comment]
No, I don't

**Comment by meejah** [comment]
Hmm, okay.

There are already explicit calls to ``.use_asyncio()`` in the ``autobahn.asyncio.wamp`` package -- but if anything else imports something out of ``autobahn.twisted.wamp`` then that will call ``.use_twisted()`` and "win". That is: you can't mix twisted + asyncio in one process.

So, I think the best thing to do is make either of the ``.use_*()`` calls "one-time" in txaio and have it throw an exception if you try to use something different (e.g. calling ``.use_asyncio()`` twice is okay, but calling ``.use_twisted()`` after gives you an exception).

**Comment by meejah** [comment]
I'm still curious how you're hitting this bug, though; there may be some flow of imports in Autobahn that cases a ``.twisted.*`` thing to get imported ...?

Perhaps after I fix the txaio bug it will become apparent what's happening...

**Comment by hlamer** [comment]
Twisted wasn't imported by me. It just was installed for Python 3.
Look at [this](https://github.com/crossbario/txaio/blob/master/txaio/__init__.py#L120) code. If I understood correctly, it just uses twisted by default.

**Comment by meejah** [comment]
Yes, it does use Twisted by default if it's available, but: https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/wamp.py#L45

**Comment by hlamer** [comment]
Hmm. I have a hypothesis.

I fixed my problem by monkey-patching [this bug](https://github.com/crossbario/txaio/pull/36) and than calling `use_asyncio`. Probably there are no bug in autobahn. wamp called `use_asyncio` on import, but the call wasn't effective because of txaio bug.

**Comment by meejah** [comment]
Great, thanks for testing and following-up :)
