### ISSUE TITLE
About websocket.http.HttpException

### ISSUE THREAD

**Issue by krrr** [crossbario/autobahn-python#548]
I accidentally used latest API and found a whole module(websocket.http) has been removed, will it break old programs? It seems that API reference didn't say it's internal

By the way, there is a bug in `autobahn.asyncio.websocket.WebSocketServerProtocol#_onConnect`: it used that module

**Comment by oberstet** [comment]
yes, that has been replaced with https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/types.py#L189

there is no bug: https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/types.py#L220

**Comment by krrr** [comment]
@oberstet my description was wrong, but the bug do exists: [here](https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/websocket.py#L201)`ConnectionDeny.http.INTERNAL_SERVER_ERROR)` will raise AttributeError

**Comment by oberstet** [comment]
@krrr ah, right. sorry. yes, bug.
