### ISSUE TITLE
Deprecate Python 2.6 support

### ISSUE THREAD

**Issue by hawkowl** [crossbario/autobahn-python#554]
Since one of our dependencies (Twisted) has dropped Python 2.6 support, and another (Cryptography.io) has deprecated it (https://github.com/pyca/cryptography/blob/master/src/cryptography/__init__.py#L21), and it is getting super super long in the tooth, maybe we should consider phasing out support next release.

Opinions, @oberstet, @meejah ?

**Comment by oberstet** [comment]
makes sense. cool, I'm +1

**Comment by hawkowl** [comment]
I think we should raise a DeprecationWarning ASAP, and then drop it in next release + 1. Then it gives some people warning, although I'm not sure how many people actually use 2.6 and would keep their AB up to date to see such a warning...

**Comment by oberstet** [comment]
Awesome! That's even better. Btw: what do you think rgd the fully PEP8 naming stuff. That'll break API. Or should we provide backward compat. classes? At least for some time?

**Comment by hawkowl** [comment]
The backwards compat adapters that raise DeprecationWarnings would be ideal -- since it means people have a transitionary period. Then I think 1.0 would remove all deprecated code, leaving only the new API left.
