### ISSUE TITLE
Spurious loss of transport in a single direction.

### ISSUE THREAD

**Issue by jjmontesl** [crossbario/autobahn-python#555]
Hello.

Since a few weeks ago, I'm facing an seemingly unpredicable issue, and I'm running out of ideas for troubleshooting. My application looks like:

Browser <----> Crossbar.io <------> Autobahn/Twisted/Python

I have observed that after a certain period of time, between 15 minutes and several hours, both published messages and responses to RPC calls stop flowing from my server (Autobahn) to Crossbar.

When this happens, the TCP connection is still alive and RPC calls from Browser/Crossbar do reach Autobahn 

So far I have checked that:

1) Tcpdump shows that data (TCP packets) are not being sent through the network in the autobahn->Crossbar direction.
2) A threaddump of my application doesn't seem to show any stuck threads.
3) The rest of the system continues to work as expected, including other Twisted protocols communicating with other systems.
4) Restarting Crossbar.io (but not the server) works around the issue. Autobahn reconnects and normal message flow is restored.
5) I tried reproducing this by forcing a connection reset (using tcpkill). The connection is closed and Autobahn simply reconnects correctly. (This is not a good test, though, because my problem happens while the socket is still connected and messages from Crossbar do reach my app, but not the other way around).
6) I added methods to the Crossbar component to log session joins and leaves, but looks normal (it's not like autobahn is leaving the session).

My Wamp client is defined as:

```
class WampReconnectingClientFactory(WampWebSocketClientFactory, ReconnectingClientFactory):

    maxDelay = 30

    def clientConnectionFailed(self, connector, reason):
        logger.warn("Failed to connect to WAMP router (trying to reconnect): %s" % reason)
        ReconnectingClientFactory.clientConnectionFailed(self, connector, reason)

    def clientConnectionLost(self, connector, reason):
        logger.warn("Disconnected from WAMP router (trying to reconnect): %s" % reason)
        ReconnectingClientFactory.clientConnectionLost(self, connector, reason)
```

And used as:

```
# WAMP (Autobahn) initialization, running on Twisted
        session_factory = ApplicationSessionFactory(ComponentConfig(realm=u"realm1"))
        session_factory.session = WampInterface
        session_factory._wamp_adaptor = self
        transport_factory = WampReconnectingClientFactory(session_factory, self.wamp_router_url, debug=True)
        transport_factory.setProtocolOptions(failByDrop=False, autoPingInterval=30, autoPingTimeout=10) # Added trying to workaround this issue, but no change observed.
        connectWS(transport_factory)
```

I'm seeking some hints about how to debug this issue, since when this happens the application is unusable (clients cannot enforce a server or Crossbar restart).

(Using autobahn 0.10.7 - 0.10.9, Twisted 15.4.0, crossbar 0.10.4).

Cheers!

**Comment by oberstet** [comment]
Could you try with production settings for the WebSocket transport? http://crossbar.io/docs/WebSocket-Options/#production-settings

The auto-ping/pong in particular ..

**Comment by jjmontesl** [comment]
Unfortunately doesn't seem to help (auto ping pong was already enabled at least from the python-autobahn side).

Any other idea?  How can I access that webstatus? Or where would I add the debug option for the transport? I have tried to use it but didn't observe any change in logging (I guess I put it in the wrong place).

My config.json:

```javascript
{
   "controller": {
   },
   "workers": [
      {
         "type": "router",
         "options": {
            "pythonpath": [".."]
         },
         "realms": [
            {
               "name": "realm1",
               "roles": [
                  {
                     "name": "anonymous",
                     "permissions": [
                        {
                           "uri": "*",
                           "publish": true,
                           "subscribe": true,
                           "call": true,
                           "register": true
                        }
                     ]
                  }
               ]
            }
         ],
         "transports": [
            {
               "type": "web",
               "endpoint": {
                  "type": "tcp",
                  "port": 9000
               },
               "paths": {
                  "/": {
                     "type": "static",
                     "directory": "public_html"
                  },
                  "ws": {
                     "type": "websocket"
                  },
		  "publish": {
		     "type": "publisher",
                     "realm": "realm1",
                     "role": "anonymous"
		  }
               },
	       "options": {
                  "enable_webstatus": false,
                  "enable_hixie76": false,
                  "max_frame_size": 1048576,
                  "max_message_size": 1048576,
                  "auto_fragment_size": 65536,
                  "fail_by_drop": true,
                  "open_handshake_timeout": 2500,
                  "close_handshake_timeout": 1000,
                  "auto_ping_interval": 10000,
                  "auto_ping_timeout": 5000,
                  "auto_ping_size": 4
	       }
            }
         ]
      },
      {
         "type": "container",
         "options": {
            "pythonpath": [".."]
         },
         "components": [
            {
               "type": "class",
               "classname": "scs_message_router.router.AppSession",
               "realm": "realm1",
               "transport": {
                  "type": "websocket",
                  "endpoint": {
                     "type": "tcp",
                     "host": "127.0.0.1",
                     "port": 9000
                  },
                  "url": "ws://127.0.0.1:9001/ws"
               }
            }
         ]
      }
   ]
}
```

Thank you very much.

**Comment by jjmontesl** [comment]
Hi. I found I was calling the publish method from a different thread. After moving those calls to the reactor thread this issue hasn't been observed anymore.

Twisted transports are not thread-safe, so I guess this also applies to Autobahn methods. 

I think this can be closed, Sorry for the (once again) faulty report :-$.

**Comment by oberstet** [comment]
@jjmontesl Glad you could resolve your issue! Don't worry about "faulty reports" - we depend on user feedback and bug reports, and even with this one, there would be a chance to improve our docs at least (yeah, if we had resources;) - so pls don't hesitate to file again - even when not sure.

Yes, Twisted stuff _must_ run on the main thread (and so Autobahn also). You can publish from a background thread in Twisted/Autobahn using `callFromThread` http://twistedmatrix.com/documents/current/core/howto/threading.html ..
