### ISSUE TITLE
implicit requirement of twisted rather than asyncio

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/autobahn-python#556]
crossbar blows up with an import error if you try to use asyncio instead of twisted:

```python
#from autobahn.twisted.wamp   import ApplicationSession
from autobahn.asyncio.wamp   import ApplicationSession
```

```python
  File "/usr/lib/python3.5/site-packages/crossbar-0.11.1-py3.5.egg/crossbar/worker/__init__.py", line 63, in _appsession_loader
    u"crossbar.error.class_import_failed", "session not derived of ApplicationSession"
autobahn.wamp.exception.ApplicationError: ApplicationError('crossbar.error.class_import_failed', args = ('session not derived of ApplicationSession',), kwargs = {})
```

**Comment by oberstet** [comment]
To use Autobahn/asyncio based components, these must be run in guest workers. Running components in container workers or side-by-side with router workers requires Twisted

**Comment by meejah** [comment]
See also this txaio bug which will give you a nicer error-message when it's fixed: https://github.com/crossbario/txaio/issues/42

(Maybe we could provide an even-better error message from crossbar and/or improve the docs)
