### ISSUE TITLE
Logging syntax does not work in Python 2

### ISSUE THREAD

**Issue by crccheck** [crossbario/autobahn-python#567]
In commit abe42b05b4505a80fd95cbe8b284011a2aa00620 logging syntax was changed to something that does not work in Python 2:
```
self.log.debug("dropping connection: {reason}", reason=self.wasNotCleanReason)
```

You'll get see error instead of the intended error:
```
exceptions.TypeError: _log() got an unexpected keyword argument 'reason'
```

The Python2 syntax will work for both: https://docs.python.org/2/library/logging.html#logging.Logger.debug

**Comment by oberstet** [comment]
we're using structured logging from txaio
