### ISSUE TITLE
autobahn.websocket.protocol.parseWsUrl() should be moved

### ISSUE THREAD

**Issue by agronholm** [crossbario/autobahn-python#571]
Trying to import this without calling txaio.use_asyncio() or use_twisted() raises an exception and it should not. @meejah suggested moving it to "util" or somewhere else that doesn't need txaio.

**Comment by meejah** [comment]
Yes, currently, WebSocketProtocol in the protocol.py packages uses txaio and so it would be nice to move parseWsUrl and createWsUrl (at least) to somewhere like util.py

**Comment by meejah** [comment]
See https://github.com/crossbario/autobahn-python/pull/619
