### ISSUE TITLE
Not able to use the decorator  @wamp.subscribe

### ISSUE THREAD

**Issue by maxMidius** [crossbario/autobahn-python#578]
My install version is 
Automatically choosing optimal Twisted reactor
Running on Linux and optimal reactor (epoll) was installed.
     __  __  __  __  __  __      __     __
    /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
    \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/

 Crossbar.io        : 0.11.1
   Autobahn         : 0.10.9
     UTF8 Validator : autobahn
     XOR Masker     : autobahn
     JSON Codec     : ujson-1.33
     MsgPack Codec  : msgpack-python-0.4.5
   Twisted          : 15.4.0-EPollReactor
   Python           : 2.7.2/CPython
 OS                 : Linux-2.6.32-431.40.2.el6.x86_64-x86_64-with-redhat-6.5-Santiago
 Machine            : x86_64
---------------
When I try to subscribe  to  topic like
@wamp.subscribe("com.sysInfo.&lt;host&gt;.&lt;acnt&gt;.procs")
def  onProcInfo(procList) :
    bla bla

The initializer throws an error like 
module does not support attribute subscribe

So my question is  there a minimum version of autobahn  which is needed to support pattern based pubsub topics

Which brings me to the next issue :
pip install  crossbar  is not installing 0.11.2   - (not able to upgrade from 0.11.1)

Thanks for any suggestions

**Comment by icefo** [comment]
Hi !
The following code works with autobahn 0.10.2 and 0.11.0

```python
@wamp.subscribe('com.sysInfo.<host>.<acnt>.procs')
def onProcInfo(self, procList):
    print(procList)

@asyncio.coroutine
def onJoin(self, details):
    print("session ready")
    try:
        res = yield from self.subscribe(self)
        print("Subscribed to {0} procedure(s)".format(len(res)))
    except Exception as e:
        print("could not subscribe to procedure: {0}".format(e))
```

**Comment by maxMidius** [comment]
Thanks a lot for your useful sample @icefo . I should have been a lot more specific about whats not working
It is actually  pattern based registration for Pub/Sub - and furthermore I am using a twisted based wamp not async. My apologies for my incomplete /incorrect problem statement to start with
My code looks like this
```python
from autobahn import wamp
from twisted.internet.defer  import inlineCallbacks
from autobahn.twisted.util import sleep
from autobahn.wamp.exception import ApplicationError
from twisted.logger import Logger
from autobahn.twisted.wamp import ApplicationSession, ApplicationRunner

class MyClient (ApplicationSession) :
    log=Logger()
    @inlineCallbacks
    def onJoin(self, details) :
        print details
        @wamp.topic("com.sys.<host>.<acnt>.procs")
         def onAcntInfo(host, acnt, procInfo) :
              print ("Got %s from %s(%s) " % procInfo, host, acnt)
         try :
               yield session.subscribe(onAcntInfo)
         except ApplicationError as err :
              print ("Unable to subscribe to topic %s" % err)

if __name__ == "__main__" :
    runner=ApplicationRunner(url=u"ws://%s:1080/ws" % cbHost, realm=u"realm1" )
    runner.run(MyClient)

```
The code does not even begin to run complaining about  wamp module does not support topic as an attribute - I am suspecting this type of decorator is not available in the release I am running.

**Comment by maxMidius** [comment]
I am wondering [if this issue on stack](http://stackoverflow.com/questions/27739717/autobahn-subscribing-to-channels-with-regex-or-wildcard-pattern/27743777#27743777) applies to my situation.

**Comment by oberstet** [comment]
@maxMidius no, SO isn't related. patter-based subscriptions _do_ work. It's just not possible from decorators. because this need to be fixed https://github.com/crossbario/autobahn-python/issues/336

**Comment by maxMidius** [comment]
thanks for the response @oberstet  - It is good to know that pattern-based topic subscriptions work in my crossbar configuration. So I guess the obvious question is what is the syntax for the non-decorator subscription  .. (Example or documentation ?) - would it be something like this
```python
yield  session.subscribe(onAcntInfo, u"com.sys.<host>.<acnt>.procs")
```

**Comment by oberstet** [comment]
there is an example here https://github.com/crossbario/crossbarexamples/tree/master/patternsubs and I think we also have docs ..

Am 22.01.2016 11:47 nachm. schrieb maxMidius <notifications@github.com>:

thanks for the response @oberstet<https://github.com/oberstet> - It is good to know that pattern-based topic subscriptions work in my crossbar configuration. So I guess the obvious question is what is the syntax for the non-decorator subscription .. (Example or documentation ?) - would it be something like this

yield  session.subscribe(onAcntInfo, u"com.sys.<host>.<acnt>.procs")

**Comment by maxMidius** [comment]
Thanks again @oberstet . My fault for not carefully reading through the examples - there are lots of good ones there - I got my use case to work -  Here is the final  relevant code snippets 

Publisher Snippet
```python
from autobahn.wamp.types import PublishOptions
class MyAcntInfo(ApplicationSession) :
     myHost="someHost"
     myId = os.environ.get('USER')
    @inlineCallbacks
    def onJoin(self, details) :
         topic=u"com.sys.acntInfo.%s.%s.procs" % (myHost, myId)
         payload="process details"
         while True :
              self.publish( topic, payload, options=PublishOptions(disclose_me=True) )
              yield sleep(60)
      
```
Subscriber Snippet
```python
from autobahn.wamp.types import SubscriberOptions
class MyClient(ApplicationSession) :
     @inlineCallbacks
     def onJoin(self, details) :
         def onAcntInfo(self, procsInfo, details=None)  :
             print ("%s %s" % details, procInfo)

         self.subscribe(onAcntInfo,  u"com.sys.acntInfo...procs", options=SubscriberOptions(match=u"wildcard", details_arg="details")
```

**Comment by maxMidius** [comment]
Closing this issue as it is covered by  #336 - and  there is a work-around (without decorators).
