### ISSUE TITLE
Need ability to "broadcast call" across multiple callees

### ISSUE THREAD

**Issue by maxMidius** [crossbario/autobahn-python#581]
I have this use case in my domain where I want to be able to broadcast call a function request into a network of machines/accounts. So for example 
Let us say we have a bunch of  machines and I want to find out the uptime for each machine
I want to be able to do something like below. This is a sort of hybrid of Pub/Sub and RPC call
We want to spray a request to a bunch of callees with a registration pattern and harvest the responses similar to how pub/sub works - but just once. I know there are lots of details to work out here - especially - how do we know when the responses are all complete ? So we may have to add  a timeout and or token in the request - so we can match the responses to .. 

Backend On every machine 
```python
    @inlineCallbacks
    def onJoin(self, details) :
    def  upTime() :
         return  upTime
    yield self.register (upTime, u"com.sys.%s.upTime" % (myHost) )
```
Frontend on client machine
```python
    @inlineCallbacks
    def onJoin(self, details) :
        def onUptimeCB (upTime, details=None) :
                 print ( "Got uptime =%s  (from %s) " %  (upTime, details)  )

     yield.call (onUptimeCB, "com.sys..upTime", options=SubscriptionOptions(match="wildcard") )
```

**Comment by oberstet** [comment]
see: https://github.com/crossbario/crossbar/issues/480
