### ISSUE TITLE
Submit additional info on authorization

### ISSUE THREAD

**Issue by Ninerian** [crossbario/autobahn-python#598]
I want to submit a additional information within the result of the authorization. Actually I return the WAMP Message ```[70,1,{},[{"secret":"secret456","role":"backend"}]]``` which works as expected. But when I send ```[70,1,{},[{"secret":"secret456","role":"backend"}],{"user-id":6}]``` there is a error returned: ```[3,{"message":"got invalid return type \"<class 'autobahn.wamp.types.CallResult'>\" from dynamic authenticator"},"wamp.error.authentication_failed"]```.

Is it possible to send additional informations in this step?

**Comment by oberstet** [comment]
https://github.com/crossbario/crossbarexamples/blob/master/authentication/advanced/authenticator.py#L78

**Comment by Paranaix** [comment]
@oberstet this has been implemented already? nice

**Comment by oberstet** [comment]
@Paranaix yep, it's implemented, and works for all dynamic authentication methods.

**Comment by oberstet** [comment]
On the client side, at least Autobahn on Python and JS works.
