### ISSUE TITLE
Consider screwing ujson completely

### ISSUE THREAD

**Issue by tautek** [crossbario/autobahn-python#611]
I'm looking for a way to disable ujson under *nix, specifically because I have issues with some messages in Crossbar that cause a max recursion error (dictionary with two lists of dictionaries approx 4000 in each list). While the message size or Crossbar's handling may be the root issue, temporarily I'd just like to be able to force Autobahn to use the standard json lib. I'm running Crossbar in Docker and uninstalling ujson doesn't seem to stop Crossbar from requiring it:

`FROM python:3.4.4`
`RUN pip install autobahn==0.12.1 && pip uninstall -y ujson && pip install crossbar[tls,msgpack,manhole,system]==0.12.1`

The only thing that works is commenting out the ujson import in autobahn/wamp/serializer.py.

Is there a better way currently? Would a PR to optionally disable ujson be worthwhile? Any thoughts on the best way to implement it?

Thanks.

**Comment by oberstet** [comment]
You can uninstall ujson *after* installing Crossbar.io. It'll then just use json from the Python standard library. You could also run under PyPy, in which case ujson is never installed nor used.

**Comment by tautek** [comment]
Thanks for the suggestions, I've decided to rollback to Crossbar 0.11.2 for now. I'll look at getting it running under PyPy later.

More of a discussion for Crossbar but since you're here.. uninstalling ujson after install doesn't work since commit https://github.com/crossbario/crossbar/commit/a73e662f9c3fe8d5f583cd876b13fe06447b4867 made it a base requirement. In the "crossbar" console script "load_entry_point" will still check install_requires and throw a pkg_resources.DistributionNotFound exception when it finds ujson is missing.

**Comment by oberstet** [comment]
Ok, I see. Thanks for reporting this issue. We should think about removing ujson completely, as it seems the implementation quality is dubious ..

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-python/pull/663
