### ISSUE TITLE
Release numbering policy and 1.0

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#623]
We need a release numbering policy - an objective one. As far as that is possible. And we should go for a "1.0" now.

The Autobahn libraries are not "finished", right. The API isn't frozen. There are still gaps feature wise. But:
- the WAMP protocol on the wire and its lower levels of implementation have been stable for long now
- the original primary goals for these libraries have been largely met already
- we have a pretty solid track record regarding stability/security
- other software depends on Autobahn
- these libraries are actually used in production

Semver is a popular choice for libraries in particular. So this is one obvious option for Autobahn. Each AutobahnXXX would run on its own semver counter.

Semver tries to communicate breaking changes in releases by major version bumps. Ideally, from comparing 2 semvers, a user could infere the likelihood something breaks. This is a useful information for a library user.

However, if each AutobahnXXX runs on its own counter (and that is the only way I can see semver work here), then the counters for major version might diverge - drastically, depending on semver strictness and progress in the different XXXs.

The semvers don't have meaning across the different AutobahnXXXs (and Crossbar.io): do these versions work together? Are they "from the same time period" (and hence likely tested together)?

Interestingly, this is less about API breakage (as semver is), but about functional and integration breakage.

If we wanted to communicate that, a calver scheme, run across both Autobahns and Crossbar.io could allow us to communicate that: "yeah, all versions 16.04 of Autobahn and Crossbar.io have been tested together." Of course, likely Autobahn 16.10 will operate with Crossbar.io 16.04, and NN.MM should generally work with XX.ZZ, but there is a limit to what we can test/guarantee for such combinations. And then there are missing features that need coordinated implementation: eg call canceling. To be able to cancel a call from AB JS, running through CB to a calle in AB Py requires touching code in all 3! And how do we communicate that a user needs certain versions of all 3?

Just saying: "if you take 16.04 of all, you are fine" seems way easier than "wait, let me see, that would be AB Py 3.4.2 with AB JS 1.2.10 and CB 2.0.12!" wtf?

**Comment by meejah** [comment]
The calendar-versioning also seems to match more closely how releases currently happen: at least AB Py and CB usually get released together, and it's usually just "whatever is on master currently".

I guess the only thing calver makes "hard" is if you want to have an "old" version and backport changes to it (e.g. a "1.X.Y" line, and a "2.Z.Q" line) but AB/CB doesn't do that either (and I guess nothing stops you from making a "14.x" release in 2017 if there's a bugfix worth back-porting for some reason, e.g. 17.x changed the API).

Personally, I kind of like the variant of calver that uses the year for the first number, but just increases the second number. E.g. 16.1.0 is the first release of 2016, no matter if it's in January or not, 16.2.0 is the second release in 2016 etc. Not sure if one needs all three versions or not, but I guess that lets you do a "16.1.1" if there's a minor mistake in the 16.1.0 release :/

**Comment by oberstet** [comment]
we have moved to calendar versioning some time ago
