### ISSUE TITLE
Compressed data become corrected

### ISSUE THREAD

**Issue by sarathak** [crossbario/autobahn-python#627]
hi 

i created and broadcasting web socket with twisted . i also added compression . some time all received message become corrected(only some session), 
once started this issue all compressed message on a session will become corrected, no problem in uncompressed message broadcast
if i make a refresh will be ok for long time

**Comment by oberstet** [comment]
what are you talking about? this is an issue tracker.

**Comment by sarathak** [comment]
![image](https://cloud.githubusercontent.com/assets/3303507/14390614/9812df42-fdd5-11e5-924e-8850d200f80d.png)
