### ISSUE TITLE
wamp.uri.Pattern.match always returns True for EXACT URIs

### ISSUE THREAD

**Issue by deceze** [crossbario/autobahn-python#634]
```python
def match(self, uri):
    ...
    if self._type == Pattern.URI_TYPE_EXACT:
        return args, kwargs
```

I'd expect [this method](https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/uri.py#L236) to raise an exception or return `False` on non-matching URIs (I'm using this class as a helper for authentication checking), yet it always unconditionally returns a truthy value for any `EXACT` URI, which is very unexpected. Could perhaps use some rethinking.

**Comment by oberstet** [comment]
This class isn't part of the public API - its semantics are driven by our internal needs
