### ISSUE TITLE
Use batching/chunking timers

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#642]
There are multiple places within Autobahn (at the WebSocket and at the WAMP level) where we use timers sticked to protocol instances.

When running massive numbers of connections, this can lead to significant CPU load.

Since these timers don't need to be precise, and hence we can conserve CPU by batching timeouts into buckets (and process timeout callbacks within a bucket in chunks).

The underlying functionality will be in `txaio`: https://github.com/crossbario/txaio/issues/66

Once that is done, we should use them here.

**Comment by oberstet** [comment]
See:

* https://github.com/crossbario/crossbar/issues/722
* https://github.com/crossbario/txaio/issues/66

**Comment by meejah** [comment]
With the changes from https://github.com/crossbario/txaio/pull/67 I hacked together some quick numbers after replacing all the ``call_later``s in websocket stuff to batched timeouts.

This is just a local test on an 8-core machine, ramping up to 20k do-nothing websocket connections (in one client process) with 10s auto-pings and 60s ping-timeouts enabled and then idling for a while. I'm showing the CPU usage of the server process as grok'd by ``collectl`` every second (there's almost no green impulses in the latter part of the graph because the CPU usage is very low).

Conclusion: well worth the batching optimization. I will do a few more tests tomorrow playing with some of the batching parameters (this was 5s bucket size, chunked at 1000 per yield). The high CPU usage on the left is during the ramp-up phase...

![batching](https://cloud.githubusercontent.com/assets/145599/14733893/a0431c42-0823-11e6-86dd-34a8faa5b526.png)

**Comment by oberstet** [comment]
@meejah 

> Conclusion: well worth the batching optimization.

Coool!!

We should really do that in AB.

We might also use this to implement write coalescing: https://github.com/crossbario/autobahn-python/compare/master...oberstet:write_coalescing

**Comment by oberstet** [comment]
rgd the value of write coalescing, this is two-fold:

* it reduces the number of syscalls and CPU load (tradeoffs is increased latency vs throughput)
* it reduces the wire level traffic when run over TLS - we should make it such that writes to the underlying Twisted stream protocol only does 1 write

Rgd the latter: http://tavendo.com/blog/post/dissecting-websocket-overhead/

**Comment by DZabavchik** [comment]
Night and day.  Looks more like 20x+ improvement, way better than what I got.

**Comment by meejah** [comment]
Well, it's pretty "burst-y" on CPU usage still, and that's just raw per-second values (e.g. no running average etc). Nevertheless, yes quite useful!

Thanks to @DZabavchik for originally noticing and reporting this!

**Comment by DZabavchik** [comment]
Do you blast to all connected only once per ping interval (even if it is in chunks, yielding to process other stuff)?.  I.e. only once a minute if ping interval is 60s, blast is going out to all 20k?  Or is it being spread out to slots so every second only 1/60 of 20k (~333) clients get their pings?

**Comment by oberstet** [comment]
@meejah 

Thiunking loudly .. there are now multiple knobs:

* 10s auto-pings
* 60s ping-timeouts
* 5s bucket size
* chunked at 1000 per yield

What happens when you decrease the bucket size to 200ms (chunksize divided then by 5s/200ms=25 => 1000/25 = 40) and/or add a random jitter to the scheduled pings (call_later(5 + random_value))?

Introducing random jitter is does good things sometimes.

Right now, if all clients initially connecting would connect at the very same time (which they don't, obvisouly, because of rampup time), this gives still waves of pings.

Or let the clients gradually connect over some minutes, so their inital connection timepoint crosses multiple buckets/ping periods.

**Comment by DZabavchik** [comment]
Timeouts question.  Is 10s ping interval with 60s ping timeout realistic?    If we are pinging a connected websocket we expect it respond to first ping before we ping it next time.  IMHO ping timeout should be less than ping interval

**Comment by meejah** [comment]
@DZabavchik yes, probably. I just made the timeout "huge" to ensure that I didn't timeout any connections because I wanted the "steady-state" period to have a lot of connections "doing pings". And, if I was ramping up "too fast" some connections would get nuked.

**Comment by meejah** [comment]
@DZabavchik yes, it just blasts out all pings "at once" (modulo yielding to the reactor). That is: I don't try to spread it out over the interval, which might work better.

I guess I'm presuming that the absolute amount of ping-traffic will be low compared to the rest, and so some bursty-ness in the pings is okay -- but maybe that's a bad presumption. Spreading it out over the bucket-size is probably "better" anyway.

**Comment by DZabavchik** [comment]
While pacing and trying to decide how to do it better, the first thought was to prevent spikes/bursts (same concern that @oberstet raised).  The other concerns are:
- if websocket connects 1ms prior to ping burst, it will get its ping right after connecting - not that big of a deal
- If bursts take substantial time, scheduling next burst after current one ends will result in red-shift - intervals will be extended beyond specified ping interval

So when assigning ping-bucket to connected websocket I used previous to current (current - 1), so newly connected socket will get ping almost exactly N seconds after connecting (N=ping interval).

**Comment by meejah** [comment]
The start of a burst is scheduled in absolute time.

**Comment by oberstet** [comment]
@DZabavchik rgd what are "realistic" values for ping period.

This can't be answered in general, because it depends on what you want to achieve. In my experience, there are three main reasons for doing ping/pong:

1. fast detection of connection loss
2. keeping connections alive
3. keeping connections snappy

(1) is about full connection loss (mainly mobile these days)
(2) is about intermediaries (NATs, firewalls, proxies) timing out connections
(3) is about keeping the link and endpoint states in a mode where messages are transmitted with low latency

The last one in particular:

* http://lists.w3.org/Archives/Public/ietf-http-wg/2012JanMar/1083.html
* https://eggert.org/students/chemmagate-thesis.pdf
* http://www.stevesouders.com/blog/2011/09/21/making-a-mobile-connection/

Note, that for (3) on HSPA, it's not enough to have a quite short ping period. You also need sufficient traffic.

In my experiments, I had to use a ping period of 200 ms (!) with a payload of at least 50 octets (effective bandwith 4kb/s) to keep my mobile (on HSPA) in the most responsive state (HSPA DCH).

However, this will not only depend on the wireless standard (HSPA vs LTE), but also depend on the specific carrier network.

The mobile network of a carrier do have state machines with carrier specific configuration: http://stevesouders.com/images/rrc-load-times.png

**Comment by oberstet** [comment]
Because of above, a "full solution" for ping/pong would need to tweak its parameters per connection class: connections coming in from HSPA mobiles need other parameters than connections coming in from residential ADSL and different from cable different from people directly hooked on backhauls or even core network.

**Comment by meejah** [comment]
Okay, so here are some more comparisons. There was also a bug meaning that in the first graph we weren't actually doing any pings at all -- still, good benefit from the buckets. Looks like smaller buckets, with less-per-chunk (and spreading it out over the bucket-duration) gets the best performance.

![batchedtimers](https://cloud.githubusercontent.com/assets/145599/14759698/e6819600-08e8-11e6-8ab7-f262c25e8607.png)

**Comment by oberstet** [comment]
@meejah Very interesting!

Here is what comes to my mind to look deeper:

* breakdown CPU into user/system (http://netdata.firehol.org/ - https://github.com/firehol/netdata/wiki/Installation)
* measure syscall rate (http://linux.die.net/man/1/strace or systemtap)
* measure interrupt rate (is that loopback?)
* what's the JITted code doing? (vmprof, Linux perf)

To establish a lower bound rgd CPU load, we could measure this: have a plain Twisted TCP server that sends out 1 octet pseudo-pings to the 20k connected clients.

My expectation: it'll be mostly system CPU and roughly scale with effective syscall rate

syscall rate is the ultimate barrier with networking code when using regular Posix socket API. There is no way of getting beyond that barrier (as of now, as far as I know) without switching to a radical different design: kernel-bypass networking.

The reason is the inherit limitation of the Posix socket API design: you can't write (different) bytes to different sockets in one syscall.

**Comment by oberstet** [comment]
rgd kernel-bypass (totally OT or over the top rgd what we discuss here - but this gives me thrills! hard-core stuff;): this was pioneered by FreeBSD (of course, who else?;) within the netmap framework. This isn't the only one, and Linux has stuff too.

This stuff is also approaching real-world deployment: here is Cloudflare talking https://blog.cloudflare.com/kernel-bypass/

Wow. It made it to BBC / theregister even: http://www.theregister.co.uk/2015/10/12/linux_networking_api_showing_its_age/

**Comment by meejah** [comment]
BTW, all the above tests are CPython2 over loopback on a single machine.

"For Comparison Purposes Only" ;)

**Comment by meejah** [comment]
Okay, here are some numbers with PyPy, with the 200ms and 1000/chunk values used in the #654 PR.

![batchedtimers-pypy-30s](https://cloud.githubusercontent.com/assets/145599/14909916/f4b90f5c-0da5-11e6-826f-d196ace4a4bf.png)

**Comment by oberstet** [comment]
@meejah awesome!! really cool.

**Comment by meejah** [comment]
Out of interest, here's a graph of the raw syscall rate (from ``strace`` with post-processing, just counting total number per second) for runs with no batched timer, and with the 200ms/1000-chunk size batched timer (for all timeouts, as per #660).
![pypy_batched_all](https://cloud.githubusercontent.com/assets/145599/14937444/97760758-0ec4-11e6-9fbb-c5a5f590b248.png)

**Comment by oberstet** [comment]
@meejah very nice! the graph looks good. With 200ms/1000 chunksize, that means 5000 socket writes/sec. That is 5000 syscalls alone. The real syscall rate is more like 12k/sec, so there are more socket writes. Factor 12k/5k .. roughly 2.5. This is less than the 4 syscalls I once tracked down here: https://github.com/oberstet/scratchbox/blob/master/docs/misc/twisted.md

> rgd the PR .. could you rebase to master please? Can't merge ..

**Comment by oberstet** [comment]
@meejah thanks! merged.

fixed on HEAD now via:

* https://github.com/crossbario/autobahn-python/pull/654
* https://github.com/crossbario/autobahn-python/pull/660

**Comment by oberstet** [comment]
@meejah alright, all of this is released in https://pypi.python.org/pypi/autobahn/0.14.0
