### ISSUE TITLE
acknowledgement option for autobahn.twisted.wamp.ApplicationSession.publish doesn't work

### ISSUE THREAD

**Issue by Budulianin** [crossbario/autobahn-python#649]
I've crossbar with some "components":

```
 {
    "type": "class",
    "classname": "application.Application",
    "realm": "general",
    "role": "backend"
 }

```

application.Application - subclass from autobahn.twisted.wamp.ApplicationSession
I'm trying publish message through publish method with acknowledgement = True

    @defer.inlineCallbacks
    def publish_message_to_client(self, user_id, message, options=PublishOptions(acknowledge=True)):
        yield self.publish(WAMP_URI_TEMPLATE.format(user_id), message, options=options)

but I always receive autobahn.wamp.request.Publication instance. Whenever was connected subscriber or not. However docs say that _**"If the publication fails the Deferred/Future will reject with an instance of autobahn.wamp.exception.ApplicationError."**_
[docs](http://autobahn.ws/python/reference/autobahn.wamp.html?highlight=acknowledgement#autobahn.wamp.interfaces.IApplicationSession.publish)

What is mean **_"publication fails"_** ?
Subscriber wasn't connected to crossbar and wasn't received message thus publication was fails and publish method must return autobahn.wamp.exception.ApplicationError instance.

Can you explain this behavior?

**Comment by oberstet** [comment]
Please ask questions on the mailing list https://groups.google.com/forum/#!forum/autobahnws

This is an issue tracker

**Comment by Budulianin** [comment]
I asked question, but nobody gave me answer. Can you find some time for answer the [question](https://groups.google.com/forum/#!topic/autobahnws/pOkXIf24twg)?
