### ISSUE TITLE
Allow for custom logger to be passed to ApplicationSession

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/autobahn-python#655]
ApplicationSession does not currently allow a custom logger to be passed to the logger instance that txaio uses. It would be nice to allow a custom logger to be passed based on the standard lib logging module. This would allow for better control of a log file for administration, and not duplicate entry with no way to stop it:

``` text
[04-28-2016 15:58:32.589 UTC] PID: 1659 Mod: timer Line: 16 INFO: build_json_tree sort finished in: 0.002349 secs
2016-04-28T11:58:32 build_json_tree sort finished in: 0.002349 secs
``` 

``` python
class ApplicationSession(BaseSession):
    """
    WAMP endpoint session.
    """

    log = txaio.make_logger() or self.config.logger  # NOTE: Or something like this

    def __init__(self, config=None):
        """
        Constructor.
        """
        BaseSession.__init__(self)
        self.config = config or types.ComponentConfig(realm=u"default")
```

``` python
class SessionComponent(ApplicationSession):
    def __init__(self, config=None, hostname=None, logger=None):
        ApplicationSession.__init__(self, config, logger)
```

**Comment by oberstet** [comment]
a) You can set a logger in `__init__`
b) `ComponentConfig` does not have a `logger` attribute - and it shouldn't

**Comment by meejah** [comment]
Can you describe how you're using logging, and what's not working? If you're using ApplicationRunner, that's important too.

You shouldn't need to change the ``self.log`` instance (and in fact, it probably won't work if you do switch it to be a stdlib logging instance, as it's doing structured logging and expecting txaio's API -- but, it should inter-op with stdlib).

**Comment by singlecheeze** [comment]
Hi @meejah. I am using ApplicationRunner. The problem I am facing is that on registration, I am getting two log entries. One is expected as I am writing it using my std lib logger, the other seems to be a new addition with autobahn 13 on registration. See Below...

``` python
from colorlog import ColoredFormatter

class SessionComponent(ApplicationSession):
    def __init__(self, config=None, hostname=None, logger=None):
        ApplicationSession.__init__(self, config)
        self.loop = asyncio.get_event_loop()
        self.hostname = hostname
        self.logger = logger

@asyncio.coroutine
    def onJoin(self, details):
       try:
            yield from self.register(self.receive_work,
                                     'mono.backend.receive_work',
                                     options=RegisterOptions(invoke='roundrobin'))
            self.logger.info("mono.backend.receive_work registered inline")

if __name__ == '__main__':
     class NoReplacementCharFilter(logging.Filter):
        def filter(self, record):
            return not record.getMessage().startswith("Some characters could not be decoded")

    # NOTE: Setup logging with simple StreamHandler (output to console) for now
    default_logger = logging.getLogger()
    default_logger.setLevel(logging.INFO)

    # NOTE: Create the logging file handler stream = console
    sh = logging.StreamHandler()
    sh.addFilter(NoReplacementCharFilter("UnicodeDammit"))
    # NOTE: Create the logging formatter (using additional lib for color
    # NOTE: For PyCharm see https://www.jetbrains.com/pycharm/help/configuring-color-scheme-for-consoles.html
    # NOTE: File> Settings> Editor> Colors & Fonts> Save As...> Console> Error Output (Deselect Foreground)
    # NOTE: http://www.python-course.eu/python3_formatted_output.php
    log_formatter = ColoredFormatter("{log_color}[{asctime} UTC] PID: {process} Mod: {module} Line: {lineno} {levelname}: {message}", style="{")

    log_formatter.converter = time.gmtime
    log_formatter.default_time_format = "%m-%d-%Y %H:%M:%S"
    log_formatter.default_msec_format = "%s.%03d"

    sh.setFormatter(log_formatter)
    # NOTE: Add handlers to logger object
    default_logger.addHandler(sh)

    runner = ApplicationRunner(url="ws://localhost/ws", realm="realm1")
    runner.run(SessionComponent(config=None, hostname=ww_hostname, logger=default_logger))
```

My little timer context manager:
``` python
import time
import logging
from contextlib import contextmanager


# http://stackoverflow.com/questions/5478351/python-time-measure-function
@contextmanager
def run_timer(pre_text, logger=None):
    if not logger:
        logger = logging.getLogger()

    start_time = time.time()
    yield
    elapsed_time = time.time() - start_time
    logger.info("{0} finished in: {1:.6f} secs".format(pre_text, elapsed_time))
```

Log entries:
``` text
[04-29-2016 15:39:12.395 UTC] PID: 2051 Mod: backend Line: 1604 INFO: mono.backend.receive_work registered inline
2016-04-29T11:39:12 mono.backend.receive_work registered inline
```

Any time I use the logger instance I now get two log entries, either on registration OR using the timer context manager like below:

``` python
@asyncio.coroutine
    def build_json_tree(self, case, light, sort_order):
        with run_timer("build_json_tree"):
            pass
```

**Comment by singlecheeze** [comment]
Also this with AutobahnPython 13.1:

``` text
[04-29-2016 15:51:32.935 UTC] PID: 5871 Mod: aio Line: 123 CRITICAL: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/autobahn/asyncio/wamp.py", line 123, in create
    session = make(cfg)
TypeError: 'SessionComponent' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/autobahn/wamp/websocket.py", line 60, in onOpen
    self._session = self.factory._factory()
  File "/usr/lib/python3.5/site-packages/autobahn/asyncio/wamp.py", line 125, in create
    self.log.failure("App session could not be created! ")
AttributeError: 'ApplicationRunner' object has no attribute 'log'
```

**Comment by meejah** [comment]
@singlecheeze Thanks for the code-snippet!

Obviously your last comment is a bug.

To clarify the logging behavior you're hoping for: you wish to have your own stdlib logging formatting, and have it format events from your own loggers and from txaio/autobahn logging, right?

**Comment by singlecheeze** [comment]
Not sure. I'm ok with how it used to work, where autobahn had it's own logging and that was mutually exclusive of any application logging. See, I use Supervisord to keep my "wamp workers" up and running. I set logging on supervisor to redirect std err and std out to a file from the autobahn worker. That way I have all of my worker log messages in the same place as you can see I am printing to std out in my code, but supervisor is catching that and logging to a file.

I think this will be how most people will do it now that daemontools is getting old and there is very active dev on supervisord.

**Comment by singlecheeze** [comment]
Just for fun my supervisord "wamp worker" config:

``` text

[program:ww_backend]
command=python3.5 -u /home/dave/ww1/backend/backend.py              ; the program (relative uses PATH, can take args)
process_name=wamp_worker_%(process_num)s ; process_name expr (default %(program_name)s)
;numprocs=1                    ; number of processes copies to start (def 1)
directory=/home/dave/ww1/backend/                ; directory to cwd to before exec (def no cwd)
;umask=022                     ; umask for process (default None)
;priority=999                  ; the relative start priority (default 999)
;autostart=true                ; start at supervisord start (default: true)
;startsecs=1                   ; # of secs prog must stay up to be running (def. 1)
;startretries=3                ; max # of serial start failures when starting (default 3)
;autorestart=unexpected        ; when to restart if exited after running (def: unexpected)
;exitcodes=0,2                 ; 'expected' exit codes used with autorestart (default 0,2)
;stopsignal=QUIT               ; signal used to kill process (default TERM)
;stopwaitsecs=10               ; max num secs to wait b4 SIGKILL (default 10)
;stopasgroup=false             ; send stop signal to the UNIX process group (default false)
;killasgroup=false             ; SIGKILL the UNIX process group (def false)
user=dave                   ; setuid to this UNIX account to run the program
redirect_stderr=true          ; redirect proc stderr to stdout (default false)
stdout_logfile=/home/dave/ww1/backend/log.txt        ; stdout log path, NONE for none; default AUTO
;stdout_logfile_maxbytes=1MB   ; max # logfile bytes b4 rotation (default 50MB)
;stdout_logfile_backups=10     ; # of stdout logfile backups (default 10)
;stdout_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
;stdout_events_enabled=false   ; emit events on stdout writes (default false)
;stderr_logfile=/a/path        ; stderr log path, NONE for none; default AUTO
;stderr_logfile_maxbytes=1MB   ; max # logfile bytes b4 rotation (default 50MB)
;stderr_logfile_backups=10     ; # of stderr logfile backups (default 10)
;stderr_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
;stderr_events_enabled=false   ; emit events on stderr writes (default false)
environment=HOME="/home/dave"       ; process environment additions (def no adds)
;serverurl=AUTO                ; override serverurl computation (childutils)
```

**Comment by singlecheeze** [comment]
@meejah also FYI, I also just did a pip for autobahn and it looks like there might be a version dependancy that is miss matched for txaio? Not sure why this didn't update yesterday when I updated autobahn just FYI....

``` text
Requirement already up-to-date: autobahn in /usr/lib/python3.5/site-packages
Requirement already up-to-date: six>=1.10.0 in /usr/lib/python3.5/site-packages (from autobahn)
Collecting txaio>=2.3.0 (from autobahn)
  Downloading txaio-2.5.1-py2.py3-none-any.whl
Installing collected packages: txaio
  Found existing installation: txaio 2.4.0
    Uninstalling txaio-2.4.0:
      Successfully uninstalled txaio-2.4.0
Successfully installed txaio-2.5.1
```

**Comment by meejah** [comment]
txaio 2.5.1 just came out last night

**Comment by singlecheeze** [comment]
Ah ;)

**Comment by singlecheeze** [comment]
Any idea if there is a merge recently to fix the log bug?

**Comment by oberstet** [comment]
No

**Comment by singlecheeze** [comment]
I don't understand. Why do you not want to track this bug?

**Comment by scrawl** [comment]
Hello, I have the same issue. Why was the report closed? Is there a fix in the pipeline?

This is how I set up my logging:

<pre>
logformat = '[%(asctime)s] %(message)s'
dateformat = "%c"
logging.basicConfig(format=logformat, datefmt=dateformat, filename="logfile", level=logging.INFO)

ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.INFO)
formatter = logging.Formatter(logformat, dateformat)
ch.setFormatter(formatter)
logging.getLogger().addHandler(ch)

logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("requests").setLevel(logging.WARNING)
</pre>

It seems that Autobahn adds a second log handler, causing all log messages to appear in the output twice. (The first message is using the format I specified, the second one isn't)

I'm using Autobahn 0.15.0 installed with pip3.

**Comment by oberstet** [comment]
Do you call `txaio.start_logging()`? Because http://txaio.readthedocs.io/en/latest/programming-guide.html#starting-logging-yourself - so this should work for Autobahn too https://github.com/crossbario/txaio/blob/master/examples/log_interop_stdlib.py

**Comment by scrawl** [comment]
I don't call ```txaio.start_logging()```. I don't use txaio in my own code.

**Comment by oberstet** [comment]
Can you post a complete example reproducing the issue you see?

**Comment by scrawl** [comment]
Adding ```txaio.start_logging()``` to my program didn't make a difference (aside from the fact that the double logging issue is now present as soon as the program is started, when previously it would happen as soon as I created the autobahn ApplicationSession).

Sure, I will make an example.

**Comment by oberstet** [comment]
Thanks!

In fact, there are only these places inside Autobahn:

```
oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ find autobahn/ -name "*.py" -exec grep -Hi "start_logging" {} \;
autobahn/wamp/test/test_runner.py:        @patch('txaio.start_logging')
autobahn/asyncio/wamp.py:        txaio.start_logging(level='info')
autobahn/twisted/component.py:        # txaio.start_logging(level='debug')
autobahn/twisted/wamp.py:            txaio.start_logging(level='info')
```

Eg if you let `ApplicationRunner` start the reactor for you, it'll also start logging: see [here](https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/wamp.py#L156)

**Comment by scrawl** [comment]
Example:

<pre>
import logging, txaio, sys

txaio.use_asyncio()

logging.basicConfig(filename="logfile", level=logging.INFO)
ch = logging.StreamHandler(sys.stdout)
logging.getLogger().addHandler(ch)

txaio.start_logging(level='debug')

logging.warning("test")

# output:
# test
# 2016-07-28T22:23:13 test
</pre>

The above log configuration should log messages to the logfile and to stdout (and does so correctly without txaio being involved). With txaio, the messages to stdout are now duplicated. The log <i>file</i> does not show duplicated messages though.

**Comment by scrawl** [comment]
> Eg if you let ApplicationRunner start the reactor for you, it'll also start logging: see here

Interesting, so could I workaround the txaio.start_logging being called by starting up the reactor manually? How do I do that?

I am using asyncio not twisted, btw.

**Comment by oberstet** [comment]
One issue at least is that the `ApplicationRunner.run` variant for asyncio currently lacks a parameter corresponding to `start_reactor` as the Twisted version has. It'll always start logging and always start a loop: https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/wamp.py#L152

**Comment by scrawl** [comment]
Ok, that helps. I can make my own version of the ApplicationRunner that doesn't start logging.

There is still a bug in txaio though, right?

**Comment by oberstet** [comment]
No, I don't think so: you start logging twice in your example. First, by attaching a logger to stdout via `logging.getHandler().addHandler(ch)`, and then via `txaio.start_logging()`. You should only do one of both.

Eg check this:

```console
(cpy2711_11) oberstet@thinkpad-t430s:~/scm/crossbario/txaio/examples$ python log_interop_twisted.py 
logging not started
Observe: {'log_io': u'logging started; calling library', 'log_level': <LogLevel=info>, 'log_logger': <Logger 'stdout'>, 'log_format': u'{log_io}', 'log_time': 1469739016.08049, 'log_source': None, 'log_namespace': 'stdout'}
Observe: {'log_namespace': '__main__.Library', 'log_level': <LogLevel=info>, 'log_logger': <Logger '__main__.Library'>, 'log_time': 1469739016.080548, 'foo': 'bar', 'log_source': None, 'log_format': 'info log from library foo={foo}'}
Observe: {'log_io': u'finished library call', 'log_level': <LogLevel=info>, 'log_logger': <Logger 'stdout'>, 'log_format': u'{log_io}', 'log_time': 1469739016.080593, 'log_source': None, 'log_namespace': 'stdout'}
(cpy2711_11) oberstet@thinkpad-t430s:~/scm/crossbario/txaio/examples$ python log_interop_stdlib.py 
logging not started
INFO:root:info-level log from my program: 42
logging started; calling library
INFO:root:info log from library foo=bar
ERROR:root:An error in the library num=42
finished library call
(cpy2711_11) oberstet@thinkpad-t430s:~/scm/crossbario/txaio/examples$ 
```

---

The issue is the missing `start_loop` parameter to `autobahn.asyncio.wamp.ApplicationRunner.run` ..

**Comment by oberstet** [comment]
@scrawl see https://github.com/crossbario/autobahn-python/issues/721

**Comment by scrawl** [comment]
In my opinion, the default for start_log should be off. It's not nice for third party libraries to mess with my own log config that previously worked. :(

Would it make sense for txaio to log to existing handlers (i.e. simple ```logging.info()``` call to a logger), instead of creating its own handler? AFAIK, that's how most other python libraries handle logging. In essence, txaio.start_logging should create a logger instead of creating a handler.

**Comment by meejah** [comment]
@scrawl if you don't ever call `txaio.start_logging()` then yes, that's precisely what happens (except if you're using Twisted it logs via the Twisted loggers).
