### ISSUE TITLE
Failing Assert statements should provide additional information about cause

### ISSUE THREAD

**Issue by tburney** [crossbario/autobahn-python#673]
https://github.com/crossbario/autobahn-python/blob/8d034622e8f6de88a619cb7dd59f57701708575d/autobahn/wamp/types.py#L127-L132

When a failure happens in these assert statements due to a mistake in custom authentication code, the cause of the failure is obscured by the lack of information regarding the reason the assertion failed.

Some additional trace/debug logging information would be very useful.

**Comment by oberstet** [comment]
https://github.com/crossbario/autobahn-python/issues/99
