### ISSUE TITLE
WebsocketClientProtocol: Expose HTTP status codes

### ISSUE THREAD

**Issue by rbmj** [crossbario/autobahn-python#696]
Currently, if a server returns any status code that is not 101 the client dies silently, with no capability for the application to present this error information to the user.  At the very least, if the server returns 301 or 401 the application should have some way of detecting the failed handshake and presenting the user with "Authorization Required," rather than just exiting quietly.  Perhaps there could be a `onBadHTTPStatus()` function or something?

Most of the errors that cause a `failHandshake()` are serious errors, but HTTP status codes tend to be for errors that can be corrected.  Being able to display a 404 after a mistyped URL could be helpful, for example.

It seems like the only way to detect this now is to override the `failHandshake()` method and parse the error strings passed to it, which is clearly a rather brittle design.

**Comment by oberstet** [comment]
A WebSocket opening handshake can fail for many reasons, and we don't map these into a consolidated list or similar. Your best bet is indeed overriding `WebSocketClientProtocol.failHandshake(reason)` (and possibly `failProxyConnect`), and simply present `reason` to users. Eg a non-101 HTTP response status code will pop up from here https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L3618
