### ISSUE TITLE
An example with TLS/SSL?

### ISSUE THREAD

**Issue by sscirrus** [crossbario/autobahn-python#697]
Hi guys,

Simple version: how can I add WSS to [serial2ws](https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/wamp/app/serial2ws/serial2ws.py)? 

-------

I'd like to know how to adapt the serial2ws example for an SSL connection.
I'm changing in serial2ws.py:

    router = args.router or 'ws://localhost:8080'
    to
    router = args.router or 'wss://localhost:8080'

And on the website JS:

    connection = new autobahn.Connection({
      url: (document.location.protocol === "http:" ? "ws:" : "wss:") + "//" + ip + ":" + port,
      realm: 'realm1',
    })

But, when I try to connect, it fails with:

    WebSocket connection to 'wss://192.168.0.12:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

The Python server logs:

```
2016-06-30 16:52:57-0400 [-] Log opened.
2016-06-30 16:52:57-0400 [-] Using Twisted reactor <class
'twisted.internet.epollreactor.EPollReactor'>
2016-06-30 16:52:59-0400 [-] WampWebSocketServerFactory starting on 8080
2016-06-30 16:52:59-0400 [-] Starting factory <autobahn.twisted.websocket.WampWebSocketServerFactory instance at 0x76669dc8>
2016-06-30 16:53:00-0400 [-] Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory instance at 0x766112b0>
2016-06-30 16:53:05-0400 [WampWebSocketClientProtocol (TLSMemoryBIOProtocol),client] Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory instance at 0x766112b0>
```

**Comment by meejah** [comment]
@scirrus are you using a "real" certificate, or e.g. a self-signed one?

**Comment by sscirrus** [comment]
@meejah I'm using a certificate created via Lets Encrypt. I don't know what that would qualify as.

**Comment by sscirrus** [comment]
I have another question about this actually - if doing this for an IoT device, does this mean we have to create new certificates and load them on every device every 3-12 months? That isn't doable for me - my devices are out in the field and we can't get to them that easily.

**Comment by meejah** [comment]
@sscirrus A LetsEncrypt certificate counts as "real", yes (by which I mean: will be trusted by most browsers).

The reason I asked is because out-of-the-box no client is going to trust a connection to a server with a self-signed certificate. With a LetsEncrypt cert, although you'll have to replace it on the server every 3 months the clients shouldn't need an upgrade until LetsEncrypt root certificate is compromised ;)

Also, you should be upgrading the clients' OS regularly, which will pull in any certificate-bundle changes on most distributions.

**Comment by sscirrus** [comment]
@meejah I'm sorry I let this drop for so long - I don't know if your comments have helped me with the original question. I'm still looking to get a stable connection using TLS and my error message is the same.
