### ISSUE TITLE
auto_ping_interval / auto_ping_timeout

### ISSUE THREAD

**Issue by ossnoser** [crossbario/autobahn-python#702]
Hello,
   I'm facing some problems with auto_ping parameters.
 In my application crossbar is running on a docker container and the apps are running on two raspberrypi (Autobahn/Twisted/Python).

When I unplug ethernet cable on a raspberrypi the application stops and when I plug the cable the application continue to comunicate and run as if nothing had happened.

I'm running crossbar 0.13.2, Twisted 15.5.0 and Autobhann 0.12.1.

Crossbar config attached.
[config_json.txt](https://github.com/crossbario/autobahn-python/files/353995/config_json.txt)

**Comment by mattcorona84** [comment]
Hi everybody,
Same problem here...
My raspberrypi is connected to a server (in wich is running crossbar). When I unplug the ethernet  cable the program on raspberrypi freeze and restart when i plug again the cable (even after a long timeout...).
I do not use docker for my application.
I've used the settings suggested on crossbar website too, but with no success:
http://crossbar.io/docs/WebSocket-Options/#production-settings

{
   "type": "websocket",
   "endpoint": {
      "type": "tcp",
      "port": 8080
   },
   "url": "ws://myserver.com:8080",
   "options": {
      "enable_webstatus": false,
      "enable_hixie76": false,
      "max_frame_size": 1048576,
      "max_message_size": 1048576,
      "auto_fragment_size": 65536,
      "fail_by_drop": true,
      "open_handshake_timeout": 2500,
      "close_handshake_timeout": 1000,
      "auto_ping_interval": 10000,
      "auto_ping_timeout": 5000,
      "auto_ping_size": 4
   }
}

**Comment by oberstet** [comment]
> For general questions and dicussions, please use our mailing list (this is a bug tracker).

You need auto ping/pong initiated from both sides of a connection, so that each side can detect a lost connection on its own ..
