### ISSUE TITLE
includes non-free autobahn.min.js without source

### ISSUE THREAD

**Issue by thomasgoirand** [crossbario/autobahn-python#709]
Hi. I'm the person packaging autobahn-python in Debian (for its use by OpenStack).

The current version of autobahn-python includes autobahn.min.js without even providing its non-minified version. From a distribution perspective, this is a non-free blob and missing source code, just like for a C object file. Please replace the non-free autobahn.min.js by its non-minified free software counter-part autobahn.js (and eventually offer a way to compress it at build time).

**Comment by oberstet** [comment]
The Python package does not contain the file you mention.

**Comment by meejah** [comment]
Actually there's two examples that include it still: serial2ws and hello -- I think we can just delete the autobahn.min.js and have them reference the amazon-s3 one like all the other examples, right?

**Comment by meejah** [comment]
I updated the two examples in #710

**Comment by oberstet** [comment]
@meejah yeah, direct linking is best. then the whole repo shouldn't have a file being problematic rgd Debian packaging.

**Comment by oberstet** [comment]
this has been fixed
