### ISSUE TITLE
util._LazyHexFormatter() returns str in py2, bytes in py3

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/autobahn-python#715]
this results in `TypeError: __str__ returned non-string (type bytes)`

a simple fix that works for both py2 and 3 is to append .decode() as shown to ensure a string representation is returned for both versions.

```python
class _LazyHexFormatter(object):
    """
    This is used to avoid calling binascii.hexlify() on data given to
    log.debug() calls unless debug is active (for example). Like::

        self.log.debug(
            "Some data: {octets}",
            octets=_LazyHexFormatter(os.urandom(32)),
        )
    """
    __slots__ = ('obj',)

    def __init__(self, obj):
        self.obj = obj

    def __str__(self):
        return binascii.hexlify(self.obj).decode()
```

**Comment by oberstet** [comment]
ah, right.

actually, there is code dup here too : https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/util.py#L20

gonna fix both ..

**Comment by oberstet** [comment]
fixed on master
