### ISSUE TITLE
Consider replacing cbor with cbor2

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#722]
[cbor2](https://pypi.io/project/cbor2/) is a shiny new CBOR implementation made by :agronholm. We should consider moving to this - it seems shiny, and polished, and he is serious about quality and maintenance.

**Comment by oberstet** [comment]
One aspect we should look at is performance on PyPy - minor difference probably is fine . Here is some test code:

* https://github.com/oberstet/scratchbox/tree/master/python/serperf
* https://github.com/oberstet/scratchbox/tree/master/python/vmprof

**Comment by kamikaze** [comment]
so what?

**Comment by oberstet** [comment]
PRs are welcome!

**Comment by agronholm** [comment]
Do you still want this, even when cbor2 supports types that msgpack and json do not?

**Comment by oberstet** [comment]
Yes, I am still interested in moving to `cbor2`, because it is maintained, documented and supposed to be "more correct" - all that even when I don't use types that are supported by cbor2 but not json/msgpack. But that is user choice.

**Comment by oberstet** [comment]
performance on pypy is crucial though .. the tests I linked here https://github.com/crossbario/autobahn-python/issues/722#issuecomment-236041938 could help us _demonstrate_ any advantages `cbor2` might have here (rgd performance, GC pressure, ..)

**Comment by agronholm** [comment]
> Yes, I am still interested in moving to cbor2, because it is maintained, documented and supposed to be "more correct" - all that even when I don't use types that are supported by cbor2 but not json/msgpack. But that is user choice.

Really? I thought your stance was that all data arriving at the router must be serializable to JSON. Then why did we have a long, heated argument about this which then led to the development of the payload codec system? Wasn't this the very reason you requested a "JSON compatibility" mode for cbor2?

> performance on pypy is crucial though .. the tests I linked here #722 (comment) could help us demonstrate any advantages cbor2 might have here (rgd performance, GC pressure, ..)

`cbor2` is not faster than `cbor` although on PyPy it's close enough.

**Comment by oberstet** [comment]
> Really? I thought your stance was that all data arriving at the router must be serializable to JSON. 

This is still what I think: I would not use non-JSON-serializable payloads with WAMP in general (other than binary, which AutobahnJS supports over JSON), because this hurts the transparency that WAMP promises.

In Crossbar.io, we will have an option to enforce that in the router. In a way, JSON-serializability is a very mild form of payload validation. Upcoming, Crossbar.io will have more options for payload validation (against schemata, IDL) or even dynamic (custom user) payload validators.

> cbor2 is not faster than cbor although on PyPy it's close enough.

Maybe the best would be to support both, and use whatever is available. That way, eg in Autobahn/CPython based programs, I can still choose as a user to run `cbor`.

**Comment by oberstet** [comment]
AB now _can_ use both cbor and cbor2 - but cbor is the default, because it is 3x faster than cbor2

https://crossbario.com/docs/benchmarks/serialization/index.html

so: won't fix
