### ISSUE TITLE
encrypt KeyRing in cryptobox TypeError 

### ISSUE THREAD

**Issue by jflorimo** [crossbario/autobahn-python#735]
file cryptobox.py line 203 in the encrypt function:

line 203:

```
payload_ser = json.dumps(payload)
payload_encr = box.encrypt(payload_ser, nonce, encoder=Base64Encoder)
```

json.dumps returns a string but box.encrypt only accepts bytes 

just add encode() to correct the error:
`payload_ser = json.dumps(payload).encode()`

see #736 for one solution

**Comment by meejah** [comment]
Thanks for the report. This is under Python3?

**Comment by jflorimo** [comment]
yes under Python 3.5.2

**Comment by oberstet** [comment]
this is fixed for a long time https://github.com/crossbario/autobahn-python/blob/b8b9096deebb7e404404f7c7b3ed69aad0febc6b/autobahn/wamp/cryptobox.py#L227
