### ISSUE TITLE
import failure due to class-level txaio.make_logger()

### ISSUE THREAD

**Issue by petri** [crossbario/autobahn-python#740]
Is it really necessary to instantiate the ApplicationSession logger at class level (see https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L277)?

It is causing import failure of autobahn.wamp.protocol (if txaio.use_twisted/txaio.use_asyncio has not been called yet at import time).

**Comment by oberstet** [comment]
So what is the issue? You have to call txaio.use_twisted/use_asyncio before importing Autobahn stuff.

**Comment by petri** [comment]
Do you mean that should be done everywhere any autobahn stuff is imported? It does not look like that is widely advertised in the docs. I took a look at a few examples and they don't do that either.

Or maybe I misunderstood?

**Comment by oberstet** [comment]
This is a "best practice" WAMP client: https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/wamp/basic/client_using_apprunner.py

**Comment by meejah** [comment]
See also: http://txaio.readthedocs.io/en/latest/programming-guide.html#logging

**Comment by meejah** [comment]
@petri what is the import error you're seeing? To import the correct `ApplicationSession` class, the right `txaio.use_{twisted,asyncio}` method should already have been called.

**Comment by petri** [comment]
I don't understand. Taking a look at several examples and running them, I see that invoking txaio.use_{twisted,asyncio} is definitely not always required - at all.

**Comment by meejah** [comment]
So you shouldn't be importing `autobahn.protocol.ApplicationSession` (it's a base class), but instead import from one of the "framework-specific" classes (i.e. `autobahn.twisted.wamp.ApplicationSession` or `autobahn.twisted.asyncio.ApplicationSession`) and then the right `txaio.use_*()` call should already have been made properly.

**Comment by petri** [comment]
Ah, thanks, got it now.

**Comment by meejah** [comment]
@petri do you know which docs could have made this more-clear? I guess perhaps all of `protocol` should maybe be in a `_protocol` package instead to make it's "internal" nature more obvious?

**Comment by petri** [comment]
I don't know. I don't remember actually using `protocol` directly, I just tracked the import error down there. Which happened when I was taking first steps writing a custom ApplicationRunner.
