### ISSUE TITLE
AttributeError raised in except block when creating the session object from ApplicationRunner fails

### ISSUE THREAD

**Issue by glenfant** [crossbario/autobahn-python#746]
When creating the session object from ApplicationRunner fails, the real issue is hidden by an AttributeError just because an ApplicationRunner object has no "log" attribute.

https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/wamp.py#L127

**Comment by meejah** [comment]
Hmm, that's ... weird. It should have a ``.log``, see https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/wamp.py#L81

**Comment by meejah** [comment]
Oh, I see: that was fixed since the last release. Thanks for the report!

So, this should be in the next release...(until then, you could try against master and if this is still an issue please re-open).
