### ISSUE TITLE
WebSocket: send message to specific user

### ISSUE THREAD

**Issue by deounix** [crossbario/autobahn-python#753]
I'm using websocket with asyncio so my question is :

1. how can I send message to specific user ?

Example :

I have 1 Server using websocket and I have 2 clients using websocket. so I want to send message to first client when the second connect.

I think it should be something like : self.sendMessage(user, "some one joined!")

**Comment by goeddea** [comment]
@deounix - This is an issue tracker, not a support forum. You should post questions like this at https://groups.google.com/forum/#!forum/autobahnws

If you're using plain WebSockets (not WAMP, which Autobahn|Python also provides) then it's entirely up to you how you do this. WebSocket does not provide any sugar here - you just send on the socket connection to the respective user.

When you use WAMP, then you can post to a topic which is specific to the user (e.g. "com.myapp.user1234.topci"), or use subscriber black- and whitelisting - http://crossbar.io/docs/Subscriber-Black-and-Whitelisting/
