### ISSUE TITLE
custom JSON encoder/decoder

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#76]
class WampServerFactory:

  json_encoder_factory = json.JSONEncoder
  json_decoder_factory = json.JSONDecoder

same for WampClientFactory. Those would then be used on any protocol
instance from this
factory for encoding/decoding messages.

So you could derive from JSONEncoder/Decoder to implement any custom
marshaling/demarshaling.

BUT: see the problems discussed in

https://github.com/oberstet/Autobahn/blob/master/test/json/json_datetime.py

AND: what about the other language bindings for WAMP: JS, Java?

**Comment by yli-cpr** [comment]
@oberstet , The problem I am having is the JSON serializer cannot serialize datetime python objects. Sure, I can manually convert datetime fields to strings for every object type I want to stream through WAMP. But it would be better if I can add a custom json encoder that automatically convert datetime (and some other types). Please reconsider.
