### ISSUE TITLE
Can't deny connection if onConnect is a coroutine

### ISSUE THREAD

**Issue by stan-sack** [crossbario/autobahn-python#770]
You're not catching the exception if onConnect is a coroutine. It means that I am unable to deny a connection by raising a ConnectionDeny

**Comment by oberstet** [comment]
dup of https://github.com/crossbario/autobahn-python/issues/791, which is later, but now I already have a PR branch named after the new issue, hence closing this one. shouldnt matter .. it'll be autolinked by GH
