### ISSUE TITLE
Autobahn in thread

### ISSUE THREAD

**Issue by mottetm** [crossbario/autobahn-python#778]
While trying to create a publishing only loop on a separate thread to push progress reports on a process, I ran into trouble trying to run the loop on a separate thread. 

`ValueError: set_wakeup_fd only works in main thread`

The problem comes from the ApplicationRunner trying to add a signal handler on the loop in the thread, which in turn triggers a test verifying that the signal is not handled anywhere but in the main thread.

```python
try:
    # set_wakeup_fd() raises ValueError if this is not the
    # main thread.  By calling it early we ensure that an
    # event loop running in another thread cannot add a signal
    # handler.
    signal.set_wakeup_fd(self._csock.fileno())
except (ValueError, OSError) as exc:
    raise RuntimeError(str(exc))
```

It would be nice to be able to be able to:

1.  toggle the handling of the SIGTERM by the runner using an argument,
2.  close the runner using a `stop()` or `close()` method

**Comment by oberstet** [comment]
So you'd like to have `installSignalHandlers=0` exposed?

http://twistedmatrix.com/trac/wiki/FrequentlyAskedQuestions#Igetexceptions.ValueError:signalonlyworksinmainthreadwhenItrytorunmyTwistedprogramWhatswrong

**Comment by oberstet** [comment]
Also, not sure if it applies to your situation, but in general doing things from a background thread that must run on the main thread: http://twistedmatrix.com/documents/current/core/howto/threading.html#invoking-twisted-from-other-threads

**Comment by mottetm** [comment]
In the mean time I realized that I had missed the `start_loop` option. So the issue is not really an issue after all. I just needed to execute `run(Session, start_loop=False)` and start the loop myself without adding any signal handler.
