### ISSUE TITLE
Documentation displays wrong version number

### ISSUE THREAD

**Issue by goeddea** [crossbario/autobahn-python#783]
http://autobahn.ws/python/index.html shows "Latest release: v0.13.0", which is completely outdated.

The wrong version number is not anywhere in the documentation source.

**Comment by oberstet** [comment]
The Autobahn web site content hasn't been deployed for ages .. the AB Py docs are at http://autobahn-python.readthedocs.io/en/latest/ - and these are automatically updated on each release.

IMO we should discuss what to do with autobahn.ws site .. what content should be there ..

**Comment by oberstet** [comment]
http://autobahn.ws/python should be redirected (S3) to http://autobahn.readthedocs.io/en/latest/

Similar for all others .. only question is the AB testsuite ..

**Comment by goeddea** [comment]
autobahn.ws no longer exists
