### ISSUE TITLE
Broken links in README.rst

### ISSUE THREAD

**Issue by rkrp** [crossbario/autobahn-python#786]
Links to documentation (https://autobahn-python.readthedocs.io/en/latest/) are broken and resulting in 404.

**Comment by oberstet** [comment]
Moved to https://autobahn.readthedocs.io/en/latest/

(the "autobahn" name was occupied by someone .. now we've got it)

**Comment by rkrp** [comment]
Can we setup a 301 permanent redirect for (http://autobahn-python.readthedocs.io) to (http://autobahn.readthedocs.io)? It would make sure all the old links in old articles and pages continue to work. 

Or I would love to send a PR fixing the links in README 😄

**Comment by oberstet** [comment]
I'm not sure if that is possible (redirect) on RTD .. FWIW, the original issue is https://github.com/rtfd/readthedocs.org/issues/2184
