### ISSUE TITLE
A component to communicate through serial with an Arduino

### ISSUE THREAD

**Issue by Vayel** [crossbario/autobahn-python#787]
I am using an Arduino UNO to command some electrical components and I communicate with an RPi through serial. After reading [this tutorial](https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/wamp/app/serial2ws), I wonder if it would be possible to automate this process. For instance, on the Arduino, I could do:

```c
#include <AutobahnSerial.h>

void setup() {
    // Init serial
}

void loop() {
    // ...
    AutobahnSerial.publish('my_topic', my_value);
    // ...
}
```

`AutobahnSerial.publish('my_topic', my_value);` would send a serial message like `[PUBSUB]my_topic: my_value`, that a Python component would receive and automatically transform in `session.publish("my_topic", my_value)`.

Both AutobahnSerial library and the Python `Serial2WAMP` component could be part of the Autobahn project.

**Comment by oberstet** [comment]
It is part of the project: see the examples.
