### ISSUE TITLE
URI shortcuts (CURIEs) support missing from autobahn-python

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/autobahn-python#801]
autobahn-js has `session.prefix('api', 'com.myapp.service')` which then lets you use `session.call('api:foo')` in all future interactions. the python WAMP implementation appears to be out of sync and does not have code that supports this.

**Comment by oberstet** [comment]
No, this is a purely client library thing: WAMPv1 had prefixes travel the wire, WAMPv2 does NOT have that.
