### ISSUE TITLE
SocketIO example?

### ISSUE THREAD

**Issue by italomaia** [crossbario/autobahn-python#813]
It would be quite nice to have an example of autobahn client connecting to a socket.io server.

**Comment by oberstet** [comment]
socket.io can use WebSocket as an underlying transport as far as I know. So you can implement a socket.io client **on top** of Autobahn at the **WebSocket client level**. Doing this as part of Autobahn is out of scope for us though.

Further, you can use Autobahn at the **WAMP client level**, and WAMP is simply better (our perspective of course) than socket.io: http://wamp-proto.org/compared/

So we (as a project) won't spend time on implementing something inferior (as we see it) to WAMP;) Seriously, we have lots to do. Sorry. Won't fix.

**Comment by italomaia** [comment]
Did not mean to upset anyone. Thanks for the answer.

**Comment by goeddea** [comment]
@italomaia - No problem, nobody was upset ;)
