### ISSUE TITLE
Weird issue running stand-alone components

### ISSUE THREAD

**Issue by OOPMan** [crossbario/autobahn-python#826]
Hey guys, so I have the following utility package in some of my code which I use to run stand-alone components quickly from the command-line. The code is included further down for reference.

However, I'm running into a weird issue. The following two example usages *should* work the same but they don't...

* `python -m runners.asyncio --component=some.module.ComponentClass --url=ws://localhost:8080/ 
   --realm=my.realm`
* `python runners/asyncio.py --component=some.module.ComponentClass --url=ws://localhost:8080/ 
   --realm=my.realm`

The problem is that while former works, the latter gives an traceback that looks like this:

```
Traceback (most recent call last):
  File "runners/asyncio.py", line 4, in <module>
    from autobahn.asyncio.wamp import ApplicationRunner
  File "venv/lib/python3.5/site-packages/autobahn/asyncio/__init__.py", line 36, in <module>
    from autobahn.asyncio.websocket import \
  File "venv/lib/python3.5/site-packages/autobahn/asyncio/websocket.py", line 32, in <module>
    txaio.use_asyncio()
  File "venv/lib/python3.5/site-packages/txaio/__init__.py", line 121, in use_asyncio
    from txaio import aio
  File "venv/lib/python3.5/site-packages/txaio/aio.py", line 47, in <module>
    import asyncio
  File "runners/asyncio.py", line 4, in <module>
    from autobahn.asyncio.wamp import ApplicationRunner
  File "venv/lib/python3.5/site-packages/autobahn/asyncio/wamp.py", line 40, in <module>
    txaio.use_asyncio()  # noqa
  File "venv/lib/python3.5/site-packages/txaio/__init__.py", line 122, in use_asyncio
    _use_framework(aio)
  File "venv/lib/python3.5/site-packages/txaio/__init__.py", line 138, in _use_framework
    getattr(module, method_name))
AttributeError: module 'txaio.aio' has no attribute 'using_twisted'
```

Have you guys seen this problem before? Any idea what the issue is?

Below is the code:

- `runners`
|-- `__init__.py`
|-- `asyncio.py`
|-- `twisted.py`

`__init__.py`
```python
# coding=utf-8
from __future__ import unicode_literals

import json
from argparse import ArgumentParser
from importlib import import_module
from os import environ

import txaio

__author__ = 'Adam Jorgensen <adam.jorgensen@opendna.ai>'


def generate_parser() -> ArgumentParser:
    """
    Generates an ArgumentParser instance for use by the `main` function
    defined in this module

    :return:
    """
    parser = ArgumentParser()
    parser.add_argument(
        '-c', '--component',
        default=environ.get('CROSSBAR_COMPONENT'),
        help='Fully-qualified path to a Component class'
    )
    parser.add_argument(
        '-u', '--url',
        default=environ.get('CROSSBAR_URL'),
        help=''
    )
    parser.add_argument(
        '-r', '--realm',
        default=environ.get('CROSSBAR_REALM'),
        help=''
    )
    parser.add_argument(
        '-e', '--extra-file',
        default=environ.get('CROSSBAR_EXTRAS_FILE'),
        help='Path to JSON file of data to be supplied to the '
             'Component via the config __init__ parameter'
    )
    parser.add_argument(
        '-s', '--use-ssl', dest='ssl', type=bool,
        default=environ.get('CROSSBAR_USE_SSL', False),
        help=''
    )
    parser.add_argument(
        '-l', '--loglevel', dest='log_level', default='info',
        help=''
    )
    # TODO: Add an argument for serializers
    return parser


def get_class(fully_qualified_class_path: str) -> type:
    """
    Returns a class given an input fully-qualified class path E.g.
    a.b.c.d.ClassName

    :param fully_qualified_class_path:
    :return:
    """
    module_name, class_name = fully_qualified_class_path.rsplit('.', 1)
    imported_module = import_module(module_name)
    return getattr(imported_module, class_name)


def main(application_runner_class: type):
    """
    Given an input CrossBar ApplicationRunner class, runs a Component
    defined using input from either the command-line or environment variables
    with parameters determined by said input.

    :param application_runner_class:
    :return:
    """
    parser = generate_parser()
    args = parser.parse_args()
    component = get_class(args.component)
    extra = None
    if args.extra_file is not None:
        extra = json.load(open(args.extra_file))
    runner = application_runner_class(extra=extra, **{
        key: value
        for key, value in vars(args).items()
        if key not in ('component', 'extra_file', 'log_level')
    })
    txaio.start_logging(level=args.log_level)
    return runner.run(component)
```

`asyncio.py`
```python
# coding=utf-8
from __future__ import unicode_literals

from autobahn.asyncio.wamp import ApplicationRunner

from runners import main

if __name__ == '__main__':
    main(ApplicationRunner)
```

`twisted.py`
```python
# coding=utf-8
from __future__ import unicode_literals

from autobahn.twisted.wamp import ApplicationRunner

from runners import main

if __name__ == '__main__':
    main(ApplicationRunner)
```

**Comment by meejah** [comment]
Hmm, that is odd. "In general" the most reliable way to run stuff is with "python -m" but I can't explain why the second doesn't work. Are you running inside a virtualenv? What OS/distribution?

**Comment by OOPMan** [comment]
@meejah This is, indeed, very strange. It gets stranger though. I decided to try and debug this using PyCharm so I created a run configuration, tested that it failed and then tried it again in debug mode expecting to have some luck digging into the exception. Unfortunately, when run through the Pydevd debugger the error does not occur and everything behaves as it should!

With regards to your questions, I am running this code inside a CPython 3.5.2 virtualenv on Kubuntu 16.10 64-bit.

**Comment by meejah** [comment]
On debian/ubuntu, `pip install --upgrade pip setuptools` in new virtualenvs is usually required/a good idea.

I would also be suspicious of `PYTHONPATH` perhaps being the culprit? For example, is "." in it?

**Comment by OOPMan** [comment]
I'm pretty sure my PYTHONPATH is okay but it's worth a look tomorrow, same
goes for the venv checks...

**Comment by meejah** [comment]
Just for fun, try re-naming `asyncio.py` to `myasyncio.py` or something; it's like something is shadowing an import and making `txaio` or something else sad. Are there other packages (or .py) files in paths that you've either installed or happen to be in `PYTHONPATH`?

Oh, and I think in the second invocation `"."` is *implicitly* in PYTHONPATH, whereas in the former it is not?

**Comment by OOPMan** [comment]
@meejah I renamed my `asyncio.py` module to `myasyncio.py` and that seems to have fixed it :-)

**Comment by meejah** [comment]
Hmm, okay!

So I think what was probably happening was that `runners` was in your PYTHONPATH (explicitly or implicitly, e.g. your current directory was in there) and so `import asyncio` was picking up that and not the built-in module.
