### ISSUE TITLE
Timing out client: IPv4Address(TCP, 'xxxx', xxx) in the twisted logs

### ISSUE THREAD

**Issue by tardyp** [crossbario/autobahn-python#829]
When using autobahn websocket, using browsers which idle, the buildbot logs are filled with "Timing out client: IPv4Address([...])"

this is coming from:
```
a064c5dff twisted/protocols/http.py (exarkun               2003-06-11 19:33:22 +0000 1644) class HTTPChannel(basic.LineReceiver, policies.TimeoutMixin):
[...]
a064c5dff twisted/protocols/http.py (exarkun               2003-06-11 19:33:22 +0000 2007)     def timeoutConnection(self):
a064c5dff twisted/protocols/http.py (exarkun               2003-06-11 19:33:22 +0000 2008)         log.msg("Timing out client: %s" % str(self.transport.getPeer()))
5f37cd1b8 src/twisted/web/http.py   (Cory Benfield         2017-01-13 20:23:38 +0000 2009)         self.loseConnection()
9497c99e8 twisted/protocols/http.py (itamarst              2001-12-27 17:17:12 +0000 2010)
```

I wonder if it would make sense to override this method in autobahn and drop this log.
Client timing out is obviously an expected behaviour, which does not require a log.

What do you think?

**Comment by meejah** [comment]
Yeah, it does seem to fill up the logs -- and I don't really see any usefulness there either, personally....

**Comment by oberstet** [comment]
I agree, it is annoying and mostly noise.

There is a corresponding issue https://github.com/crossbario/crossbar/issues/974

This likely needs bits in Twisted ..

**Comment by tardyp** [comment]
Do we have a twisted bug already?

**Comment by oberstet** [comment]
@tardyp I'm not aware of a Twisted issue tracking this ..

**Comment by meejah** [comment]
I do have a patch that fixes this without touching Twisted: https://github.com/crossbario/crossbar/pull/1060

Not *ideal*, because I basically just override the method that does the logging -- but I don't see any other solution because this Twisted code is still using the old-twisted-logger, so it's `log.msg` :/

**Comment by oberstet** [comment]
@meejah ah, right. you already fixed it;) I am catching up with stuff, merged this one. Only thing left: use the new LessNoisy thing in all places within CB where we do Web (REST bridge, Universal Transport ..

**Comment by meejah** [comment]
Because of the way it's set up, this patch works for the REST bridge as well.

It looks like the universal transport also (or, the way it steals the transport means the channel doesn't timeout, maybe?) In any case, I can't repeat this with the universal transport.

**Comment by oberstet** [comment]
@meejah thanks for checking!
