### ISSUE TITLE
Double logging bug

### ISSUE THREAD

**Issue by normanjaeckel** [crossbario/autobahn-python#834]
I have a small AutobahnPython app in two files this:

```python
# File runner.py

import logging
import sys

from autobahn.asyncio.wamp import ApplicationRunner

from .component import Component

logging.basicConfig(level=10)
logger = logging.getLogger(__name__)


def run():
    logger.info('Starting server')
    runner_kwargs = {
        'url': 'wss://demo.crossbar.io/ws',
        'realm': 'realm1'.
    }
    runner = ApplicationRunner(**runner_kwargs)
    runner.run(ZeitSonde)


if __name__ == '__main__':
    run()
```
```python
# File component.py

import asyncio
import logging

from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner

logger = logging.getLogger(__name__)
logger.setLevel(10)


class Component(ApplicationSession):
    def __init__(self, config):
        logger.debug('Init')
        super().__init__(config)

    async def onJoin(self, details):
        logger.debug('Server has joined to WAMP router')
        await asyncio.sleep(3)
        logger.debug('Server has joined to WAMP router 2')
```

This code should work. The problem is that the log messages from runner.py and sometimes the `Init` message appear once and the log messages from inside the `onJoin` method appear always twice in the log (in different format). I can not imagine why.

Also if I remove the setLevel from the second file the logging disappears although the root logger was set to DEBUG in the first file.

I use Python 3.6.1 and autobahn 0.18.1 (ArchLinux).

Any idea about this hidden logging magic? Thanks in advance.

**Comment by meejah** [comment]
So, `ApplicationRunner` is a high-level helper that starts the event-loop and logging for you. So you have started two loggers: the Python stdlib logger, and the txaio / autobahn logger. The ApplicationRunner-started logger logs at level "info". So if you turn the .debug()s into .info()s, then you do see your logs.

I see that the asyncio version doesn't take the `log_level` kwarg, which it should. So that's a bug.

Also: you can always just `print` in components being run by crossbar and it'll get logged.

**Comment by meejah** [comment]
If you want to, you can use the `txaio` logging APIs which gives you a cross-"platform" (asyncio/twisted) structured-log-like system: https://txaio.readthedocs.io/en/latest/programming-guide.html#logging

One advantage: it doesn't do the string-interpolation if you're not going to log (e.g. debug level logs).

**Comment by normanjaeckel** [comment]
Thanks. I solved my logging problems by using `txaio.start_logging(level=...)` as first line in the `run()` function so txaio takes control over the whole logging lib. Then calling `logging.info()` or such calls make output appear only once (The loglevel kwarg would not be enough because I would not be able to log something before calling `runner.run(Component)`).
