### ISSUE TITLE
Multiple threads being used by asyncio ApplicationRunner?!?!?!

### ISSUE THREAD

**Issue by OOPMan** [crossbario/autobahn-python#854]
Hi guys, I'm working with some Python 3 components that use asyncio and are run as guest workers in my Crossbar controller.

I've been having some weird issues lately that *seem* as if they could be threading-related deadlocks. Initially I was like, _that can't be happening, asyncio is single-threaded right?_ but when I ran `htop` and filtered the view to show one of my components it seems to tell a different story.

Here is a screenshot with `uvloop` powering things:
![image](https://user-images.githubusercontent.com/248980/27173170-fead6452-51b7-11e7-8ae5-0d71d5102e02.png)

and here is another with the stock `asyncio` loop:
![image](https://user-images.githubusercontent.com/248980/27173197-1c6e8502-51b8-11e7-8d34-b94268840a28.png)

and another with the stock `asyncio` loop after hitting a RPC end-point hosted by this component:
![image](https://user-images.githubusercontent.com/248980/27173243-498e0594-51b8-11e7-8b7b-5087ea2298d2.png)

as you can see, `htop` indicates that threads are in use. There are differences between `uvloop` (which seems to use a fixed pool of 4 threads) and the stock loop (which starts with 1 thread and then scales up when it handles an RPC call) but overall the story is the same: threads are in use.

Is this normal? Is there something wrong with my components? Could this cause deadlock issues with my component (which is using a aiomysql connection pool attacked via a decorator to the RPC function being called)?

**Comment by OOPMan** [comment]
Hmmmmmmmm, so further work using a debugger seems to indicate that my component code is running in a single-thread (as it should be?)

I would still love to know what these additional threads are for tho. Does anyone have any ideas?

**Comment by OOPMan** [comment]
Hmmmmmmmmmm, okay, it seems my deadlock issues might be due to an issue with `aiomysql`

**Comment by meejah** [comment]
Crossbar starts multiple sub-*processes* (e.g. each "realm" is a separate sub-process etc)

**Comment by OOPMan** [comment]
@meejah I am aware of that :-) In this case though I had configured `htop` to display a tree view the follows the format:

```
parent process
|
|---- child process
|      |---- child thread
|      |---- child thread
```
I suspect that what is actually going on is the threads being displayed are associated with I/O. I could be totally wrong though. Interestingly enough, when I ran in debug mode via PyCharm/IntelliJ I noticed the following:

1. With `uvloop`, there was only a single thread visible when stopped in a break-point
2. With the default loop, there was a main thread and two additional threads visible when stopped in a break-point. However, through testing I was able to confirm that all code running in the loop was confined to the main thread.

**Comment by meejah** [comment]
Okay, I'm not familiar enough with the internals of asyncio (or AIO libraries) to know if/when they use threads for things.

Twisted does use threads/threadpools for certain things in some situations, even though most people would call it "single threaded"...one example would in fact be their database abstraction layer; perhaps similar in asyncio.

**Comment by OOPMan** [comment]
@meejah Yeah, I'm not sure what is going on here either. In practise, however, it seems like the application code running under asyncio is behaving as it should so I'm not going to worry too much about whether or not the underlying library using multiple threads to service I/O :-)
