### ISSUE TITLE
WebSocket opening handshake timeout

### ISSUE THREAD

**Issue by ashetov** [crossbario/autobahn-python#855]
I'm trying to subscribe to WAMP feed over SSL using examples for autobahn-python library. Both twisted and asyncio examples permanently return the same error message: `dropping connection to peer tcp4:104.20.13.48:443 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)` I've tried to tune up some timeouts inside the library near transport_factory.setProtocolOptions(...) but unsuccessfully.

At the same time, similar autobahn-js code works good for me with the same WAMP-server. So I suppose there is some bug in autobahn-python library.

- url: wss://api.poloniex.com
- realm: realm1
- feed: ticker
- python 3.5.2
- autobahn-python v17.6.1
- nodejs v4.2.6
- autobahn-js v17.5.2

**Comment by ashetov** [comment]
Working js example:

```javascript
var autobahn = require('autobahn')
var connection = new autobahn.Connection({url: "wss://api.poloniex.com", realm: "realm1"})

connection.onopen = function(session) 
{
	function tickerEvent(args, kwargs) 
	{
		console.log(args)
	}
	session.subscribe('ticker', tickerEvent)
}

connection.onclose = function() 
{
  console.log("Websocket connection closed")
}

connection.open()

```

**Comment by ashetov** [comment]
Failed python example:

``` python
import asyncio
from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner

class Component(ApplicationSession):
    async def onJoin(self, details):
        def on_event(*args, **kwargs):
            print("Got event", args, kwargs)

        await self.subscribe(on_event, 'ticker')

    def onDisconnect(self):
        asyncio.get_event_loop().stop()

if __name__ == '__main__':
    runner = ApplicationRunner('wss://api.poloniex.com', 'realm1')
    runner.run(Component)

```

**Comment by subiol** [comment]
I am having the same issue, autobahn python will not connect to poloniex wamp api because the handshake times out.

I have created a simple test program in golang using the turnpike wamp library and it connects fine, so it seems to be a problem between autobahn python and the poloniex wamp api only.

**Comment by subiol** [comment]
The problem seems to be explained in https://github.com/crossbario/autobahn-python/issues/838

There is a solution offered, but only works with Twisted and my program used Asyncio.

**Comment by oberstet** [comment]
dup https://github.com/crossbario/autobahn-python/issues/838

**Comment by BackTrackCRoot** [comment]
can you solved the problem? i have same problem, can you tell me how to?
