### ISSUE TITLE
crochet with flask - how about flask_restful

### ISSUE THREAD

**Issue by chrisamow** [crossbario/autobahn-python#857]
autobahn-python/examples/twisted/wamp/app/crochet/example1/server.py

This is a great example to get developers pointed in the direction of adding async web to their existing app.

The problem in my case is, the app is dependent on the base resources, using flask_restful.  But that is the level where it probably makes the most sense to publish change notifications.  i.e. both the resource and the app want to be direct clientcode of crochet (and there is a constraint that the app is already clientcode of the resource.)  Is it merely a problem of looking at composition or should I think about it another way.

**Comment by oberstet** [comment]
https://groups.google.com/forum/#!forum/autobahnws
