### ISSUE TITLE
Angular cli - UglifyJs Unexpected token: name (Simple) 

### ISSUE THREAD

**Issue by codegastudio** [crossbario/autobahn-python#858]
Hello,
I am using autobahn package (17.5.1) in my angular-cli projet and i am not able to generate a production version cause i get the following error 

> ng build --prod
> UglifyJs Unexpected token: name (Simple) 

 I am not alone to get this error and the only solution founded is to downgrade to 0.11.2 version
 of autobahn as described in this issue post on [angular-cli project](https://github.com/angular/angular-cli/issues/6453)

I have try versions between 0.11.2 and 17.5.2 but no one work like 0.11.2

Thanks for your help
Regards

**Comment by OOPMan** [comment]
@codegastudio I think you maybe meant to register this in autobahn-js

**Comment by codegastudio** [comment]
@OOPMan oups !
you are right ! 
sorry
