### ISSUE TITLE
Why is disclose_me deprecated / removed?

### ISSUE THREAD

**Issue by richardartoul** [crossbario/autobahn-python#864]
Hello,

It looks like this library used to support disclose_me, but no longer does, but I can't figure out why. The feature still appears to be in the WAMP spec.

If that feature is no longer supported, what is the recommended way of doing RPC while still identifying the caller?

**Comment by meejah** [comment]
The right way to configure disclosure is via "authorization" (either static or dynamic). See e.g. http://crossbar.io/docs/Authorization/#dynamic-authorization

**Comment by richardartoul** [comment]
Isn't that in conflict with the spec though? I'm using the turnpike Golang router which implements the WAMP spec and it expects clients to disclose themselves. I can work around it, I just don't know why an RFC-specified feature would be purposefully omitted.

This feature becomes particularly useful when the router and the RPC callee are the same machine/application.

**Comment by meejah** [comment]
Hmm, okay. I'll re-open this for now. I'm not sure how this new way relates to the old one; perhaps the wamp-proto repository has more.

**Comment by oberstet** [comment]
Actually, this is a bug in the spec text https://github.com/wamp-proto/wamp-proto/issues/57

The Crossbar.io implementation is in line with what was the result of the discussion above: whether the identity of a publisher/caller to a respective URI should be disclosed or not should be under control of the router (configured there).

It is also a bug that AutobahnJS allows to set arbitrary options when publishing/calling (like this deprecated one). I wouldn't recommend relying on `disclose_me` ..
