### ISSUE TITLE
Using uvloop with asyncio wamp implementation

### ISSUE THREAD

**Issue by morissette** [crossbario/autobahn-python#868]
Would autobahn-python project be open to using uvloop in the asyncio event loop for performance gains or are there specific concerns around this?

**Comment by meejah** [comment]
This should work fine already. Or did you mean "uvloop should be the default"?

It may be more appropriate in the https://github.com/crossbario/txaio repository, perhaps; most autobahn code is implemented on top of that compatibility library.

**Comment by morissette** [comment]
So implementing in the _AsyncioApi class?

**Comment by meejah** [comment]
Possibly in the `use_asycnio()` method? I haven't thought hard about this, though .. possibly other things make sense :)

**Comment by meejah** [comment]
...but to expand on the above, it should already be possibly to "opt in" to uvloop with Autobahn (or any other txaio-using thing). Are you wanting this as an "optimistic default" or similar? (i.e. "if uvloop installed, use it")

**Comment by morissette** [comment]
Absolutely; that is the intention Im looking at currently for my current abstraction of crossbar

**Comment by morissette** [comment]
So many currents in that last comment. Should not comment on issues and drive.

**Comment by morissette** [comment]
Alright; gonna play with uvloop with current autobahn while converting some of my blocking methods to non-blocking.

Thanks, can probably close this for now.
