### ISSUE TITLE
request.params values as list (array)

### ISSUE THREAD

**Issue by Kostanos** [crossbario/autobahn-python#876]
Making connection to `autobahn.twisted.websocket` using URL: `wss:localhost:9000?customerId=2`

```
def onConnect(self, request):
  print(request.params)
```
prints:
```
{u'customerId': [u'2']}
```
any clue why customerId value is a list and not just string?

**Comment by meejah** [comment]
Probably so you deal with them uniformly as "always a list"? i.e. if you have two (or more) `customerId` fields for example.

**Comment by Kostanos** [comment]
for lists the parameters are use to go this way: `?customer[]=pepe1&customers[]=pepe2` or like this: `?customer[0]=pepe1&customers[1]=pepe2`
nobody expects `?a=b` comes as a=['b'], it is ridiculous, didn't saw it in any other framework/language. Even in python's frameworks itself.

**Comment by meejah** [comment]
I believe Twisted does this too.

I meant if you have query strings like `?customer=foo&customer=bar`

**Comment by Kostanos** [comment]
yea, twisted returns list always too, just checked it. :(

**Comment by oberstet** [comment]
> any clue why customerId value is a list and not just string?

because one query parameter can occur multiple time, so the value need to be collected into a list for the general case
