### ISSUE TITLE
peer did not finish the opening handshake in time

### ISSUE THREAD

**Issue by BackTrackCRoot** [crossbario/autobahn-python#884]
I use autobahn try to Poloniex.
but it display
`2017-08-18T20:13:31+0800 dropping connection to peer tcp4:104.20.13.48:443 with abort=True: WebSocket closing handshake timeout (peer did not finish the opening handshake in time)`

I read more issues in this project, but i can't find i how to fix this error.

my code is very easy

``` from twisted.internet.defer import inlineCallbacks
from autobahn.twisted.wamp import ApplicationSession, ApplicationRunner

class MyComponent(ApplicationSession):

    @inlineCallbacks
    def onJoin(self, details):
        print("session joined")
        # can do subscribes, registers here e.g.:
        # yield self.subscribe(...)
        # yield self.register(...)

if __name__ == '__main__':
    runner = ApplicationRunner(url=u"wss://api2.poloniex.com/", realm=u"realm1")
    runner.run(MyComponent) ```



so.. how to fix this error ? thanks !

**Comment by stefan-j** [comment]
What was the solution ? Could you point other searchers in the correct direction?

**Comment by BackTrackCRoot** [comment]
Thanks for your help.
