### ISSUE TITLE
Backoff policy options are not exposed

### ISSUE THREAD

**Issue by Evidlo** [crossbario/autobahn-python#886]
There should be a way to [override the default backoff policy](https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/wamp.py#L317-L330) in case people want a retry policy that is not exponentially increasing (constant interval, for example).

I don't know if it would be better to pass in a `backoffPolicy` object, or simply expose [some of the options available](https://twistedmatrix.com/documents/16.1.0/api/twisted.application.internet.backoffPolicy.html) in backoffPolicy.

I can patch this issue myself once I get some feedback.

**Comment by Evidlo** [comment]
Anyone have thoughts on this?

**Comment by oberstet** [comment]
ABJS has this (=> see "Options that control automatic reconnection"):

* https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#connection-options

We could expose options that follow above, and then map to Twisted's policy class or implement for asyncio under the hood.
