### ISSUE TITLE
Websocket server-side sendClose results in a connection reset instead of a graceful termination.

### ISSUE THREAD

**Issue by jansing** [crossbario/autobahn-python#887]
When using <code>WebSocketServerProtocol</code>'s <code>sendClose()</code> function, the underlying TCP connection gets reset (RST) instead of a graceful teardown (FIN/ACK). This leads to a non-clean call on the client side in <code>WebSocketClientProtocol</code>'s <code>connectionLost</code> handler.

This leads to messages like
> Connection to the other side was lost in a non-clean fashion.

To illustrate I modified the echo-example in examples/twisted/websocket.

`server.py`: On the server-side, when we recieve a "CLOSE" message from the client, close the connection.
```python
from autobahn.twisted.websocket import WebSocketServerProtocol, \
    WebSocketServerFactory


class MyServerProtocol(WebSocketServerProtocol):

    def onConnect(self, request):
        print("Client connecting: {0}".format(request.peer))

    def onOpen(self):
        print("WebSocket connection open.")

    def onMessage(self, payload, isBinary):
        if isBinary:
            print("Binary message received: {0} bytes".format(len(payload)))
        else:
            print("Text message received: {0}".format(payload.decode('utf8')))
            if payload.decode("utf8") == "CLOSE":
                self.sendClose()
        # echo back message verbatim
        self.sendMessage(payload, isBinary)

    def onClose(self, wasClean, code, reason):
        print("WebSocket connection closed: {0}".format(reason))


if __name__ == '__main__':

    import sys

    from twisted.python import log
    from twisted.internet import reactor

    log.startLogging(sys.stdout)

    factory = WebSocketServerFactory(u"ws://127.0.0.1:9000")
    factory.protocol = MyServerProtocol

    reactor.listenTCP(9000, factory)
    reactor.run()
```

`client.py`: The client is modified to send a "CLOSE" message as the second message. The factory reacts on a lost connection by either stopping the reactor (on proper close) or reconnecing (on errorous close, like in the reconnecting factory examples). Also added a bunch of debug messages.
```python

from autobahn.twisted.websocket import WebSocketClientProtocol, \
    WebSocketClientFactory

from twisted.internet.error import ConnectionDone

class MyClientFactory(WebSocketClientFactory):
    
    """Factory that terminates, when the connection is closed."""
    
    def clientConnectionLost(self, connector, reason):
        print("WebSocket connection lost (in factory) on reason: {0}".format(reason))
        if reason.type == ConnectionDone:
            # We are fine with exiting.
            print("Stop reactor.")
            self.reactor.stop()
        else:
            # Reconnect, connection dropped improperly.
            connector.connect()

class MyClientProtocol(WebSocketClientProtocol):

    def onConnect(self, response):
        print("Server connected: {0}".format(response.peer))

    def onOpen(self):
        print("WebSocket connection open.")
        self.no = 0
        
        def hello():
            self.no += 1
            if self.no == 2:
                self.sendMessage(u"CLOSE".encode('utf8'))
                self.sendClose()
                return
            self.sendMessage(u"Hello, world!".encode('utf8'))
            self.sendMessage(b"\x00\x01\x03\x04", isBinary=True)
            self.factory.reactor.callLater(1, hello)

        # start sending messages every second ..
        hello()

    def onMessage(self, payload, isBinary):
        if isBinary:
            print("Binary message received: {0} bytes".format(len(payload)))
        else:
            print("Text message received: {0}".format(payload.decode('utf8')))

    def onClose(self, wasClean, code, reason):
        print("WebSocket connection closed on code {1}: {0}".format(reason, code))

    def connectionLost(self, reason):
        # Debugging only, the actual work is done in clientConnectionLost in
        # the factory.
        print("WebSocket connection lost (in protocol) on reason: {0}".format(reason))
        print("Clean close:", reason.type == ConnectionDone) # Should be True, since we did it cleanly ...
        # Pass the event, so that 'onClose' event will be triggered.
        WebSocketClientProtocol.connectionLost(self, reason)


if __name__ == '__main__':

    import sys

    from twisted.python import log
    from twisted.internet import reactor

    log.startLogging(sys.stdout)

    factory = MyClientFactory(u"ws://127.0.0.1:9000")
    factory.protocol = MyClientProtocol

    reactor.connectTCP("127.0.0.1", 9000, factory)
    reactor.run()
    print("Good bye.")
```

This creates an infinite loop in the client (closing and reestablishing the connection), since in <code>MyClientFactory</code>'s <code>clientConnectionLost</code> the <code>reason.type</code> is <code>ConnectionLost</code>. Since the connection in closed properly on both sides, I think it should be <code>ConnectionDone</code>.

I tracked this down to <code>autobahn.websocket.protocol.WebSocketProtocol</code>'s <code>onCloseFrame</code>, which uses <code>self.dropConnection(abort=True)</code> (line 729) to close the server-side connection if it recieves a 'reply-close' frame and <code>self.dropConnection(abort=False)</code> (line 756) if the client initiated the close.
<code>abort=True</code> seems to do a reset on the TCP connection, whereas <code>abort=FALSE</code> tears it down gracefully. Changing also to <code>abort=False</code> in line 729 seems to be the correct behavior.

**Comment by oberstet** [comment]
A WebSocket implementation that receives an invalid WebSocket message should hard drop the connection by default, which is why the uses of the abort flag is correct as it is.

**Comment by jansing** [comment]
Thanks for the quick reply.
My argument is, that the WebSocket message, that was received is not invalid:
To my understanding, WebSockets should be closed by a closing frame on both sides (https://tools.ietf.org/html/rfc6455#section-1.4).
Lines 714-738 in `protocol.py` handle the situation, where the side running the code first sends the closing and then receives the closing frame from other side. This is also, what the comment says:
```python
# We already initiated the closing handshake, so this
# is the peer's reply to our close frame.
```
So the closing frame from the other side is not invalid and the underlying connection should be teared down gracefully.

**Comment by chrisnorman7** [comment]
I'm also struggling with this issue I think.

On the server side I've got:
    def disconnect(self, text=None):
        """Close this websocket, sending text as reason."""
        self.sendClose(code=self.CLOSE_STATUS_CODE_NORMAL, reason=text)


If I call that:
con.disconnect('Bye bye.')

I get:
Connection failed: Bye bye..

Am I using the wrong code to sendClose?

Cheers.
