### ISSUE TITLE
component api: authentication types

### ISSUE THREAD

**Issue by meejah** [crossbario/autobahn-python#905]
Currently it's only possible to configure authentication for `cryptosign` and `wampcra` methods using the component API; the others should be added as well.

**Comment by aarcane** [comment]
This API is actually perfect for a project I'm on now.  I'm using TOTP and TOKEN based authentication methods currently.

**Comment by oberstet** [comment]
subseded/fixed in https://github.com/crossbario/autobahn-python/issues/964
