### ISSUE TITLE
Serialization error when local exception's arguments are not serializable

### ISSUE THREAD

**Issue by agronholm** [crossbario/autobahn-python#920]
If during handling of a WAMP invocation an exception is raised, Autobahn attempts to send the arguments of this exception to the caller. This will fail if one of the arguments cannot be serialized. Therefore Autobahn must never try to serialize such arguments, but instead send string representations when an argument is not a natively JSON serializable type.

**Comment by oberstet** [comment]
Do you have a traceback?

**Comment by oberstet** [comment]
> This will fail if one of the arguments cannot be serialized. 

yes, as with all WAMP results

> Therefore Autobahn must never try to serialize such arguments

no
