### ISSUE TITLE
No workers configured!

### ISSUE THREAD

**Issue by 9599** [crossbario/autobahn-python#938]
When I typed"crossbar start",it shows "**successful "but no workers configured so that I can't run '/wamp/rpc/arguments/backend.py or frontend.py'on Centos7.But I can run'./run-all-examples.py'.So what's matter it is?

**Comment by goeddea** [comment]
This is an issue tracker for the autobahn-python library, not a help forum for the crossbar.io messaging router.

Anyway: Not enough detail in your question for an answer to be possible,

Closing this.
