### ISSUE TITLE
pip not working for requirements.txt when running autobahn Python with make start

### ISSUE THREAD

**Issue by NumesSanguis** [crossbario/autobahn-python#944]
I posted this question on stackoverflow, but since I didn't get a response, I post it here as well: [https://stackoverflow.com/questions/48578719/pip-not-working-for-requirements-txt-when-running-autobahn-python-with-make-star](https://stackoverflow.com/questions/48578719/pip-not-working-for-requirements-txt-when-running-autobahn-python-with-make-star)
Sorry if this is the wrong place.

From other descriptions I've found on the internet it's due to docker's DNS not being configured properly. All suggestions however point to modifying the docker container, but since I use `make start` for both my `crossbar` and `autobahn-python` project, I don't know how to access it as a Docker container. Passing arguments like `--dns 8.8.8.8` in the Makefile also don't help.

The [documentation](https://crossbar.io/docs/Getting-Started/) is not really pointing in a direction I can find help with this issue:
> The containers as-is are there to demonstrate principles.
> 
> To develop your own applications, you need to modify the code they run as well as the Crossbar.io config.
> 
> The application components are in the app directory of each of the subdiretories (and, in the crossbar directory, in the web directory).
> 
> The Crossbar.io configuration file is in the .crossbar subdirectory.

Help with this issue is greatly appreciated.

**Comment by oberstet** [comment]
pls see https://stackoverflow.com/questions/48578719/pip-not-working-for-requirements-txt-when-running-autobahn-python-with-make-star#comment84272977_48578719
