### ISSUE TITLE
Protocol error while handling subscribe error 

### ISSUE THREAD

**Issue by stanleyxu2005** [crossbario/autobahn-python#948]
I'm publish message from the latest `autobahn-js` to a `autobahn-python` subscriber. The router is not crossbar, but a wamprpc 2.0 implementation `wamp-server`. The python code uses `serializers=[JsonSerializer()]`.

Now the python subscriber receives a message like this
```
    [36, 8483690563665722, 8483690563665722, 'testpy.echo', [], {}]
```
But I met the error
```
  File "C:\Users\xusta\Miniconda3\lib\site-packages\autobahn\wamp\message.py", line 274, in check_or_raise_extra
    raise ProtocolError(u"{0}: invalid type {1}".format(message, type(value)))
autobahn.wamp.exception.ProtocolError: 'details' in EVENT: invalid type <class 'str'>
```
This is how I subscribe
```
    client.subscribe(shutdown, topic="testpy.shutdown", options=SubscribeOptions(details=False))
```

The 4th parameter is topic. I see the [WAM RPC spec](http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.9.2) support to be a string.
```
    [16, 239714735, {}, "com.myapp.mytopic1", [], {"color": "orange",
        "sizes": [23, 42, 7]}]
```

In `autobbahn\wamp\message.py` line 2439, the 4th parameter is not topic but details
```
        # my proposed workaround
        # if type(wmsg[3]) == str:
        #     wmsg[3] = dict(topic=wmsg[3])

        details = check_or_raise_extra(wmsg[3], u"'details' in EVENT")
```
It requires this param to be a dict, like this `{topic: "'testpy.echo"}`. Is it possible to accept a string arg? I currently use a workaround. But I think autobahnjs and autobahnpython should be able to communciate very well.

**Comment by oberstet** [comment]
not a bug here, conforms to spec: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/message.py#L2306

**Comment by stanleyxu2005** [comment]
Thank you very much, it looks like a `wamp-server` (nodejs) implementation problem. I think I found the root cause.

**Comment by oberstet** [comment]
@stanleyxu2005 np, glad you found it!
