### ISSUE TITLE
set auto-reconnect with Component?

### ISSUE THREAD

**Issue by sk-gara** [crossbario/autobahn-python#951]
Is ist possible to set auto-reconnect settings when using `autobahn.twisted.component.Component` similar to `autobahn.twisted.wamp.Applicationrunner`?

**Comment by meejah** [comment]
Yes, it will automatically re-connect by default. You can set `max_retries` etc as options in the config you give to component. Questions like this are better asked on the mailing-list, gitter.im or IRC.
