### ISSUE TITLE
Double logging when using the std-lib loggging module

### ISSUE THREAD

**Issue by rdebroiz** [crossbario/autobahn-python#952]
As I am not able to do what i want using the txaio logging API, I decided to not call `txaio.start_logging` and use only the standard logging module for my application.

I am facing this issue :  #834

The problem is that at some point after i call `ApplicationRunner.run(ApplicationSession)` a preconfigured `_TxaioFileHandler` is added to the root logger.

Would be great to have an option to disable it.

Also when using asyncio, the logger used by Autobahn is the root logger, it would be better IMO to have a dedicated logger for autobahn.

**Comment by meejah** [comment]
https://github.com/crossbario/txaio/pull/121 fixes part of this.

`ApplicationRunner` does call start_logging, but that's more of an Autobahn issue I'd say? (You can get `component.run` to not call start_logging or use `.start()`).

If there's still more work needed directly in txaio, please re-open this.
