### ISSUE TITLE
Blocking call when using ProgressiveResult (asyncio)

### ISSUE THREAD

**Issue by rdebroiz** [crossbario/autobahn-python#954]
* What I want to do: send a  heavy payload to a remote component using the progressive result.

* What I do: The sender creates a function to send the payload by chunk, register that function with a temp uri then call a `receive` rpc registered by the Receiver that take the temp uri in parameter. the `receive` function got the chunk send by the Sender and reconstruct the payload once all pieces have been received.

* What happens: the sender block after it calls the `receive` rcp. ie it blocks while sending stuff if details.progress is not None.

* Minimal example: https://gist.github.com/rdebroiz/0143ab027c17cc641ad20cea5238821c

Start first a receiver
```sh
python autobahn_progressive_send_block.py receive
```
then a sender
```sh
python autobahn_progressive_send_block.py send
```
The receiver call a rcp to the sender that just print "pouet" each time it receive a chunk.

On the receiver console all works as expected. On the sender console no ping/pong  message are received until all the chunk have been sent, all the pouet message arrived when all the chunk have been sent as well

* What I would expect: receive pouet and ping/pong messages while it is still sending chunks. But the ping/pong just stop until sending all the chunks is finish, then it comes back and the sender receive all the pouet message.

**Comment by rdebroiz** [comment]
Maybe what'd like is to write something like:

```python
async def send_bytes_by_chunk(payload, details=None):
    if details.progress:
        for i in range(0, len(payload), CHUNK_SIZE):
            await details.progress(payload[i:i+CHUNK_SIZE])
            print("send chunk!")
    else: return payload
```
ie have an async `details.progress()`

**Comment by meejah** [comment]
Yes, you've gotten closer to the answer yourself. I don't know exactly how you'd express that in asyncio off the top of my head, but in Twisted you'd either do `@inlineCallbacks` and have a bare `yield` in the loop, or do your own tail-recursion with something along the lines of: `reactor.call_later(0, send_more(chunks[1:]))`

**Comment by rdebroiz** [comment]
> you'd either do @inlineCallbacks and have a bare yield

This is what I did in the line above (if my understanding of twisted is correct) but it doesn't work because `details.progress`  does not return a coroutine, it is not async. ie: There is no async keyword in its definition in AP. (nor @inlineCallbacks decorator in the twisted implementation I suppose).


> or do your own tail-recursion with something along the lines of: reactor.call_later(0, send_more(chunks[1:]))

Not sure to understand what you mean here, could you be more explicit?

**Comment by meejah** [comment]
Right, but in Twisted you can just do "yield" inside @inlineCallbacks and it's kind-of-the-same-as re-calling your routine with a "reactor.callLater" -- it lets the reactor "do an iteration" (so, e.g., service any pending I/O or timers).

"Tail recursion" is like you're writing your own loop without a "for" or "while". So you'd chunk out your input and call something like:

```
def send_one(chunks):
   if not len(chunks):
       return
   send(chunk[0])
   reactor.callLater(0, send_one, chunks[1:])
```
So then each "reactor loop" you'll send one chunk and give other things a chance to do some work as well.  For example, imagine running 10 of these at once.

**Comment by rdebroiz** [comment]
Ok I got you now, the equivalent of a "bare" yield in asyncio is `await asyncio.sleep(0)`.  Thanks!

**Comment by rdebroiz** [comment]
Anyway I'm surprised that such a thing is not already done in autobahn, I think one would expect progressive result being non blocking on both size (progress and on_progress calls) without doing anything, no?

**Comment by meejah** [comment]
Autobahn's progress calls *are* non-blocking -- or do you mean "I'd like a nicer API to send a big chunk of data to another place"..?

**Comment by rdebroiz** [comment]
I was going to say that a hint in the doc and the example that it's the user's responsibility to yield if needed to the event loop in `detail.progress`  would have helped me. 

It's kind of already there. Maybe a comment to emphasize this point would be great:
```python
# In autobahn-python/examples/asyncio/wamp/rpc/progress/backend.py

        async def longop(n, details=None):
            if details.progress:
                for i in range(n):
                    details.progress(i)
                     # Yield to the loop here, 
                     # otherwise it will block until all `details.progress` calls 
                     # has been done. 
                    await asyncio.sleep(1)
```
Also what confused me, I think, is that it's not needed  for `on_progress`, The event loop got the hand back after each call of `on_progress` even if you don't explicitly yield to it. It would be good to have the same behavior on both side.

**Comment by oberstet** [comment]
All of this behavior has nothing to do with Autobahn, but with async programming.
