### ISSUE TITLE
how to send json from python.

### ISSUE THREAD

**Issue by dvhwgumby** [crossbario/autobahn-python#970]
We have three clients, one in python (data source), one in java and one in C++ (latter two data consumers), all using Autobahn.  We send our data as a single string of JSON rather than breaking it apart into the WAMP argument/keyword mechanism.

The python program just sends submits a dict and it gets turned into something that looks like JSON but quotes the strings with '.  The java consumer apparently accepts this illegal coding, producing JSON directly from the network transmission, but the C++ version rejects it. 

I changed the python code to do ```return (json.dumps(response_dict))``` instead of ```return (json.dumps(response_dict))``` which makes C++ happy but causes my colleague with the Java version to complain that he just gets a string.

What's the intended behavior here?  I'm honestly surprised that the Java version works at all.

**Comment by meejah** [comment]
https://gitter.im/crossbario/public or https://groups.google.com/forum/#!forum/autobahnws or #autobahn on freenode are probably better places to ask questions like this.

The short answer is: just use `kwargs`.

**Comment by oberstet** [comment]
@dvhwgumby 

> We send our data as a single string of JSON

Well, this is misusing WAMP/Autobahn. So the answer is: do not serialize yourself, but let Autobahn / WAMP do that.
