### ISSUE TITLE
Asyncio: ApplicationRunner doesn't handle correctly restart of the event loop

### ISSUE THREAD

**Issue by rdebroiz** [crossbario/autobahn-python#971]
Running a `asyncio.wamp.ApplicationSession` with `ApplicationRunner.run(session start_loop=True)`
two consecutive times fails the second one.

Minimal example: https://gist.github.com/rdebroiz/1854c2bab7da929e376c273d262c805a

Adding
``` python
if loop.is_closed():
    asyncio.set_event_loop(asyncio.new_event_loop())
```
Before to run the ApplicationRunner the second times make it works as expected.

This code snippet is coming from and is already called by `asyncio.wamp.ApplicationRunner.run`
see: https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/wamp.py#L246

Any ideas of what is going on?

**Comment by om26er** [comment]
I can definitely reproduce the issue and after some initial debugging, I am a little confused as we are definitely checking if the loop is closed and setting a new one.

That's most probably a race condition, needs more digging.

**Comment by om26er** [comment]
Commenting this out seems to fix the issue https://github.com/crossbario/autobahn-python/blob/master/autobahn/asyncio/wamp.py#L283

**Comment by rdebroiz** [comment]
Just for the record, I got the same behavior with components, except that refresh the event loop between the two calls to run does not fix it.
```python
#!/usr/bin/env python
# usage: python autobahn_start_AS_two_times.py host port realm
import sys
from autobahn.asyncio.component import Component, run

import txaio
txaio.use_asyncio()

if __name__ == '__main__':
    url = f"ws://{sys.argv[1]}:{sys.argv[2]}/ws"
    realm = sys.argv[3]

    def main(session, details):
        pass

    component = Component(main=main, transports=url, realm=realm)

    run(component, 'debug')
    # let's do it again
    run(component, 'debug')
```
Output
``` python
  File "trash.py", line 19, in <module>
    run(component, 'debug')
  File "/local/ch196713/virtualenvs/****/lib/python3.6/site-packages/autobahn/asyncio/component.py", line 355, in run
    loop.add_signal_handler(signal.SIGINT, partial(nicely_exit, 'SIGINT'))
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 85, in add_signal_handler
    self._check_closed()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by om26er** [comment]
> Just for the record, I got the same behavior with components, except that refresh the event loop between the two calls to run does not fix it.

I have a fix for component API here: https://github.com/crossbario/autobahn-python/pull/979

**Comment by om26er** [comment]
I have a fix for original bug as well: https://github.com/crossbario/autobahn-python/pull/979/commits/41001b42dfd926c653df90f51c80bd28d91ba1ba
