### ISSUE TITLE
When serialize invalid Json object, the WAMP session will be ended

### ISSUE THREAD

**Issue by stanleyxu2005** [crossbario/autobahn-python#994]
**In short,** regarding the WAMP RPC call, if I send some non Json serializable object, I except the caller should still receive an error response, .e.g. protocol error. But in my case, the WAMP session is just closed. I don't know, what I did wrong.

**The longer version:** 
I have registered a function `load_csv`. It uses internally pandas to load csv files. I want to return the csv as a 2d array. Somehow, pandas use a customized list class to represent the data. When I try to send back such a 2d array, WAMP simple closed the session. Here is the message I see.
```
2018-04-25T18:01:21 session closed with reason wamp.error.goodbye_and_out [None]
```

Here are two questions:
1. I don't see any detail of encoding logs with the following code, How to enable related logs?
2. How to keep the WAMP session not to be closed, in case the response is not a valid Json object?

Here is my actual minimal code example:
```python
def load_csv(self):
        import pandas
        df = pandas.load_csv("bad.csv")
        return df.as_matrix().tolist() # type is <class: list>, content is [1,2,3,,,,,,]


class Component(ApplicationSession):
    log = txaio.make_logger()

    async def onJoin(self, details):
        try:
            await self.register("load_csv", load_csv)
        except:
            sys.exit(1)
    async def onDisconnect(self):
        asyncio.get_event_loop().stop()

    async def onUserError(self, fail, msg):
        print("user error", flush=True)

runner = ApplicationRunner(
    conn['url'],
    realm=conn['realm'],
    serializers=[JsonSerializer()]
)
runner.run(Component)
```

**Comment by oberstet** [comment]
you cannot send a object that cannot be serialized

**Comment by stanleyxu2005** [comment]
Yes. This is a programmer error of one single RPC request. Do you think, whether WAMP should throw an exception in case of error (no matter what it is), instead of just close the WAMP session? 

From my understanding, just like one Python web service is accepting all requests. If one request is invalid, server should response with an error message instead of shutting down the service.
