### ISSUE TITLE
Publish only delivered to subscriber if PublishOptions(acknowledge=True)

### ISSUE THREAD

**Issue by markope** [crossbario/autobahn-python#997]
The setup is rather standard
one python server publishing and one JS client subscribing

Crossbar Version 18.3.1
Autobahn Python Version 18.4.1
Autobahn JS Version 18.3.2

(excludeMe=True/False is not part of the issue)

**Comment by meejah** [comment]
You mean no publishes at all are delivered w/o acknowledge=True?

**Comment by markope** [comment]
yes

**Comment by meejah** [comment]
With lastest autobahn + crossbar on python3, pubsub works fine with the Autobahn example router config and both the asyncio and twisted "basic" pubsub examples (and to JS).

Crossbar >= 18.5.1 and Autobahn >= 18.4.1

**Comment by oberstet** [comment]
cannot reproduce
